### ISSUE TITLE
Incoming file transfer

### ISSUE THREAD

**Issue by hit** [emesene/emesene#744] opened 2011-07-22 16:39 UTC
There is no information about incoming file transfer, except desktop notification. No accept, no decline buttons in conversation so I can't even receive a file.

**Comment by pepeleproso** [comment] 2011-07-22 23:48
Are you using git version? it's working here.

**Comment by hit** [comment] 2011-07-23 11:42
Always git and not working here. Also using adium if that counts something.

**Comment by Sbte** [comment] 2011-07-23 14:09
Then it's a dupe of #499 I guess

**Closed as completed by Sbte** 2011-07-23 14:09 UTC

**Comment by Sbte** [comment] 2011-07-23 14:11
@pepeleproso: IIRC it only happened for certain clients? So I suppose it works for emesene->emesene but not for for example WLM->emesene?

**Comment by pepeleproso** [comment] 2011-07-23 20:42
WLM ->emesene works here I tested version 2009 and 2011
emesene ->emesene works here
