### ISSUE TITLE
Python-gtkspell improvement

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#631] opened 2011-06-05 11:55 UTC
Why not select in each conversations window a language rather than just one language for every conversation windows? Like when you right click a windows you select let's say Portuguese an the other Spanish, emesene should remember in which window it should spell-check in Portuguese and in Spanish.

**Comment by c10ud** [comment] 2011-08-10 21:08
this involved emesene/gui/gtkui/TextBox.py and a bunch of calls to config...if someone wants to take the job, you're welcome!

**Comment by sturmer** [comment] 2011-08-11 14:16
I'm looking into this :)

**Comment by Sbte** [comment] 2011-08-19 16:01
<sbte> c10ud, i think we can override the set_language method
<sbte> def set_language(...):
<sbte> gtkspell.set_language(bla)
<sbte> self.config.d_spell_config[user] = bla

I think this would allow us to implement this without a new window. You'd just have to use the right-click menu, which should work automagically.

Edit: oh, this is in an overridden Spell() class

**Comment by sturmer** [comment] 2011-08-24 07:52
After what we discussed, should we consider my fix done? should I go for a pull request?

**Comment by Sbte** [comment] 2011-08-24 07:57
If you save per-user settings now, then I guess sure. I'll implement the right-click menu later if c10ud agrees with me it's actually a good thing. And if I can get it to work in the first place.

**Comment by sturmer** [comment] 2011-08-24 13:53
I'll get it done soon.

**Comment by sturmer** [comment] 2011-09-04 13:25
Sbte, guys, 

I've been looking into this a little more. I provided a patch that _in my opinion_ solves the issue, but I gave up the per-user setting save, for a number of reasons. The following are the result of my understanding of the issue and of the project, and they are opinions, so please read them as such:
1) The only way I've found to save the setting per-user is to add a field to the gui.gtkui.ConversationInformation object. This is however conceptually wrong, because this information is not written by the local user, but from the contact, and retrieved somehow (like the nick history, that depends on the other user changing his nick)
2) If you restart emesene, you'll lose that setting anyway, because no part of the local config is saved locally (unless I'm wrong, which is very probable -- see 3)
3) At this level, this issue is not "easy", for sure. I'm a Python and an emesene novice (not a programming novice though), and I've spent already some weeks' spare time to try to solve this issue to no avail.
4) I still don't agree that the user that opened the issue wants the spell-check language to be saved when he closes the conversation window. It would be a good thing, but it was not requested.

Comments are welcome.

**Comment by Sbte** [comment] 2011-09-04 14:02
Here's some answers:

1) Not sure what you mean here. You just need to add a dict to session.config. d_user_spell or something
2) Everything stored in self.session.config is saved locally
3) Maybe we just think it's easy :P
4) It'd still be a good thing though

**Comment by c10ud** [comment] 2011-09-04 14:19
@sturmer: while every contribution is appreciated, i think you misunderstood what this issue is about because it's _already_ possible to change the language checked by gtkspell: just right-click the input box and you'll have an entry called "Languages" which makes you choose the locale that's going to be spell-checked. It's already built-in in gtk thanks to gtkspell.

The issue here is about extending this functionality for people that talk multiple languages e.g. i talk with sbte in "nl" and i'd like to get my sentences spell-checked in his window while keeping "en" by default for everyone else.

The issue is marked as "easy" because (i may be wrong though) it's really a matter of adding some calls to config, e.g. reading/saving a dict {account:locale,} and checking out values when initializing the gtk-spell object in conversation, nothing more (i guess (?))

The tricky part could be: do we need a separate gui for this or we can pack it in the already avail widgets?

I think for a basic implementation you just check for language changes and save them, regardless the user wants it or not. More complex solutions are really not needed (i hope people ain't changing the way they speak everyday (?))

Here's why i think your code doesn't solve this issue nor offers something we already have

**Comment by ghost** [comment] 2011-09-04 19:36
@sturmer
4) I still don't agree that the user that opened the issue wants the spell-check language to be saved when he closes the conversation window. It would be a good thing, but it was not requested.
Sorry my bad i forgot to mention it, I do want it to be permanent.

@c10oud
Exactly what i meant, I want the modification to be permanent.

Nice to see that you are working on this.

**Comment by ghost** [comment] 2011-09-04 19:36
Oh i didn't want to close it :s

**Comment by sturmer** [comment] 2011-09-06 16:39
Sbte, c10ud, soued031: thanks for the comments.
c10ud, soued031, I think I get it now. I'll try to use your suggestions and see what happens.

**Comment by DimitrisSevastakis** [comment] 2011-10-18 15:01
hello, i am new to the project and to python in general but I hope that i will be of some help:)
to begin with, i think the language should be assigned to the windows that is created.. so adding a lang variable in windows class in Window.py to save the current language is needed, and then 1 method in the textbox to get the language from the window object and another method to change it. how does that sound?

**Comment by Sbte** [comment] 2011-10-18 15:41
That won't work. A window can contain multiple conversations. This should be implemented in the TextBox and the language should be determined from fetching the contact's language from the config. The language should only be saved in the config if it differs from the default.

**Comment by DimitrisSevastakis** [comment] 2011-10-18 15:55
ah yes.. forgot about the tabbed interface:P i will take a swing at it in the weekend!:)

**Comment by c10ud** [comment] 2012-08-27 16:16
looks like noone took the easy job, too bad..

**Closed as completed by c10ud** 2012-08-27 16:16 UTC
Labels: feature
