### ISSUE TITLE
msn: display images do not download, having to manually enter personal message on every login

### ISSUE THREAD

**Issue by SWOriginal** [emesene/emesene#75] opened 2010-08-15 15:32 UTC
when using msn contact's display images don't download and im having to enter my personal message on every login

**Comment by c10ud** [comment] 2010-08-15 20:33
with papyon 0.5? not good

**Comment by SWOriginal** [comment] 2010-08-16 06:57
yeah using papyon0.5, contacts have also told me my user name is just showing as my email address even tho it shows as my name on the main header

**Comment by c10ud** [comment] 2010-08-18 11:06
i'm closing this issue since the problem is the same as file transfers :)

**Closed as completed by c10ud** 2010-08-18 11:06 UTC
