### ISSUE TITLE
Custom emoticons and RichBuffer output

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#129] opened 2010-10-29 12:16 UTC
it tries to look in 

ven/.config/emesene2

where it should look in

/home/sven/.config/emesene2

so I guess this line

```
    pixbuf = gtk.gdk.PixbufAnimation(path[7:])
```

51 in RichBuffer.py should be changed to

```
    pixbuf = gtk.gdk.PixbufAnimation(path)
```

If you do that, the next thing you run into is Issue 126. I would attach a patch, but I have no idea how to do that with this system.

EDIT: It's more difficult than this. When I received an animated gif, it worked (up to Issue 126). When I received a PNG, the above error came up.

EDIT2: 

Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 63, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 110, in **call**
    apply(self.f, (self.c(),) + arg)
  File "/home/sven/emesene/emesene/gui/base/ConversationManager.py", line 47, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/home/sven/emesene/emesene/gui/base/Conversation.py", line 223, in on_receive_message
    received_custom_emoticons, user_emcache.path, self.first)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 301, in receive_message
    self.append(first + middle + last, cedict, self.config.b_allow_auto_scroll)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 275, in append
    TextBox.append(self, text, scroll)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 52, in append
    self._buffer.put_formatted(text)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 31, in put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 71, in _put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 71, in _put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 66, in _put_formatted
    self.put_image(child.src, child.alt)
  File "/home/sven/emesene/emesene/gui/gtkui/RichBuffer.py", line 51, in put_image
    pixbuf = gtk.gdk.PixbufAnimation(path[7:])

**Comment by c10ud** [comment] 2010-10-29 15:33
Fix path in RichBuffer, thanks Sbte. Closed by 79d283491c039677a25fa15753f0161db3dfb5d8

**Comment by Sbte** [comment] 2010-10-29 15:38
Actually that's not a fix, as I said in my first edit. Local emoticons have the style

file:///home/sven/....

So path is defined differently at two places. A real fix would probably be to define it everywhere in the same way, but you could also hack around that by doing

if path[0:6] == "file://":
    pixbuf = gtk.gdk.PixbufAnimation(path[7:])
else:
    pixbuf = gtk.gdk.PixbufAnimation(path)

**Comment by c10ud** [comment] 2010-10-29 16:09
ouch, i'll dig _deeper_

**Comment by c10ud** [comment] 2010-10-29 16:20
can you try changing that line to:
pixbuf = gtk.gdk.PixbufAnimation(os.path.abspath(path))

and see what happens?

**Comment by c10ud** [comment] 2010-10-29 16:21
nvm, doesn't work

**Comment by c10ud** [comment] 2010-10-29 16:28
try latest pull

**Comment by Sbte** [comment] 2010-10-29 16:31
Don't you need at least a : after else? Just sayin' ;)

**Comment by Sbte** [comment] 2010-10-29 16:54
Ok, here's what happens now:

if the emoticon is the first message, you get just the name of the picture, not the actual picture. The emitocon also wasn't saved to the emoticon folder in ~/.config/emesene2/email/emoticons

The second try on that same emoticon doesn't work either. If you try this emoticon, or a different one on the second or later message, you get

Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 63, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 110, in **call**
    apply(self.f, (self.c(),) + arg)
  File "/home/sven/emesene/emesene/gui/base/ConversationManager.py", line 47, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/home/sven/emesene/emesene/gui/base/Conversation.py", line 224, in on_receive_message
    received_custom_emoticons, user_emcache.path, self.first)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 301, in receive_message
    self.append(first + middle + last, cedict, self.config.b_allow_auto_scroll)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 275, in append
    TextBox.append(self, text, scroll)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 52, in append
    self._buffer.put_formatted(text)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 31, in put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 71, in _put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 71, in _put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 66, in _put_formatted
    self.put_image(child.src, child.alt)
  File "/home/sven/emesene/emesene/gui/gtkui/RichBuffer.py", line 54, in put_image
    pixbuf = gtk.gdk.PixbufAnimation(path)
GError: Openen van bestand ‘None’ mislukt: Bestand of map bestaat niet
[18:46:40 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: Openen van bestand ‘None’ mislukt: Bestand of map bestaat niet
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 63, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 110, in __call__
    apply(self.f, (self.c(),) + arg)
  File "/home/sven/emesene/emesene/gui/base/ConversationManager.py", line 47, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/home/sven/emesene/emesene/gui/base/Conversation.py", line 224, in on_receive_message
    received_custom_emoticons, user_emcache.path, self.first)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 301, in receive_message
    self.append(first + middle + last, cedict, self.config.b_allow_auto_scroll)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 275, in append
    TextBox.append(self, text, scroll)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 52, in append
    self._buffer.put_formatted(text)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 31, in put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 71, in _put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 71, in _put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 66, in _put_formatted
    self.put_image(child.src, child.alt)
  File "/home/sven/emesene/emesene/gui/gtkui/RichBuffer.py", line 54, in put_image
    pixbuf = gtk.gdk.PixbufAnimation(path)
GError: Openen van bestand ‘None’ mislukt: Bestand of map bestaat niet
[18:46:41 ERROR papyon.msnp2p.session_manager] Session_id == 0

Where:  Openen van bestand ‘None’ mislukt: Bestand of map bestaat niet == File named 'None' failed: File or folder doesn't exist.

(I tried to run it trough LANG="en_GB.UTF-8", but that didn't work.)

the emoticon is now created under ~/.config/emesene2/email/emoticons

Now on the second try (or third try for the emoticon in the first message), it actually works.

Short summary:

On the first message, custom emoticons don't work at all.
After that first message, you get the failure above for any new emoticon. The file is now created in ~/.config/emesene2/email/emoticons.
On the second try for an emoticon (after the first message) it actually works, and always works thereafter, because the file is now in ~/.config/emesene2/email/emoticons.

**Comment by c10ud** [comment] 2010-10-29 17:00
ah, the good ol' adiumtextoutput where stuff automagically falls back to something working.. i guess checking for the file to exist first and put some alt text otherwise could be a good idea, otherwise a complex loading-emoticon widget could be required, honestly i don't remember how's this handled in emesene-1..

**Comment by Sbte** [comment] 2010-10-29 17:05
Oh, yeah, forgot to add that this is in both normal text and adium

**Comment by c10ud** [comment] 2010-10-29 17:18
well, at least adium shouldn't except :p the problem is that there's no mechanism yet for updating the view when the emoticon has been received -- adium handles that (quite) well without breaking up, but the richbuffer.. well it does not it seems

**Comment by Sbte** [comment] 2010-10-29 17:21
Adium does exactly the same thing:

Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 63, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 110, in **call**
    apply(self.f, (self.c(),) + arg)
  File "/home/sven/emesene/emesene/gui/base/ConversationManager.py", line 47, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/home/sven/emesene/emesene/gui/base/Conversation.py", line 224, in on_receive_message
    received_custom_emoticons, user_emcache.path, self.first)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 301, in receive_message
    self.append(first + middle + last, cedict, self.config.b_allow_auto_scroll)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 275, in append
    TextBox.append(self, text, scroll)
  File "/home/sven/emesene/emesene/gui/gtkui/TextBox.py", line 52, in append
    self._buffer.put_formatted(text)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 31, in put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 71, in _put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 71, in _put_formatted
    bold, italic, underline, strike)
  File "/home/sven/emesene/emesene/gui/gtkui/RichWidget.py", line 66, in _put_formatted
    self.put_image(child.src, child.alt)
  File "/home/sven/emesene/emesene/gui/gtkui/RichBuffer.py", line 54, in put_image
    pixbuf = gtk.gdk.PixbufAnimation(path)

**Comment by c10ud** [comment] 2010-10-29 17:30
that's not adium that's still the same output!

**Comment by Sbte** [comment] 2010-10-29 17:34
Actually that output was with adium enabled, and all the messages were in adium style. Also the emoticon I received on the second try was in adium style. Weird.

Anyways, after restarting emesene I got this:

[19:31:44 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 63, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 110, in __call__
    apply(self.f, (self.c(),) + arg)
  File "/home/sven/emesene/emesene/gui/base/ConversationManager.py", line 47, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/home/sven/emesene/emesene/gui/base/Conversation.py", line 224, in on_receive_message
    received_custom_emoticons, user_emcache.path, self.first)
  File "/home/sven/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 162, in receive_message
    self.view.add_message(msg, message.style, cedict, cedir)
  File "/home/sven/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 55, in add_message
    html = self.theme.format_incoming(msg, style, cedict, cedir)
  File "/home/sven/emesene/emesene/gui/base/AdiumTheme.py", line 75, in format_incoming
    return self.replace(template, msg, style, cedict, cedir)
  File "/home/sven/emesene/emesene/gui/base/AdiumTheme.py", line 107, in replace
    msgtext = MarkupParser.replace_emotes(escape(msg.message), cedict, cedir)
  File "/home/sven/emesene/emesene/gui/base/MarkupParser.py", line 73, in replace_emotes
    path = os.path.join(cedir, cedict[shortcut])
  File "/usr/lib/python2.6/posixpath.py", line 65, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
[19:31:44 ERROR papyon.msnp2p.session_manager] Session_id == 0

So it still fails ;)

**Comment by c10ud** [comment] 2010-10-29 17:52
ok, this is a good FAIL :D

**Comment by c10ud** [comment] 2010-10-29 19:10
wait-- does it mean that cache.path is none? how can this be possible? :s

**Comment by c10ud** [comment] 2010-11-02 18:01
i've reproduced the issue, it happens when first receiving a new custom emoticon -- once you have it, it works -- i'll try to fix it asap

**Comment by Sbte** [comment] 2010-11-02 18:06
That's what I said here:

http://github.com/emesene/emesene/issues#issue/129/comment/502570

;)

**Comment by c10ud** [comment] 2010-11-02 18:36
sorry :D

**Comment by c10ud** [comment] 2010-11-04 18:23
Do not try to put the path of (still) unknown emoticons. Closed by fc5d52bf4118326071216ddc071e15613ba31bc6

**Comment by Sbte** [comment] 2010-11-04 20:10
This still isn't fixed. What you did is get rid of the error and hide the real problem. Custom emoticons still don't work when they are first sent. They only work the second time you receive them (and thereafter).

**Comment by c10ud** [comment] 2010-11-04 21:00
i can't show something that's not in cache yet, and currently there's no way to predict where it will be (afaik) so i can't put a placeholder (other solutions would be way overcomplicated)

**Comment by Sbte** [comment] 2010-11-04 21:12
Yes, but you can wait for it to be in cache and then display it (and possibly already display the text from the message in advance). I don't know how it worked in emesene1, but it worked there for sure.

**Comment by c10ud** [comment] 2010-11-04 21:16
not possible to do without pain with the current design, if you have an idea just tell me

**Closed as completed** 2010-11-05 01:23 UTC
Labels: gtk, AdiumTextBox, Plugins
