### ISSUE TITLE
Ubuntu: emesene 2.12.5 - Auto Quit unexpectedly

### ISSUE THREAD

**Issue by spyalert01** [emesene/emesene#1345] opened 2012-06-18 03:45 UTC
I recently (for the pass 2 weeks) experience Emesene AUTO-QUIT, randomly... 
I never have this problem previously.
Is there due to some setting? I can't find any auto-quit setting in the preferences.

**Comment by KinG-InFeT** [comment] 2012-06-18 07:31
please post emesene -vvv output so developers can try to solve the problem

**Comment by moneycat** [comment] 2012-06-18 07:50
@spyalert01 Please define what is the term "AUTO-QUIT" mean, thanks.

**Comment by spyalert01** [comment] 2012-06-18 09:11
@moneycat AUTO-QUIT - that mean, I still have my Emesene LOGGED IN. But I leave the Emesene for no action for sometime, then Emesene just quit. (not in memory anymore).

**Comment by spyalert01** [comment] 2012-06-18 09:12
@KinG-InFeT How to emesene -vvv output?

**Comment by moneycat** [comment] 2012-06-18 09:13
@spyalert01 You mean 'crash'?

**Comment by c10ud** [comment] 2012-06-18 09:15
i think this is #1340

**Comment by moneycat** [comment] 2012-06-18 09:16
@c10ud I think so.

**Comment by spyalert01** [comment] 2012-06-18 10:43
@c10ud I don't see any crash message. It just AUTO-QUIT.
I am using 

Distributor ID: Ubuntu
Description:    Ubuntu 11.10
Release:    11.10
Codename:   oneiric

**Comment by c10ud** [comment] 2012-06-18 11:32
unless you run it from terminal you won't see any message

**Comment by Sbte** [comment] 2012-06-18 11:33
@spyalert01 run emesene -vvv from a terminal and tell us what you see. It's probably similar to what's posted in #1340

**Comment by spyalert01** [comment] 2012-06-19 02:07
@Sbte ok... will give it a try

**Comment by Sacolevas** [comment] 2012-06-19 03:44
I am experiencing this problem too!!!! I have to revert to the previous version because of that!! I connect to emesene (I have activated the tray icon), I do my work and suddenly (I am concentrated in my work so I don't know why is happening) I realize that the program is already closed; I am not sure what happens, but the program simply closes. 

It should be a crash and not a disconnection (in case of a disconnection, the status icon should still appear, but this is not the case) and yes .... it happens quite frequently. 

If some other users have experienced this problem, it could be good to see more comments, so we know that it is not an isolated fact, but rather a stability problem. 

Thanks for your attention; as soon as I have time (and it coincidentally the program closes by itself in a moment I run from terminal) I could put some message.

**Comment by spyalert01** [comment] 2012-06-19 06:40
@c10ud Ok. It's similar to 1340. And @Sacolevas explained the situation well. 
So what should I do now? Downgrade Emesene?
I am on Ubuntu 11.10 - Emesene 2.12.5

**Comment by Sbte** [comment] 2012-06-19 06:57
More comments saying "It doesn't work me me either" don't help. If you have any information about where the segmentation fault comes from, then that's the only useful comment.

Duplicate of #1340

**Closed as completed by Sbte** 2012-06-19 06:57 UTC
