### ISSUE TITLE
View contact profile in browser 

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#1003] opened 2012-02-02 05:06 UTC
Hello,

In most messenger programs, including emesene1, you could put your mouse in a contact location, right click and open the browser to see the profile.

Currently, emesene2 has a very interesting feature to "view information" in each contact (BTW, I mentioned before the issue of being able to copy information to clipboard, such as email, for example). However, you cannot see all the relevant information you are interested about a contact unless you open a browser and see contact's profile.

Is there a way to implement this feature in emesene2? (I think it shouldn't be difficult, given that you have implemented the feature of  checking email with just one click). 

Thanks for your attention.

**Comment by Sbte** [comment] 2012-02-02 09:18
Duplicate of #814

**Closed as completed by Sbte** 2012-02-02 09:18 UTC
