### ISSUE TITLE
Avatar problem

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1067] opened 2012-03-07 23:19 UTC
Avatar contact not appear in emesene.

See:

http://imageshack.us/photo/my-images/856/screenshotfrom201203072.png/

**Comment by c10ud** [comment] 2012-03-08 13:46
the guy is probably using a client which does bad p2p, while the
webclient uses the profile picture

2012/3/8 zipatei
reply@reply.github.com:

**Comment by pepeleproso** [comment] 2012-04-02 20:35
Closed as per Cloud comment not a bug

**Closed as completed by pepeleproso** 2012-04-02 20:35 UTC
