### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#232] opened 2010-11-26 17:49 UTC
Found this when I returned to my PC this morning:

<pre><code>

(emesene:2977): LIBDBUSMENU-GLIB-CRITICAL **: dbusmenu_menuitem_property_set_value: assertion `DBUSMENU_IS_MENUITEM(mi)' failed

(emesene:2977): LIBDBUSMENU-GLIB-CRITICAL **: dbusmenu_menuitem_property_set_value: assertion `DBUSMENU_IS_MENUITEM(mi)' failed

(emesene:2977): LIBDBUSMENU-GLIB-CRITICAL **: dbusmenu_menuitem_property_set_value: assertion `DBUSMENU_IS_MENUITEM(mi)' failed
Segmentation fault

</code></pre>

**Comment by marianoguerra** [comment] 2010-11-26 21:37
operating system? distro? version of python?

try updating your packages to the latest version (sudo apt-get update && sudo apt-get upgrade on debian based systems)

**Comment by Ancanus** [comment] 2010-11-26 22:17
<pre><code>

~$ apt-cache policy python
python:
  Installed: 2.6.6-2ubuntu1
  Candidate: 2.6.6-2ubuntu1
  Version table:
 *** 2.6.6-2ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ maverick/main i386 Packages
        100 /var/lib/dpkg/status
</code></pre>


Packages are updated to latest version.

**Comment by c10ud** [comment] 2010-11-26 23:18
this seems like some appindicator/messaging menu fuckup, not 100% sure though. i can't test since i'm not on mav and don't have the necessary appind version..

**Comment by Ancanus** [comment] 2010-11-28 07:00
This is happening a bit more often that I thought. It is prone to happen within a few hours of having emesene running. Here are some more details about it:

.) Running emesene with -vvv flags will not yield any additional info when the segmentation fault occurs.
.) The amount of times the error message is displayed varies. On my last occurrence, it was repeated like 40 times before it caused a segmentation fault.

**Comment by c10ud** [comment] 2010-11-28 18:03
i think i got the error too:

tail /var/log/syslog shows:
 emesene[1984]: segfault at 50 ip 00007fd7a3a54cf9 sp 00007fff07a89140 error 4 in libwebkit-1.0.so.2.17.7[7fd7a3062000+1080000]

too bad, too bad.. and i didn't have any conversation opened.. seems like webkitgtk is kind of broken? or maybe this has something to do with flashplayer and stuff?

**Comment by c10ud** [comment] 2010-11-28 18:06
https://bugs.archlinux.org/task/18955 says it's a bug with java plugin

**Comment by c10ud** [comment] 2010-11-28 18:17
Trying to fix potential segfault in webkitgtk.

Probably some java-plugin related issue as google seems suggesting. Closed by 88c350c668ad8f3726acb0744dd9edbd7de4633b
Please tell us if it still segfaults after this &quot;fix&quot;

**Comment by Ancanus** [comment] 2010-11-29 01:36
Happened again after "fix":

<pre>
Nov 28 20:20:13 Ancanus-SAGUBU kernel: [30751.608155] emesene[13646]: segfault at 28 ip 01b20f70 sp bff430f0 error 4 in libwebkit-1.0.so.2.17.7[131b000+d7f000]
</pre>

**Comment by c10ud** [comment] 2010-11-29 12:33
other reference:
https://bugs.launchpad.net/ubuntu/+source/gnome-panel/+bug/660455

i'll try to search for the upstream bug in order to see if there's some workaround we can use

**Comment by c10ud** [comment] 2010-11-29 16:29
maybe:
https://bugs.webkit.org/show_bug.cgi?id=36016
and/or
https://bugs.webkit.org/show_bug.cgi?id=33761

can we get a stacktrace?

**Comment by Ancanus** [comment] 2010-11-30 04:39
Getting libwebkit-1.0-2-dbg ( 138M! ), is there any other -dbg package I would need for generating a coherent stacktrace?

**Comment by c10ud** [comment] 2010-11-30 09:54
not sure, sorry.. but i think we're in the same boat as that guy since he's reporting for gnome-panel (i wonder what has gnome-panel to do with webkit anyway lol)

**Comment by c10ud** [comment] 2010-11-30 14:29
quite managed to sort-of-reproduce:
open tab with contact A
open tab with contact B
switch to tab B
A sends a message
switch to A and then to B
repeat until segfault

**Comment by c10ud** [comment] 2010-11-30 14:33
another(!!!):
open emesene
A starts a conv with you
close using the X of the window decorator
A starts a conv with you again
segfault

**Comment by c10ud** [comment] 2010-11-30 14:35
cool stuff, if i close the window using the tab-X instead, it doesn't segfault (!)

**Comment by c10ud** [comment] 2010-11-30 14:53
please update&test, will reopen if issue persists

**Closed as completed by c10ud** 2010-11-30 14:53 UTC
