### ISSUE TITLE
GTK3 Bug after reconnect emesene

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1213] opened 2012-05-01 18:47 UTC
Open conversation

Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in **call**
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/gui/gtkui/MainWindow.py", line 278, in _on_contact_selected
    self.on_new_conversation_requested(contact.account)
  File "/home/andre/emesene/emesene/gui/base/MainWindowBase.py", line 48, in on_new_conversation_requested
    self.on_new_conversation(cid, [account], False)
  File "/home/andre/emesene/emesene/emesene.py", line 750, in on_new_conversation
    conv_manager.present(conversation)
  File "/home/andre/emesene/emesene/gui/gtkui/ConversationManager.py", line 251, in present
    self.get_parent().present()
AttributeError: 'NoneType' object has no attribute 'present'

**Comment by zipatei** [comment] 2012-05-01 18:49
Another bug: click quit in main menu

Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in **call**
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/emesene.py", line 786, in on_close
    self.close_session(close)
  File "/home/andre/emesene/emesene/emesene.py", line 350, in close_session
    conv_manager.hide_all()
  File "/home/andre/emesene/emesene/gui/gtkui/ConversationManager.py", line 271, in hide_all
    self.get_parent().hide()
AttributeError: 'NoneType' object has no attribute 'hide'

**Comment by pepeleproso** [comment] 2012-05-02 19:18
this error happen every time you open a conversation? because I can't reproduce here and maybe it's not gtk3 specific

**Comment by lfottaviano** [comment] 2012-05-05 15:41
I couldn't reproduce it here

**Comment by c10ud** [comment] 2012-05-22 09:51
sbte got rid of those methods so OPs issue should be fixed, however there's a huge gtk3 bug which makes emesene segfault but it's not our fault

**Closed as completed by c10ud** 2012-05-22 09:51 UTC
Labels: bug, GTK3
