### ISSUE TITLE
"Chat History" doesn't log anything

### ISSUE THREAD

**Issue by the98** [emesene/emesene#661] opened 2011-06-14 03:03 UTC
Emesene version: 2.11.4
OS: Debian Sid

I don't think Emesene is logging any chat history because whenever I go to "View Information" and then "Chat History" tab, I can't see anything. I think I'm setting the calendar right, and besides I don't see any log files in my .config directory.

Kind regards, keep up the great work!

**Comment by Sbte** [comment] 2011-06-14 06:15
I think in emesene 2.11.4 it was broken somethings? Could you try with 2.11.5? Or otherwise delete your ./config/emesene2 directory and try again? Or tell us if you have any terminal output?

The log file should be in .config/emesene2/[protocol]/[account]/log btw

**Comment by c10ud** [comment] 2011-06-14 08:51
sbte is right, i'm starting to think your issues depend on some bad permissions on user dir or somehting like that.. (avatar not saved as chat history)

please check you have rw permissions in ~/.config, don't run emesene as root and update to 2.11.5

**Comment by the98** [comment] 2011-06-14 16:07
Permissions were ok, and of course I wasn't running emesene as root.

I updated to 2.11.5. It still didn't log. I deleted my .config/emesene2 directory, saving a backup of my avatars and my old config file. Restarted emesene and there you go, it was logging. Then I restored my old config and avatars, and for the moment it is working. So it must have been a combination of things. I'd try once to sync my config with emesene1, and since it took too long I'd canceled it. I think that might "have broken" my config and that's why it wasn't logging (??)... Could be, don't know for sure.

I don't know where logs are stored. Are they stored as before in html format? I can't see them.

BTW: avatar problem has got worse. I can see even less avatars than before. I'll to debug it and post it where it belongs.

Thank you all.

**Comment by Sbte** [comment] 2011-06-14 16:45
@4ndreaSt4gi, sync problem? ^

@the98, maybe the persons having no avatar have no avatar? emesene seems to keep loading avatars from cache even if the contacts have no avatar set.

**Comment by the98** [comment] 2011-06-14 17:33
They do. I can see them with emesene1, aMSN, MSN's profile, etc. And I also asked my contacs if they had one (who doesn't have an avatar these days?)

Cheers.

**Comment by arielj** [comment] 2011-06-14 22:02
I think that the avatar problem is caused because they are using something old (i mean, something like msnp15 instead of msnp18), for example, I have one contact that uses pidgin and I can't see his avatar with either emesene2 or WLM2011 (so we have similar support), so I guess it's our contact's client's protocol implementation's fault. Can you dig on what client are those contacts using? at least some of them, maybe they use some old WLM or MSN version.

I've also had one contact that I couldn't see her avatar for a few days and one day it just appeared (I suppose she just changed her avatar or updated her client).

**Comment by the98** [comment] 2011-06-15 00:36
Ok, so maybe emesene should use msnp15 to provide full compatibility with every messenger there is out there? At least until every other msn uses the same protocol, or whatever it's called. I mean, otherwise it's like we're forcing everyone to switch to emesene (which would be great but impossible), or "suffer" the consequences (it isn't that chaotic, really, :-P).

PS: should with discuss this in here: https://github.com/emesene/emesene/issues/602 ???  In that Issue I've post that one user is using aMSN, and another one is using WLM 2009 (at least that's what aMSN tells me, there is a feature to what MSN the contact is running)

Cheers.

**Comment by arielj** [comment] 2011-06-15 01:18
I think that WLM09 uses msnp18 too, I don't think that's the problem. Maybe their profile is broken? (like emesene1 does) I have no clue, I can only confirm that happening when a contact uses pidgin, not sure other's client.

**Comment by the98** [comment] 2011-06-15 02:42
It can't be a broken profile, I think, because I've tried to running one account with emesene2, and another account with emesene1. I can see the avatar in both cases, if I remember correctly. I will test later if I have the time.

**Comment by c10ud** [comment] 2011-06-15 08:07
with Sbte we checked out a few things about avatars, some clients aren't advertising their msnobject when we login, i think it's their fault. investigating a way to force the check of msnobjs as soon as there's something available..the only question is, will it be something available? :D

**Comment by Sbte** [comment] 2011-06-15 08:21
Just do the same we do now but with a glib timeout of 10 seconds or so. That suggestion worked for me at least. Not sure if it's the right one though. I'll leave that you you c10ud ;)

gobject.timeout_add_seconds(10, self._on_contact_msnobject_changed, papycontact)

**Comment by c10ud** [comment] 2011-06-15 10:24
it's not the right solution, but it's a start

**Comment by Sbte** [comment] 2011-07-02 18:08
Let's close this as a dupe of #602

**Closed as completed by Sbte** 2011-07-02 18:08 UTC
