### ISSUE TITLE
Crashes when sending messages

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#414] opened 2011-04-15 01:11 UTC
Updated (May 10, 2011);
When trying to send a message on the windows version of emesene2 with Adium Output enabled, emesene crashes. It sometimes is able to send the message, but it still crashes.

The current workaround for me is to go to Preferences > Live Messenger > Open Live Profile, and then REMOVING the avatar. Restart emesene, and if you have previously saved your login data DELETE it. 

Tested on Windows XP and 7.

**Comment by astagi** [comment] 2011-04-15 01:19
Please report your terminale output...

**Comment by ghost** [comment] 2011-04-15 01:30
Not sure if this is what you wanted, but here anyways.
http://pastebin.com/uhpse7nf

Here is the emesene.exe.log just in case.
http://pastebin.com/TbgbJWg7

**Comment by marianoguerra** [comment] 2011-04-15 08:00
that's a packaging problem, I had those crashes when I didn;t included the font configuration from gtk on the package.

the only way to find that for me was to use process explorer and see which resources the app was trying to access before crashing (yeah, it sucks)

I don't now if we should track package bugs here?

wdyt?

**Comment by c10ud** [comment] 2011-04-15 08:26
@syst3mfailur3: on a side note, you may want to fix your profile in Preferences-Live Messenger, i see lots of 404 in there, and they are a consequence of a broken profile

@marianoguerra: i think we can leave the issues to packagers, just we write somewhere (your old "package for windows" post? windows page in github wiki?) the issue that has been found

**Comment by ghost** [comment] 2011-04-16 02:21
When running it out of the git terminal, python.exe is crashing which then brings down emesene.
python.exe is actually crashing as soon as I open a chat window.

**Comment by c10ud** [comment] 2011-04-18 10:41
added possible issue to windows wiki page https://github.com/emesene/emesene/wiki/windows

**Comment by marianoguerra** [comment] 2011-05-05 15:12
try copyin all you can from the gtk library folder to the dist folder, it will generate a huge .exe but check if that works, if that works it means you are missing an important file (it happened to me with the fonts folder)

**Comment by ghost** [comment] 2011-05-05 15:53
Everything in C:\Python26\Lib\site-packages\gtk-2.0\runtime?

**Comment by marianoguerra** [comment] 2011-05-05 16:15
On Thu, May 5, 2011 at 12:53 PM, syst3mfailur3
reply@reply.github.com
wrote:

> Everything in C:\Python26\Lib\site-packages\gtk-2.0\runtime?

remove all the locales and all the themes but one to get some speedup
and less package size (I think the problem is with some of the other
folders)

**Comment by ghost** [comment] 2011-05-05 16:28
while waiting for a response, I did copy everything in C:\Python26\Lib\site-packages\gtk-2.0\runtime, but didnt remove any of the other files since I wasn't sure. Anyways, it is still crashing when I try to send a message.

**Comment by marianoguerra** [comment] 2011-05-05 16:47
it doesn't crash if run from the source right?

**Comment by ghost** [comment] 2011-05-05 16:49
I'm pretty sure it is crashing from source, but I will double check.

**Comment by ghost** [comment] 2011-05-05 16:54
When I run from source I get "python.exe has stopped working" and it crashes.

**Comment by marianoguerra** [comment] 2011-05-05 17:34
I think you have a mess with dependencies, maybe some wrong combination of dlls is making the interreter crash.

can you run a clean vm and install the dependencies that I listed on the blog in that order and try again?

the other solution (harder) is to clean/remove all the installations and try again, but it always leave traces of previous instalations.

**Comment by ghost** [comment] 2011-05-05 18:29
Ok so I installed everything from the guide in order on XP (vm), but its still crashing when i send a message.
It does seem to be at least running on XP now which is an improvement, but right now im still just running from the source.

**Comment by ghost** [comment] 2011-05-05 19:30
The crashes seem to be caused by adium output. With the normal text output, its fine.

**Comment by arielj** [comment] 2011-05-06 11:21
The crashes with Adium output happened to me before when webkit missed dependencies (I've never used a package, just source), it must be that. It's hard to find the right dependencies though...

Can you run dependency walker agains the installer? maybe it shows more dependencies missing.

**Comment by ghost** [comment] 2011-05-06 16:50
Not sure if I'm using it right, but it says there is an "Error opening file. The system cannot find the file specified (2)." for GPSVC.DLL and IESHIMS.DLL.

Also the adium theme works fine with dummy, but crashes with msn.

**Comment by arielj** [comment] 2011-05-06 17:23
I have those missing dll's too, they are not really needed I guess, and you say it working with dummy backend, so it's a problem with something done by papylib... maybe contacts pictures? do you have two accounts to test? put both with no picture and try opening a conversation. Can you send my the installer so I can test it too?

**Comment by ghost** [comment] 2011-05-06 17:57
Seems to have worked with no avatars.
http://imageshack.us/photo/my-images/848/adiumoutput.png/

And installer and portable version (updated when I have time) are here:
http://www.fileserve.com/list/3sn6UZV

**Comment by marianoguerra** [comment] 2011-05-06 20:32
I updated the guide http://blog.emesene.org/2011/03/rough-guide-to-create-windows-packages.html

it uses the xmppy submodule and patches the boot_common.py file from py2exe to avoid the error on close.

if there is any problem with the guide let me know.

btw, I made a portable build and it doesn't crash on gtalk, (no avatars there), so I will try to debug what's causing the problem with the avatars

PS: sorry for the merge, I commited directly to emesene/emesene, no idea why it happened

**Comment by c10ud** [comment] 2011-05-06 20:53
commit to your personal branch, and i'll fix the thing

2011/5/6 marianoguerra
reply@reply.github.com:

**Comment by marianoguerra** [comment] 2011-05-06 21:03
On Fri, May 6, 2011 at 5:53 PM, c10ud
reply@reply.github.com
wrote:

> commit to your personal branch, and i'll fix the thing

my personal branch is a mess, I can't fix it with my more than basic
git knowledge, that's why I tried to push to emesene/emesene to avoid
this, but it seems that git hates me

**Comment by c10ud** [comment] 2011-05-06 21:03
ok no need, i rewrote history for good :D

2011/5/6 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by marianoguerra** [comment] 2011-05-06 21:04
On Fri, May 6, 2011 at 6:03 PM, Mariano Guerra
luismarianoguerra@gmail.com wrote:

> On Fri, May 6, 2011 at 5:53 PM, c10ud
> reply@reply.github.com
> wrote:
> 
> > commit to your personal branch, and i'll fix the thing
> 
> my personal branch is a mess, I can't fix it with my more than basic
> git knowledge, that's why I tried to push to emesene/emesene to avoid
> this, but it seems that git hates me

I would like to start again forking emesene/emesene, but I would loose
all the watchers and related data

**Comment by c10ud** [comment] 2011-05-06 21:16
no need, just:

git reset HEAD^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ (this uncommits a lot)

then

git reset --hard (cleans stuff)

and 

git clean -f (cleans other stuff)

remove things external from the repo (check with git status) and hopefully you'll get in an old commit but still in emesene master. at this point: git pull emesene master and you'll hopefully be at current HEAD

**Comment by c10ud** [comment] 2011-05-06 21:17
once you fixed locally, just git push mariano -f and rewrite your remote

**Comment by Sbte** [comment] 2011-05-06 21:37
Or you could just do 

git fetch upstream
git reset --hard upstream/master

that makes sure you have a clean clone of emesene/emesene. Here I assume upstream is your remote alias for emesene/emesene. And then push with git push -f of course.

**Comment by marianoguerra** [comment] 2011-05-06 21:53
c10ud, I think it worked, I'm going to cry ;)

**Comment by markuznw** [comment] 2011-05-10 17:56
Hello, did you have any luck on debugging avatars maybe mariano? This bug is the only real BLOCKER for windows i think... :)

**Comment by ghost** [comment] 2011-05-10 18:59
@markuznw for me, it is already fixed. What I did was the same for fixing a broken profile but completely removed the avatar.
Try that.

**Comment by ghost** [comment] 2011-05-10 19:31
Updated the issue.

**Comment by Sbte** [comment] 2011-05-10 19:49
I suspect it is because gui.theme.user or gui.theme.logo is not read correctly by set_from_file in Avatar.py. But that's just a random guess. One should probably use utils for that (see Conversation.py). But I don't have windows, so can't test it.

**Comment by arielj** [comment] 2011-05-10 20:15
Just pointing one thing, it works from source, the problem appears using the installable version.

@markuznw, you can use the text output meanwhile, I guess it's not crashing, i'll test it better later

**Comment by ghost** [comment] 2011-05-10 20:19
@arielj I've had the problem running from the source. Python.exe crashes instead.

**Comment by arielj** [comment] 2011-05-11 14:00
Weird, it works ok here from source :S, it crashed using your installable version only (didn't try the portable one).

Just to be curious, what Window version do you use? do you have one or more drives? can you check if the path of the avatars is right? line 133 on base/adiumTheme.py, add some "print image_path"

**Comment by arielj** [comment] 2011-05-11 15:11
Just tried the portable version from 2011-05-10 on a clean pc (no emesene2, gtk, python, webkit from other tests) and it didn't crash.

It's Windows XP SP3, I have no clue, it's working here.

**Comment by ghost** [comment] 2011-05-11 15:22
For it to happen you need a broken profile and no avatar, i think. I used emesene1.6.3 to break the profile and remove the avatar. Even after fixing the broken profile, it will continue to happen.

I think emesene is forcing a saved avatar from before removing it, because if you remove the account from the computer and re-add it its fine and re-downloads whatever avatar should be present.

File path was:
file://localhost/c%3A/Users/Shawn/.config/emesene2/messenger.hotmail.com/syst3mf
ailur3%40gmail.com/syst3mfailur3%40gmail.com/avatars/67f4994da2e700fcae0937cce89
5d1212e2828ce

I've been using windows 7 64bit and Windows XP 32bit.

**Comment by arielj** [comment] 2011-05-11 21:52
can you open that file with an image editor like The GIMP? just to see if the file works or is broken.

**Comment by ghost** [comment] 2011-05-11 22:07
Don't have GIMP, but in infranview it opens but gives a message about wrong file extensions. None of the saved avatars have a file extension.

**Comment by arielj** [comment] 2011-05-11 22:14
That's why you need an more powerful image editor. You can try putting a .png or .jpg extension but if ifranview doesn't show the image you can't know if the file is broken or if it's only a wrong extension.

You can download Portable GIMP from PortableApps, just search in google, you don't have to install anything, and The GIMP always comes handy.

**Comment by ghost** [comment] 2011-05-11 22:21
It did open along with show the warning. Once I changed the file extension it worked fine. I also have Paint.net and it worked once I changed the file extension too.

**Comment by arielj** [comment] 2011-05-12 12:12
Ok, just go the error:
1->Break your profile using emesene 1.6.3 (change avatar, nick and pm)
2->Log in emesene2, profile should be broken (wrong nick ad so on)
3->Go and fix your profile (Preferences > Live Messenger) with emesene2 closed (just change your picture there)
4->Log back in emesene2 and the profile should be fixed
5->Emesene crashes on messages

**Comment by arielj** [comment] 2011-05-12 12:21
here's one problem (from the debug window)

<pre>
<div class="message-outgoing"><b>arielop</b>:<br/>    [09:16:49] <span style="color: #<img src="file://localhost/C%3A/Documents%20and%20Settings/Administrador/.config/emesene2/messenger.hotmail.com/arieljprueba%40hotmail.com/arieljprueba%40hotmail.com/emoticons/27c61d603cc6b0e966cf4c4712d4d32841677eee" alt="00000" name="MDAwMDA="/>0; font-family: 'Sans'; ">ñ</span><br/></div>
</pre>

The img tag is inside the style tag, something is wrong with the template or the replace method on sending (receiving seems to work just fine)

EDIT: I forgot that github eats html tags http://pastebin.com/rbG37zUL

**Comment by arielj** [comment] 2011-05-12 12:35
Also, from the logs:
Traceback (most recent call last):
  File "e3\common\Signal.pyo", line 64, in emit
  File "e3\common\Signal.pyo", line 111, in **call**
  File "gui\base\ConversationManager.pyo", line 75, in _on_message
  File "gui\base\Conversation.pyo", line 288, in on_receive_message
  File "gui\gtkui\AdiumTextBox.pyo", line 252, in receive_message
  File "gui\gtkui\AdiumTextBox.pyo", line 104, in add_message
  File "gui\base\AdiumTheme.pyo", line 96, in format_incoming
  File "gui\base\AdiumTheme.pyo", line 151, in replace
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd5 in position 84: invalid continuation byte
Traceback (most recent call last):
  File "e3\common\Signal.pyo", line 64, in emit
  File "e3\common\Signal.pyo", line 109, in __call__
TypeError: Method called on dead object
[09:14:43 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'str' object has no attribute 'display_name'
Traceback (most recent call last):
  File "e3\common\Signal.pyo", line 64, in emit
  File "e3\common\Signal.pyo", line 111, in __call__
  File "gui\base\ConversationManager.pyo", line 75, in _on_message
  File "gui\base\Conversation.pyo", line 293, in on_receive_message
  File "gui\gtkui\AdiumTextBox.pyo", line 256, in information
  File "gui\base\Message.pyo", line 72, in from_information
AttributeError: 'str' object has no attribute 'display_name'

**Comment by c10ud** [comment] 2011-05-12 14:32
wat, crashes because of broken profile? wtf?

2011/5/12 arielj
reply@reply.github.com:

**Comment by arielj** [comment] 2011-05-12 16:07
It's really weird, I mean, it was working ok until I broke my profile, then the problem appears, only happens sending a message (sending a nudge or receiving a message works ok).

Also, it looks like the avatar is not getting updated online, the contact's account (I'm using two accounts to test this here) shows the old avatar (the one that I used to break the profile). Maybe the profile is still not really fixed?.

I'll try this when I get some time with the source so I can make a better debug of this, sadly, I don't have the time until next week.

Also, the backtrace from before is not always there, I guess they are a side effect from the real problem.

**Comment by marianoguerra** [comment] 2011-05-12 16:48
On Thu, May 12, 2011 at 5:07 PM, arielj
reply@reply.github.com
wrote:

> It's really weird, I mean, it was working ok until I broke my profile, then the problem appears, only happens sending a message (sending a nudge or receiving a message works ok).
> 
> Also, it looks like the avatar is not getting updated online, the contact's account (I'm using two accounts to test this here) shows the old avatar (the one that I used to break the profile). Maybe the profile is still not really fixed?.
> 
> I'll try this when I get some time with the source so I can make a better debug of this, sadly, I don't have the time until next week.
> 
> Also, the backtrace from before is not always there, I guess they are a side effect from the real problem.

I think we should print the content of the message formatter before
adding it on adium theme to see if we are putting some malformed
content.

a sys.stdout.flush() would be needed to avoid loosing the content if
it crashes too fast.

**Comment by arielj** [comment] 2011-05-16 11:36
Ok... I cann't reproduce this from source (so, I can't properly debug this)

I'm trying to break my profile but the problem does not happen using source, only with the installable or portable versions. I'll try to install everything for packaging when I get more time...

I've just found something that might be wrong, inside our main config forlder, we have our "avatars" folder, with our avatar history, but we also have an "our_account@hotmail.com/avatars" folder with... our avatar history as a contact (I don't have myself as a contact).

When we send a message, the avatar is choosen from that directory instead of the avatars folder, maybe there's a problem?

**Comment by arielj** [comment] 2011-05-16 12:27
oooooooooook, just found the problem!

not sure how to fix this though...

mariano, in your guide, you do this: cp ../dlls/\* .

If I don't do that, it works perfectly!

I do have some of those dll's inside C:\Python26\Lib\site-packages\gtk-2.0\runtime\bin so I don't need to copy them inside emesene's folder to run it. Maybe it's some broken or damaged or wrong dll?

**Comment by arielj** [comment] 2011-05-16 13:42
Can you try this? http://www.mediafire.com/?bizvmartggtajpa

**Comment by markuznw** [comment] 2011-05-16 15:48
It seems to work ariel, i can see the adium blobs with it with no apparent crash. Will test more deep when i will be at home ;D

**Comment by marianoguerra** [comment] 2011-05-17 13:42
On Mon, May 16, 2011 at 4:48 PM, markuznw
reply@reply.github.com
wrote:

> It seems to work ariel, i can see the adium blobs with it with no apparent crash. Will test more deep when i will be at home ;D

maybe the visual studio c++ redistributable dlls I put there are in
somw way incompatible?

we have to check if in a clean windows xp installation we don't get
"dll missing" or something like that

nice work!

**Comment by markuznw** [comment] 2011-05-17 13:49
Seems to work even on my windows xp computer that previously had the same issues. Only problem there is UI seems a lot less responsive than on Windows 7 and frequently locks making windows print "do you want to terminate the program? It's not responding" while just chatting with people

**Comment by arielj** [comment] 2011-05-17 14:00
@mariano, I'll check my dll's against emesene ones to see if there's something different, can anyone check on a new xp installation on a virtual machine? My pc can't handle a virtual machine :P

@markuznw, I have no idea about that, it works fine here on XP, no gui locks or anything

**Comment by mariano** [comment] 2011-05-17 14:01
@arielj: please tag using the fullname. I got an email on a ticket I don't have anything to do because of this wrong tag :)

**Comment by arielj** [comment] 2011-05-17 14:09
Sorry, didn't knew there was another mariano :P

**Comment by marianoguerra** [comment] 2011-05-17 14:11
On Tue, May 17, 2011 at 3:09 PM, arielj
reply@reply.github.com
wrote:

> Sorry, didn't knew there was another mariano :P

didn't knew that mentions worked :D

**Comment by mariano** [comment] 2011-05-17 14:12
And now, obviously, I was added as a watcher of this ticket and can't seem to get out of it :)

**Comment by arielj** [comment] 2011-05-17 14:26
At the bottom of the page it says (bellow the comment buttons):

Notifications for new comments on this Issue are on. Disable notifications for this Issue

Sorry about that :P!

**Comment by mariano** [comment] 2011-05-17 14:28
Oh duh. Thanks :)

**Comment by Sbte** [comment] 2011-05-24 19:21
@syst3mfailur3, did you maybe find any problems with arielj's fix? If not, can this issue be closed?

**Comment by ghost** [comment] 2011-05-24 19:57
Been busy the last while and haven't really had a chance until today to try anything out. 
I'll let you know later today.

**Comment by ghost** [comment] 2011-05-25 02:09
@arielj Just tried the package you made (https://github.com/emesene/emesene/issues/552#issuecomment-1193996), it didn't seem to work for me. Conversation output is gone from the extension part of preferences, and it seems text output is used. 

Also when trying to recreate your fix on my end, no files made it into "dist" except "etc" "lib" and "share" from C:\Python26\Lib\site-packages\gtk-2.0\runtime. I instead tried not doing the command "cp *.dll ../dist/". The result was the same as using your package

**Comment by arielj** [comment] 2011-05-26 20:21
I'm sending my package to some friends to test it a little more, just tried yesterday on another pc and it worked right :S, I'm not really sure where's the problem.

**Comment by c10ud** [comment] 2011-05-30 13:40
are the new incoming packages affected by this issue?

**Comment by arielj** [comment] 2011-05-30 14:10
I can't find testers! I'll made a new package with most recent changes, it works on my two pc's with Windows XP, I don't have another Windows version to test them :/

**Comment by c10ud** [comment] 2011-05-30 14:14
@syst3mfailur3 can you check this out with @arielj ?

**Comment by Sbte** [comment] 2011-05-30 14:18
Or else just release it. Them we'll find them complaining soon enough.

Does Adium work for you with your package btw arielj?

**Comment by arielj** [comment] 2011-05-30 14:20
Yes, it works here, I'm doing the new package right now.

**Comment by Sbte** [comment] 2011-05-30 14:24
@arielj, I'll test it in my vm as soon as soon as your package is ready

**Comment by markuznw** [comment] 2011-05-30 15:05
Up to test it, got like 4 computers but just one with xp (and your old package worked ;))

**Comment by arielj** [comment] 2011-05-30 16:40
WT...? now it's not working on one of the pc's here, I don't know why, it's not showing any error importing webkit, but it's not imported :S

**Comment by ghost** [comment] 2011-05-30 17:08
Its only seems to happen when logged into msn. Gtalk and dummy are both file. I still think its avatar/profile related.

**Comment by arielj** [comment] 2011-05-31 11:34
Ok, I think I've found the problem! Py2exe is not packaging these dll's:
libxml2.dll
libxml2-2.dll
libiconv-2.dll
iconv.dll
z.dll

How can I tell NSIS to include those files too? I've put them inside /dist, I guess that works, but I have to wait until the package finish :P

Can you try this installer? http://www.mediafire.com/?x972xzs0x62u467
If adium themes doesn't get loaded (run emesene_debug.exe from the command line and you should see the error and emesene will crash), copy those 5 dll's from emesene/dlls folder (source) to program files/emesene2 and start emesene again, it should work! with adium themes too!!!

I've also found that most of the dll's from emesene/dlls are different than mines, maybe that caused emesene to crash when I do:
cp ../dlls/\* .

@syst3mfailur3, can you try to package emesene yourself but replacing the dll's from emesene/dlls with the ones on this package? if it works for you too we can change them on the main repo so everyone has them!

I'm uploading a version including those missing dll's too, I'll update here with the new package later, if it works we can use it as the installer for emesene 2.11.5 and finally close this issue ;)

EDIT: installer including missing dlls http://www.mediafire.com/?qmndb9mk21m4bgi

**Comment by ghost** [comment] 2011-05-31 15:34
@arielj It works! The installer at the bottom at least, the first one you posted didn't run at all including the debug.

What was your exact process in getting this dlls included? Did you do it do something different in the git bash? Or did you just drag and drop?

I don't have time now to do anything now, but maybe later.

**Comment by arielj** [comment] 2011-05-31 16:16
@syst3mfailur3, the first link on my other post will crash because I made it to crash to see the error, you have to run it from a windows cmd so the output of emesene_debug.exe can be seen, and, if you copy and paste those 5 dlls listed above inside program files/emesene2, it should not crash anymore.

To get those dlls included I just put them inside /dist (copy paste using windows explorer), but only those dlls, the others were already there (I have them inside my gtk installation and they are different). I'll upload my dll versions on a different dll folder so you can test with those dlls (instead of ignoring the cp ../dlls/\* . command at build, do something like cp ../dlls2/\* ., if dlls2 works, we can remove the ones from dlls and use mines).

Here are the finished exes:
Installer: http://www.mediafire.com/?qmndb9mk21m4bgi
Portable: http://www.mediafire.com/?1d5ay9kyxkkoxj7

test them, so we can finally close this issue for good ;D

**Comment by ghost** [comment] 2011-05-31 16:46
Don't have time to create my own package and test that right now, but I didn't run from terminal and it worked. It did freeze for a sec before showing, which scared me, but then it displayed fine. No crash. After the first message, no more little freezes. Using your installer, didn't notice any little freezes.

Second time I tested from terminal, stall was even shorter. I think its just because I'm running from terminal, and I don't think that the fact its being run from a vm with only 512mb memory helped.

I say lets go with your dlls, they are working better then the others.

**Comment by marianoguerra** [comment] 2011-06-01 09:03
On Tue, May 31, 2011 at 5:16 PM, arielj
reply@reply.github.com
wrote:

> @syst3mfailur3, the first link on my other post will crash because I made it to crash to see the error, you have to run it from a windows cmd so the output of emesene_debug.exe can be seen, and, if you copy and paste those 5 dlls listed above inside program files/emesene2, it should not crash anymore.
> 
> To get those dlls included I just put them inside /dist (copy paste using windows explorer), but only those dlls, the others were already there (I have them inside my gtk installation and they are different). I'll upload my dll versions on a different dll folder so you can test with those dlls (instead of ignoring the cp ../dlls/\* . command at build, do something like cp ../dlls2/\* ., if dlls2 works, we can remove the ones from dlls and use mines).
> 
> Here are the finished exes:
> Installer: http://www.mediafire.com/?qmndb9mk21m4bgi
> Portable: http://www.mediafire.com/?1d5ay9kyxkkoxj7
> 
> test them, so we can finally close this issue for good ;D

if you find that some dlls can be taken from the gtk installation (or
other package that we installed in the process of packaging emesene)
then we should remove the dlls from the dll folder and update the
instructiomns.

the ideal state would be not to have dlls on the repo so if we can get
them from the installations then better!

**Comment by arielj** [comment] 2011-06-01 12:45
I think that most dlls came from google :P, I've put them on gtk's folders just to make webkit work before knowing that emesene had a dlls folder

**Comment by marianoguerra** [comment] 2011-06-01 12:56
On Wed, Jun 1, 2011 at 1:45 PM, arielj
reply@reply.github.com
wrote:

> I think that most dlls came from google :P, I've put them on gtk's folders just to make webkit work before knowing that emesene had a dlls folder

we should be careful with the procedence of the dlls, some may be
infected, we don't want to be on the news because of that :)

**Comment by c10ud** [comment] 2011-06-03 09:30
to windows installers builders: please clean up the dll/ dll2/ folders :D

**Comment by c10ud** [comment] 2011-06-03 09:31
i mean, leave only what's needed and kill the rest

**Comment by arielj** [comment] 2011-06-03 12:55
If someone can confirm that the ones on dlls2 work and the installer doesn't crash sending messages with adium, we can remove dlls folder and close this issue.

**Comment by Sbte** [comment] 2011-06-03 13:01
syst3m said on irc they worked:

<sbte> hey syst3m, did you try arieljs dlls yet?
<syst3m> sbte, yea
<syst3m> they seem to work

arielj, can you remove the other dlls that are not needed too?

**Comment by arielj** [comment] 2011-06-03 13:27
ok, i'll remove them

**Closed as completed by arielj** 2011-06-03 13:27 UTC
Labels: AdiumTextBox, sʍopuıʍ

**Comment by markuznw** [comment] 2011-06-04 13:48
Doesn't work on my work xp machine with latest installer. As soon as i open one contact window and try type something it locks (and only with adium output). The first one u made was working fine :(
