### ISSUE TITLE
gtkui.Renderers: "parser went crazy"

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#1395] opened 2012-07-01 19:14 UTC
I'm trying to open a conversation with a friend, but it doesn't open ... 

In Debug, the message is:

```(16:07:55) gtkui.Renderers:this nick: '[/c][c=48][c=12][b]CS Extreme  qualidade 100% peça seu teste agora mesmo![/b][/c=50]
[$small][C=c10ud][/C][$/small]' made the parser go crazy, striping. Error: list index out of range

```
Ok, his name has a lot of bbcodes and totally out of order, but I should be able to open the conversation anyway ...
(In this case, I think there's no problem in just removing all bbcodes and open without them they're kind of useless, better than try parsing things like that ...)
```

**Comment by moneycat** [comment] 2012-07-01 19:55
@Stiveknx Which emesene version you are using, the latest dev or stable 2.12.5 or others?

The message you attached is just an notice and it should not be the reason the window could not open. If you are not using the latest dev version, you can try it, check if the issue there and wait for it to be a stable version for release.

In my environment, if I set my personal message as the crazy one you provided, other people with latest dev version will see `[/c][c=12]CS Extreme qualidade 100% peça seu teste agora mesmo!` in conversation window and beautiful `CS Extreme qualidade 100% peça seu teste agora mesmo!` in contact list.

**Comment by moneycat** [comment] 2012-07-01 19:58
PS. Nick also works fine for me. There must be another log contains `Error` or traceback message and it is the issue.

**Comment by Stiveknx** [comment] 2012-07-01 19:58
Before opening emesene I always update to the latest git version ...
So, I had the last version till 16:07 (GMT -3) ...

The user it's the one that started the conversation, I had another conversation open, the notification came up, but his tab conversation didn't show  up...
I'll wait till he opens the conversation again to check if there's another error.

**Comment by moneycat** [comment] 2012-07-01 22:21
@Stiveknx Please pull the latest git version as I just commit. The commit sha1 should be 71c08d8cde0c66871528467118d9e7e4d127a87a. In my PC, all things works find even without this two patches.

**Comment by c10ud** [comment] 2012-07-02 07:07
moneycat, btw, if it has invalid tags it doesn't need "fixing", just not excepting (didn't check your commits but.. ;))

**Comment by moneycat** [comment] 2012-07-02 08:38
@c10ud I know. The two patches just make up some lost logic in my previous patch. :P

**Comment by c10ud** [comment] 2012-07-08 10:27
@moneycat fixed?

**Comment by moneycat** [comment] 2012-07-08 13:59
@c10ud I cannot reproduce this. According to OP: "The user it's the one that started the conversation, I had another conversation open, the notification came up, but his tab conversation didn't show up...", I only can find a similar one in v2.12.5 or before the first Plus.py commit (after v2.12.5). In that version, an user with the nick may lead the conversation window broken.

Maybe we can close this because we can't reproduce it and assume it is fixed.

**Comment by Sbte** [comment] 2012-07-08 14:11
Yes, just reopen if it's still present.

**Closed as completed by Sbte** 2012-07-08 14:11 UTC
