### ISSUE TITLE
WebMessenger on hotmail + Emesene

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1203] opened 2012-04-23 08:39 UTC
Reproduce:

1) Open/login emesene with emesene@emesene.org
2) Open/login webmessenger on hotmail with emesene@emesene.org
3) Send message for another contact in webmessenger
4) Contact send message to us

Result: emesene@emesene.org open two tabs (emesene@emesene.org + contact conversation)

**Comment by pepeleproso** [comment] 2012-05-01 22:09
I can't reproduce this, I get the messages in the same conversation printed as other contact but that's other bug

**Comment by zipatei** [comment] 2012-05-02 00:48
Now, also i cant reproduce this... maybe some day problem in MSN servers?

**Comment by c10ud** [comment] 2012-05-02 13:14
could be, sometimes they test stuff too

**Comment by Sbte** [comment] 2012-05-02 18:11
Let's just close this until someone can reproduce it

**Closed as completed by Sbte** 2012-05-02 18:11 UTC
Labels: bug, papylib
