### ISSUE TITLE
Blocked contacts appear as offline

### ISSUE THREAD

**Issue by ricardofcf** [emesene/emesene#105] opened 2010-10-25 08:07 UTC
If you block a contact, it will show as offline in your contact list (MSN). Furthermore, it's display picture also won't be displayed.

What is the expected result?
Blocked contacts should have an emblem or tag reminding you that they're blocked and you should still be able to see their current status, display picture, etc.

**Comment by c10ud** [comment] 2010-10-26 17:25
there's no emblem yet, but they're not showed as offline, they're hidden because blocked are hidden by default (you can show blocked contacts with options-show-show blocked contacts

**Comment by c10ud** [comment] 2010-11-04 12:12
i'll mark this as duplicate of #79

**Closed as completed by c10ud** 2010-11-04 12:12 UTC
Labels: gtk, HARD, core
