### ISSUE TITLE
Tray Icon blinking

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#241] opened 2010-11-29 01:24 UTC
Pulled with last commits and https://github.com/emesene/emesene/issues/closed#issue/162 is not fixed here.

When i am talking, systray icon is blinking when a message is recived and the only way that i have to stop it is with Hide/show emesene option (on tray icon).

Sorry for my english... i am spanish... :D

**Comment by edualberice** [comment] 2010-11-29 18:00
I had the same problem

**Comment by c10ud** [comment] 2010-11-30 14:53
please update&test, will reopen if issue persists

**Comment by ghost** [comment] 2010-11-30 16:55
sir c10ud: Tested and perfect!

**Comment by ghost** [comment] 2010-12-01 13:03
Partially fixed:

-When you open a conversation window... seems to work fine. (You start the conversation)

-When your contact open the conversation... bug still present.

**Comment by c10ud** [comment] 2010-12-01 14:26
this should only happen the 2nd (or later) time the contact open a conversation with you -- which unfortunately make iconify not work too .. not sure why

**Comment by ghost** [comment] 2010-12-08 19:29
Issue should be reopened

Not sure... but I think that the problem appeared with these commits: https://github.com/emesene/emesene/pull/235 (November 28, 2010)

Can you take a look?

Thanks in advance

**Comment by arielj** [comment] 2011-04-11 00:31
I can't reproduce this, can anyone else confirm this?

**Comment by c10ud** [comment] 2011-04-11 16:21
there's been a lot of changes meanwhile, maybe it's just gone (?)

**Comment by c10ud** [comment] 2011-04-12 16:55
i'll close it -- reopen if issue comes back

**Closed as completed by c10ud** 2011-04-12 16:55 UTC
Labels: bug
