### ISSUE TITLE
File bar still present after clearing sent files

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#610] opened 2011-05-31 02:05 UTC
I sent a file to a contact and after it was completed i cleared it from the bar below the input box. But now even though the file is gone, the bar remains open with no visible way to close/hide it.

emesene 2.11.5 on windows 7.

**Comment by EchoUSB** [comment] 2011-05-31 07:49
Happens to me too.

**Comment by pepeleproso** [comment] 2011-06-27 20:52
This bug is fixed in git master now, it's duplicate of #682

**Closed as completed by pepeleproso** 2011-06-27 20:52 UTC
