### ISSUE TITLE
another file transfer issue

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#703] opened 2011-07-03 09:56 UTC
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 132, in run
    self._process_action(action)
  File "/home/andre/emesene/emesene/e3/base/Worker.py", line 181, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 1363, in _handle_action_ft_cancel
    self.rfiletransfers[t].cancel()
KeyError: <e3.base.Transfer.FileTransfer object at 0xafac4ac>

**Comment by pepeleproso** [comment] 2011-07-03 19:09
This is a duplicate of #702 so i'll close it.

**Closed as completed by pepeleproso** 2011-07-03 19:09 UTC
