### ISSUE TITLE
TypeError: Method called on dead object

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1333] opened 2012-06-09 13:47 UTC
In login...

Error calling config callback <function _on_nick_renderer_changed at 0x93650d4>
[14:46:33 ERROR e3.common.Signal] Method called on dead object: on_login_succeed.on_login_succeed

Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/WeakMethod.py", line 33, in **call**
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/emesene.py", line 567, in on_login_succeed
    self.draw_main_screen()
  File "/home/andre/emesene/emesene/emesene.py", line 473, in draw_main_screen
    self.session.set_default_extensions_from_config()
  File "/home/andre/emesene/emesene/e3/base/Session.py", line 167, in set_default_extensions_from_config
    extension.set_default_by_id(cat_name, ext_id)
  File "/home/andre/emesene/emesene/extension.py", line 640, in set_default_by_id
    return extension_manager.set_default_by_id(category_name, id_)
  File "/home/andre/emesene/emesene/extension.py", line 522, in set_default_by_id
    self.notify_change(category_name, new_ext)
  File "/home/andre/emesene/emesene/NotificationObject.py", line 46, in notify_change
    raise ex
TypeError: Method called on dead object

**Comment by zipatei** [comment] 2012-06-25 02:58
[03:57:12 ERROR e3.common.Signal] Method called on dead object: _on_endpoint_added._on_endpoint_added
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/WeakMethod.py", line 31, in __call__
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object

**Comment by Sbte** [comment] 2012-06-25 08:10
@pepeleproso for the first one.

The second one is probably a signal that is not unsubscribed.

**Comment by moneycat** [comment] 2012-06-26 11:13
Oh, my fault. The second one should be fixed now.

**Comment by c10ud** [comment] 2012-06-26 19:03
@zipatei could be interesting knowing which revision you were using and what exactly happened (disconnected, server off, etc.?)

also if you can reproduce the issue so you can help identifying what's (was?) wrong

**Comment by zipatei** [comment] 2012-06-26 20:41
@c10ud Sorry, but this error happened to me two times, not more... in login.

**Comment by zipatei** [comment] 2012-06-26 21:29
[22:26:55 ERROR NotificationObject] Error calling config callback <function _on_nick_renderer_changed at 0x95de764> for nick renderer
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/NotificationObject.py", line 46, in notify_change
    callback(value)
  File "/home/andre/emesene/emesene/WeakMethod.py", line 31, in **call**
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object

[22:26:55 ERROR e3.common.Signal] Method called on dead object: on_login_succeed.on_login_succeed
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/WeakMethod.py", line 33, in **call**
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/emesene.py", line 543, in on_login_succeed
    self.draw_main_screen()
  File "/home/andre/emesene/emesene/emesene.py", line 449, in draw_main_screen
    self.session.set_default_extensions_from_config()
  File "/home/andre/emesene/emesene/e3/base/Session.py", line 167, in set_default_extensions_from_config
    extension.set_default_by_id(cat_name, ext_id)
  File "/home/andre/emesene/emesene/extension.py", line 645, in set_default_by_id
    return extension_manager.set_default_by_id(category_name, id_)
  File "/home/andre/emesene/emesene/extension.py", line 527, in set_default_by_id
    self.notify_change(category_name, new_ext)
  File "/home/andre/emesene/emesene/NotificationObject.py", line 50, in notify_change
    raise ex
TypeError: Method called on dead object

**Comment by zipatei** [comment] 2012-06-26 21:30
This happened with Facebook account... in login..

**Comment by Sbte** [comment] 2012-06-26 22:02
@pepeleproso overriding `__del__` is REALLY bad (afaik), especially in emesene, because we never properly delete anything... We should probably try to implement that in a more sane way. Maybe we should standardize this. For example by overriding the `destroy` method instead on every widget.

**Comment by pepeleproso** [comment] 2012-06-26 22:32
from my tests **del** method it's called, but it's fine for me to standardize things.

**Comment by Sbte** [comment] 2012-06-27 19:47
@pepeleproso probably, but I think that then the class attributes are not properly destroyed. Because you don't do it manually. Anyhow, I read in multiple places that because of this, it's really bad to do this in general.

**Comment by zipatei** [comment] 2012-06-28 02:58
Happened to me now, i logout, and login again with MSN account.

**Comment by c10ud** [comment] 2012-06-28 09:14
@Sbte @pepeleproso i remember reading somewhere that destroy was still keeping refs to objects, maybe we should go for the "hard" del?

however i don't have a clear picture on what's happening here, probably the same ol' leaking bug of mainwindow/reconnect/login window?

**Comment by c10ud** [comment] 2012-06-30 09:47
assuming fixed due to the recent unsubscribe signals work

**Closed as completed by c10ud** 2012-06-30 09:47 UTC
Labels: bug
