### ISSUE TITLE
Translate emesene2

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#355] opened 2011-03-24 10:16 UTC
I think emesene2 is very close to everybody can use it for main msn client, but is isn't translatable yet. When we can translate it? I'm gladly help, if somebody tell me what.

**Comment by c10ud** [comment] 2011-03-24 19:02
as discussed in the mailing list (?) we need launchpad to be able to
import our git tree from github in order to set up translations just
like emesene1.. until launchpad devs fix our git import, we're stuck

2011/3/24 rockybalboa
reply@reply.github.com:

**Comment by rockybalboa** [comment] 2011-03-27 10:59
Thanks for the quick reply. 

Are the launchpad devs work on this? Or it is a request only now?

**Comment by c10ud** [comment] 2011-03-27 14:11
i talked with Jorge Castro about the issue, we're trying to make it work..otherwise we'll have to provide the updated translation template by hand i think..

**Comment by rockybalboa** [comment] 2011-03-27 16:39
Okay, I understand it. Thanks.

**Comment by c10ud** [comment] 2011-03-27 17:40
i uploaded a pot file https://translations.launchpad.net/emesene/trunk/+imports let's see what we get

**Comment by rockybalboa** [comment] 2011-03-28 14:25
Cool, I hope somebody review it soon.

**Comment by Sbte** [comment] 2011-03-28 14:53
https://translations.launchpad.net/emesene/trunk

I guess you can start ;)

**Comment by ricsipontaz** [comment] 2011-03-29 15:24
Hungarian translation is ready. :) But there are some strings, which aren't translatable.

**Comment by c10ud** [comment] 2011-03-29 20:27
we're still in development, so we could add/remove them, but if you could keep some list of the missing strings could be great! (or even hack the code yourself, and add _() to strings :D) example: "normal string" -----> _("translatable string")

**Comment by ricsipontaz** [comment] 2011-03-30 08:06
Okay I made a commit and requested a pull. If I find other untranslatable strings I'll add "_()" to it.

**Comment by c10ud** [comment] 2011-03-30 10:02
great, now i just need to find out where to put an initial translation update in emesene tree and we're done

**Comment by c10ud** [comment] 2011-03-30 10:03
well, "done".. i'd prefer having launchpad to manage the translation template import but..

**Comment by ricsipontaz** [comment] 2011-03-31 10:26
I use the new language file (emesene/po/), but the status strings aren't translated. The second thing is where can I find the "XY is online, is offline" messages?

**Comment by c10ud** [comment] 2011-03-31 12:12
the upload i did didn't contain the latest files, so the translations
are a little outdated (one day :))

as for the other thing, you can find it in notification code. you may
want to use the simple

grep -ri "is offline" *

in the emesene root directory, this will find all occurencies with
file name and make an easier search

2011/3/31 ricsipontaz
reply@reply.github.com:

**Comment by ricsipontaz** [comment] 2011-03-31 12:37
It's okay. But I downloaded the .mo file from Launchpad and copied to /home/user/emesene/po/hu/LANG_LC (I'm not sure, this is the right path, I am not in Ubuntu now) and the status strings don't translated.

**Comment by c10ud** [comment] 2011-03-31 13:52
then my "fix" for making status translatable was wrong, i need to look into it but the LC_ALL hacks ain't working here :s

**Comment by ricsipontaz** [comment] 2011-03-31 14:58
Okay, I found 3 other untranslated strings. This is an example how there are look:

 _('string'). Is this okay? Or it needs to look like this: _("string")

**Comment by c10ud** [comment] 2011-03-31 15:06
they're both okay afaik..you mean untranslated or not present in translation template?

**Comment by ricsipontaz** [comment] 2011-03-31 15:11
Not presented in template. ("is online", "is offline" and "a widget to display conversation messages")

**Comment by Richardprins** [comment] 2011-04-06 15:30
It still isn't possible to translate the statusses in some locations

**Comment by Sbte** [comment] 2011-04-06 16:10
Could you be more specific about the locations?

**Comment by c10ud** [comment] 2011-04-06 16:14
where exactly? also, i uploaded a new translation template and changed
some strings, things may change a bit

2011/4/6 Richardprins
reply@reply.github.com:

**Comment by Richardprins** [comment] 2011-04-06 16:20
In file > status and in the main screen when you click the green ball at the top. Thanks for the fast reply BTW.

**Comment by Richardprins** [comment] 2011-04-06 16:25
And while we're at it, it would be nice if we could translate "default" in preferences > theme.

**Comment by c10ud** [comment] 2011-04-06 16:30
sorry for that, git ate the modification in one of my commits. now i'm testing and hopefully with the next round of update thing should work :)

**Comment by c10ud** [comment] 2011-04-06 16:39
i think the "default" theme name is linked to the directory name, so
i'm afraid we can't translate it

2011/4/6 Richardprins
reply@reply.github.com:

**Comment by rockybalboa** [comment] 2011-04-06 17:36
So, what's up with the statuses? It is still untranslated. Is something wrong with it, or nobody hack it yet?

**Comment by Richardprins** [comment] 2011-04-06 17:40
If I understand cloud directly, he's made a patch and it is getting integrated soon.

**Comment by Richardprins** [comment] 2011-04-06 17:41
Also, it also takes time for someone to actually go and translate it

**Comment by c10ud** [comment] 2011-04-06 17:41
the problem is wider than i thought. we need to import some module to
fix paths, but the module we need calls in the module that has
statuses, so i need some time

2011/4/6 rockybalboa
reply@reply.github.com:

**Comment by c10ud** [comment] 2011-04-06 17:59
ok. the issue should now be fixed. Please note that i didn't update
translations yet...i will do it in the next days so translators can
add more strings. but now statuses are definitely translatable

2011/4/6 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by ricsipontaz** [comment] 2011-04-06 18:11
It is works now (downloaded translation from Launchpad), thanks for your efforts! :)

**Comment by c10ud** [comment] 2011-04-07 12:09
ok, i'll close this issue then

**Closed as completed by c10ud** 2011-04-07 12:09 UTC
Labels: nocoding, important
