### ISSUE TITLE
Receiving a message in an unfocused conversation provokes focus

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#530] opened 2011-05-09 23:11 UTC
If, while you're typing, someone sends you a message from another tab, your typing cursor will focus on that tab, but your're still going to see the tab you were typing on. The rest of your message will then be written in the new conversation., and pressing enter will also post it in that conversation.

Steps to reproduce:
1. Open a conversation
2.Start typing a very long message in it
3. Get someone else to talk to you while you're typing
4. See if what yu're typing is still appearing in your text field

Expected behaviour:
The focus should never switch t another convo unless the user requests it.

**Comment by Sbte** [comment] 2011-05-10 05:25
Duplicate of #493

**Closed as completed by Sbte** 2011-05-10 05:25 UTC
