### ISSUE TITLE
Me Menu in Ubuntu shows offline rather than invisible

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#474] opened 2011-04-30 14:20 UTC
I submitted the bug a while ago but it still doesn't seem like it's fixed. When emesene's status is set to appear offline, instead of having the invisible status in the Ubuntu Me Menu (the status changer in the panel in Ubuntu) it shows offline instead.

Also, as a feature request, the offline status option should be used as a short cut to disconnect/sign out from emesene, as I believe this is the purpose of this option and it is the behaviour of pidgin and empathy.

**Comment by c10ud** [comment] 2011-05-02 15:51
i'm not 100% sure on how this thing works, it could be a bug in memenu... 

@cando can you check this out?

**Comment by cando** [comment] 2011-05-02 15:58
I've done this because emesene2 has not an invisible state. (check e3/base/status.py).

**Comment by c10ud** [comment] 2011-05-02 16:02
yeah i put some conditional stuff around the code so the offline becomes invisible when user==self

so the ubuntu stuff should really call disconnect when offline is chosen i guess..

**Comment by cando** [comment] 2011-05-02 16:08
well, the ubuntu stuff "should" already call disconnect in emesene when offline is choosed...

**Comment by Mystro256** [comment] 2011-05-02 16:30
@cando well the so called invisible state should be equivalent to being appear offline no? It's only called invisible to not confuse it with offline (disconnected) mode. In other words, the option of offline is there not as an extra status but to note that one is not signed in. For other messaging clients, this also used is used as a shortcut to disconnect.

**Comment by cando** [comment] 2011-05-02 16:37
Mystro256 maybe i'm misunderstooding your answer but AFAIK
invisible---->appear offline but i'm actually online ; offline-----> i'm
really disconnected.
As i said above, clicking on Offline in the MeMenu should really disconnect
emesene. The same should happen when the user clicks on invisible: this is
due to the fact that emesene hasn't an invisible state...

2011/5/2 Mystro256 <
reply@reply.github.com>

**Comment by c10ud** [comment] 2011-05-02 16:40
if you choose offline in emesene (now correctly localized as
invisible) it will put you in "appear offline" state

2011/5/2 cando reply@reply.github.com:

**Comment by Mystro256** [comment] 2011-05-02 16:46
Well, none the less, the invisible status existed, whether or not it was called it. The issue is that when I'm invisible, it shows offline (even when I click the invisible option) and when I hit offline it doesn't log me out. This is less of a bug, more of a feature request.

**Comment by Mystro256** [comment] 2011-05-05 03:05
May I ask which file(s) does this involve? I maybe able to help if I knew.
I'm fairly new to python and most of it seems daunting or confusing to figure out.

**Comment by c10ud** [comment] 2011-05-05 08:44
it's a bug in the ubuntu memenu, i wouldn't know which files are
involved, @cando surely knows.
the memenu Invisible entry is ok as it is
the memenu Offline entry should probably tell emesene to disconnect,
now it only does what the Invisible entry does

2011/5/5 Mystro256
reply@reply.github.com:

**Comment by cando** [comment] 2011-05-05 08:46
@Mystro256 https://code.launchpad.net/indicator-me here's the MeMenu code(
it's in C/GObject). Btw i'll look into that asap.

2011/5/5 c10ud <
reply@reply.github.com>

**Comment by Mystro256** [comment] 2011-05-05 15:15
Oh okay, I'll look into it when I have time, but it's probably better I leave it to you ;P

**Comment by cando** [comment] 2011-05-05 18:33
I've looked into my MeMenu patch and it seems there are no problem(when the
user choose the OFFLINE status the MeMenu sends the right OFFLINE status
signal to emesene); the problem is in emesene imho:
file e3/papylib/PapyConvert:

STATUS_E3_TO_PAPY = { \
    status.ONLINE : papyon.Presence.ONLINE,
    status.BUSY : papyon.Presence.BUSY,
    status.IDLE : papyon.Presence.IDLE,
    status.AWAY : papyon.Presence.AWAY,
    status.OFFLINE : papyon.Presence.INVISIBLE}

in the last line the offline status is associated with the papyon's
INVISIBLE one...if you change this in papyon.Presence.OFFLINE the issue
should go away.

2011/5/5 Mystro256 <
reply@reply.github.com>

**Comment by c10ud** [comment] 2011-05-05 18:53
that's because emesene offline status is invisible. "disconnect" is
not a status in emesene, just an event (?)

2011/5/5 cando reply@reply.github.com:

**Comment by Mystro256** [comment] 2011-05-06 01:17
Well, can't you just have a condition where when offline is set, it calls the disconnect script or is it more complicated than that?

Also, when Invisible is clicked, it is immediately switched to Offline in the MeMenu rather than staying on invisible. Are you saying this is the fault of emesene as well?

**Comment by Mystro256** [comment] 2011-05-06 02:11
If I understand things correctly, the "status.OFFLINE" represents the invisible status right?

If so, it would mean there is an issue with the MeMenu code no? My knowledge of how the indicator works is a little edgy but if I understand it correctly, it seems it treats the status as either disconnected/not signed in, rather than invisible, or all of them at the same time. Maybe an extra faux status could be added to emesene that would cause a disconnect when invoked?

As well, I seem to have found another glitch; when set to any status while connected, the status on the MeMenu is kept and is still changeable after disconnected, either via connection issue or the menu, file>disconnect (ie without closing/quitting emesene)

**Comment by c10ud** [comment] 2011-05-06 10:03
for your account, yes, for other people it really means offline

2011/5/6 Mystro256
reply@reply.github.com:

**Comment by c10ud** [comment] 2011-05-06 11:53
try e3/common/DBus.py

```
    @dbus.service.method(BUS_NAME, 'i')
    def set_status(self, status):
        self.session.add_action(Action.ACTION_CHANGE_STATUS, (status,))
```

to

```
    @dbus.service.method(BUS_NAME, 'i')
    def set_status(self, status):
        print status
        self.session.add_action(Action.ACTION_CHANGE_STATUS, (status,))
```

and see if there's a difference when you choose invisible and offline from memenu...maybe we can solve this in emesene

**Comment by Mystro256** [comment] 2011-05-06 20:01
Nope, it didn't fix it. Instead, it just caused the status in the MeMenu to not update when changed in the emesene window.

**Comment by c10ud** [comment] 2011-05-06 21:00
it didn't mean to fix anything, just print in the terminal if there was a difference between the offline and invisible statuses in memenu

**Comment by Mystro256** [comment] 2011-05-06 21:13
Oh sorry, my bad, I wasn't paying full attention and missed the last line you wrote :P

It appears invisible and offline is treated as the same thing, as I thought. it outputs a 0 for online, 3 for away, 2 for busy, 1 for invisible and the same for offline.

**Comment by c10ud** [comment] 2011-05-06 21:25
too bad, then that's an issue in the ubuntu code i think

**Comment by c10ud** [comment] 2011-05-06 21:28
well, not really an issue, it's just we offer that statuses: that method should be changed like:

```
@dbus.service.method(BUS_NAME, 'i')
def set_status(self, status):
    if status == -1: do_something_that_disconnects()
    self.session.add_action(Action.ACTION_CHANGE_STATUS, (status,))
```

so ubuntu can call i.e. status -1 and we know we must disconnect

**Comment by Mystro256** [comment] 2011-05-06 21:34
Yeah, that definitely would be good to implement in emesene. Fortunately I know some C, so I could implement this in the Ubuntu code, but unfortunately I'm not too familiar/have no idea how to use LaunchPad :(

**Comment by Mystro256** [comment] 2011-05-06 21:57
Assuming I'm not too rusty in C, to fix this in the ubuntu code, in status-provider-emesene.c, EM_STATUS_OFFLINE in line 52 needs to be changed to EM_STATUS_INVISIBLE, and the lines:

```
typedef enum {
EM_STATUS_ONLINE,
EM_STATUS_OFFLINE,
EM_STATUS_BUSY,
EM_STATUS_AWAY,
EM_STATUS_IDLE  
} em_status_t;
```

changed to

```
typedef enum {
EM_STATUS_OFFLINE = -1,
EM_STATUS_ONLINE = 0,
EM_STATUS_INVISIBLE = 1,
EM_STATUS_BUSY = 2,
EM_STATUS_AWAY = 3,
EM_STATUS_IDLE = 4
} em_status_t;
```

And the same corresponding change to "static const StatusProviderStatus" function below it

This should be easy to put it if there's a "-1" status, as you mentioned

**Comment by c10ud** [comment] 2011-05-07 08:21
@cando when you have some time, if you could take a look and maybe ping the memenu devs :)

edit: if you do this, i'll take care of the emesene modifications

**Comment by Sbte** [comment] 2011-05-07 18:45
@Mystro256, enums count automatically, so you'd just need the first -1 I guess.

**Comment by Mystro256** [comment] 2011-05-07 21:08
Oh okay, I wasn't sure, I put that just to be safe

**Comment by c10ud** [comment] 2011-05-23 12:51
closing as this is a memenu bug

**Closed as completed by c10ud** 2011-05-23 12:51 UTC
Labels: ubuntu
