### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by maccabbeo** [emesene/emesene#1562] opened 2012-11-27 07:53 UTC
Hi to all.
I get a Segmentation Fault as soon as I click on the "Connect" button.
Actually, just right after launching the program I get:

Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
/usr/share/emesene/emesene/gui/gtkui/**init**.py:97: GtkWarning: IA__gdk_error_trap_pop: assertion `gdk_error_traps != NULL' failed
  gtk.main()

and then the Segmentation Fault after clicking on "Connect".

What can I do?
Thanks.

Kubuntu 12.10
Emesene 2.12.5

**Comment by c10ud** [comment] 2012-11-27 09:02
Please try upgrading to emesene 2.12.9

You can use this ppa: https://launchpad.net/~emesene-team/+archive/emesene-stable

**Comment by Sbte** [comment] 2012-11-27 18:37
Sounds like a duplicate of #1537

**Closed as completed by Sbte** 2012-11-27 18:37 UTC

**Comment by maccabbeo** [comment] 2012-11-29 18:10
Is there any solution to that problem?

 emesene
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
/usr/share/emesene/emesene/gui/gtkui/**init**.py:102: GtkWarning: IA__gdk_error_trap_pop: assertion `gdk_error_traps != NULL' failed
  gtk.main()
Errore di segmentazione (core dump creato)

**Comment by Sbte** [comment] 2012-11-29 18:21
Not that we know of
