### ISSUE TITLE
Message not sending after losing connection and regaining connection quickly

### ISSUE THREAD

**Issue by shuhaowu** [emesene/emesene#693] opened 2011-06-28 22:03 UTC
I "ignored" a friend of mine for about an hour due to a problem involving the following steps:
1. Be in a conversation in emesene, do not close the window.
2. Lose connection (something like a router problem)
3. emesene doesn't log out because the OS still thinks there's a connection
4. You regain the connection quickly.
5. Send a message over emesene from the original window. It doesn't actually get sent out, and no error is returned.
6. Emesene doesn't get logged out.

To fix the issue, you have to log out and log back in.

It's kind of vague, and a bit difficult to reproduce, but as I recall, in those situations, Pidgin will give you a message not sent error due to a switchboard error.

**Comment by c10ud** [comment] 2011-06-29 13:01
i think the problem lies in the fact that papyon doesn't tell us that there's been an error, it could be worth reporting this upstream..we currently handle disconnection at os level with networkmanager, but ofcourse that's not enough if the router loses connection

**Comment by Sbte** [comment] 2011-06-29 13:46
it should return 4 1 right? Do we catch that yet?

**Comment by c10ud** [comment] 2011-06-29 13:56
i think we catch everything, just 4 1 is the most common (read: only one)

**Comment by Sbte** [comment] 2011-06-29 14:02
Ok, then do we handle it properly? We could return an error to the user or just create a new switchboard. If we don't do that already and is possible.

**Comment by c10ud** [comment] 2011-06-29 14:08
i don't think an error is fired, that's the main reason of implementing the nm handler

**Comment by shuhaowu** [comment] 2011-06-30 19:50
Did we even try to reproduce this error? I suggest trying that first. A good way to do it is to unplug the cable from the model to the router for just 10 - 20 seconds, then connect it back.

**Comment by Sbte** [comment] 2011-07-01 14:10
On ubuntu it uses the network manager to handle this. We know what the problem is, but I'm just not sure if it's handled properly when you're not on a distro with the network manager...

**Comment by shuhaowu** [comment] 2011-07-01 14:17
Well. I'm on ubuntu when this happened.
On 2011-07-01 10:10 AM, "Sbte" <
reply@reply.github.com>
wrote:

**Comment by Sbte** [comment] 2011-07-01 15:46
What version of emesene do you have then? If it's lower than 2.11.5, here's the ppa:

https://launchpad.net/~emesene-team/+archive/emesene-stable

**Comment by shuhaowu** [comment] 2011-07-01 15:49
I have 2.11.5 from the ppa
On 2011-07-01 11:46 AM, "Sbte" <
reply@reply.github.com>
wrote:

**Comment by ez1to3** [comment] 2011-07-08 03:10
I've had this problem several times, and what's annoying is that it's hard to tell if the message was sent or not. closing the chat box, and re-opening it does not seem to work. the only option is to re-login. I'm using the latest git version of emesene on Ubuntu 11.04 32 & 64 bit.

**Comment by shuhaowu** [comment] 2011-07-09 07:36
Yea, you need to re-login. A way to find out is use the conversation logger plugin and see if it's logged.

**Comment by Sbte** [comment] 2011-07-09 08:17
You could try to report it here:

https://bugs.freedesktop.org/enter_bug.cgi?product=papyon

Maybe if they get enough bugs reported, they'll start to realize how crappy papyon is...

**Comment by ez1to3** [comment] 2011-07-10 04:56
@ ultimatebuster sorry, just to clarify; If I check the chat log, it will say the message in the log only if it was sent? The logger is enabled in Preferences > Desktop. Not sure if that's what you're talking about. or is it a separate plugin.

**Comment by shuhaowu** [comment] 2011-07-10 06:05
Where did you get a logger other than the plugin in the emesene-supported-plugin one?

**Comment by ez1to3** [comment] 2011-07-10 06:41
Don't see any chat logger from  emesene-supported-plugin... but there is one by default in Emesene. it shows up in contact information.

**Comment by Mystro256** [comment] 2011-07-10 22:18
I think @ultimatebuster is mistaken, I believe he meant the built in one.

**Comment by shuhaowu** [comment] 2011-07-11 13:52
Yeah it's the built in one. Hm it only happened to me once, so I'm not sure..

**Comment by Mystro256** [comment] 2011-07-11 14:39
Yeah I get this sometimes due to inactivity

**Comment by shuhaowu** [comment] 2011-07-14 15:05
It's difficult to tell that you're affected by this bug as there's no errors.. The only thing is that the person you're talking to might yell at you.

**Comment by mgonto** [comment] 2011-07-20 01:44
This happends to me all the time and i don't see any connection loose. At least the rest of the programs don't loose connection but sometimes messages start to not being sent (I'm not notified) and I have to restart emesene.
I'm on the PPA with ubuntu 11.04

**Comment by danielgomon** [comment] 2011-07-22 04:09
Same issue here, 2.11.5 version on Archlinux...

**Comment by Sbte** [comment] 2011-07-22 10:07
Please report it here:

https://bugs.freedesktop.org/enter_bug.cgi?product=papyon

**Comment by shuhaowu** [comment] 2011-07-23 05:33
Can someone with more information report and post the link back here?

**Comment by c10ud** [comment] 2011-08-16 19:12
we're investigating if we can fix this and if there's some proper way to do it along with upstream devs

**Comment by c10ud** [comment] 2011-08-16 20:06
potential fix, waiting for upstream:

https://github.com/emesene/papyon/commit/0ae79fef5455f7bfa24fa4150aab354419b696e0

**Comment by c10ud** [comment] 2011-09-13 14:54
papyon is now inside emesene tree, with this feature

**Closed as completed by c10ud** 2011-09-13 14:54 UTC
Labels: papyon
