### ISSUE TITLE
Url issues in contact list

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#388] opened 2011-04-12 23:12 UTC
In the contact list if a contact has one or more urls within his/her personal message, the first one is not blue while the rest are. It is underlined like the rest of the urls, but not made blue.

I found this on Windows on a package made less then 3 hours ago, yet it is not present in a package made earlier earlier today. I think it may have had something to do with https://github.com/emesene/emesene/issues/386.

**Comment by ghost** [comment] 2011-04-13 03:49
I took another look, and its not happening to all contacts. I was testing it between 2 different versions of emesene, a package from today and 1.6.

On a separate but related note, some other contacts with the url at the end of there personal message had a [/C] added onto the end, but only in the contact list.

**Comment by Sbte** [comment] 2011-04-13 09:23
This is weird. And I also don't seem to be able to reproduce it. Are you sure your contact didn't do anything weird with the url? But they're not clickable, anyway, so I guess it doesn't really matter right? I'll see if I can fix the [/C] though.

**Comment by Sbte** [comment] 2011-04-13 11:43
I just removed the markup from urls. That should do it.

Closed by 0454069a17c8a89bc6cb015cf05194b1f827b80a

**Comment by ghost** [comment] 2011-04-13 19:03
The [/C] is still visable.
Testing on version from after your fix.
http://img845.imageshack.us/i/urlproblem.png/

**Comment by Sbte** [comment] 2011-04-13 19:07
Sorry, had to add a space because c10ud didn't believe the color bug was there, and forgot to check if this still worked if I removed the space...

**Comment by Sbte** [comment] 2011-04-13 22:44
Ok, this is actually fixed now, but the default template is still wrong. But there is so much going on in the Parser that parses this stuff that it BLOWS MY MIND. Atm, if someone uses Plus to color their names, you won't see them, because the color is overridden. The easiest fix for this is using no color at all in the default template.

Template without color:

[$DISPLAY_NAME][$NL][$small][$MESSAGE][$/small]

Template with color:

[$DISPLAY_NAME][$NL][$small][$COLOR=#696969][$MESSAGE][$/COLOR][$/small]

Now we only need to discuss what the default template should be...

**Comment by Sbte** [comment] 2011-04-14 17:00
I seem to have fixed this while writing the new contact list parser. Please try again. I probably broke something different now...

**Comment by c10ud** [comment] 2011-04-14 17:07
fixed!

**Closed as completed by c10ud** 2011-04-14 17:07 UTC
Labels: HARD, Discussion Required, bug
