### ISSUE TITLE
Action to "copy email": Could this action be introduced in emesene2 ?

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#990] opened 2012-01-27 09:53 UTC
Hello, 

The action of copying email address was a very useful feature of emesene 1.6.3 that doesn't exists in emesene2. In the newest versions, we see the more elaborate option of "View Information", but it is impossible to select and copy the email address; users can only see the address and nothing more. 

Could this very useful feature being implemented the way it existed in emesene 1.6.3? I am not a programmer, but I have the impression it should not be difficult to do it.

Thanks for your attention.

**Comment by c10ud** [comment] 2012-01-27 11:03
you can copy it from the conversation header, it shouldn't be
difficult to implement though, so if someone wants to tackle this
issue...

2012/1/27 Sacolevas
reply@reply.github.com:

**Comment by Sbte** [comment] 2012-01-27 11:17
@c10ud, you can't. That's the problem...

**Comment by Sbte** [comment] 2012-01-27 11:29
Actually, duplicate of #984

**Closed as completed by Sbte** 2012-01-27 11:29 UTC
Labels: easy, gtk
