### ISSUE TITLE
Remove plugin

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1312] opened 2012-05-29 23:04 UTC
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/ExtensionList.py", line 451, in remove
    path = self.removable_list[self.remove_item[0]][self.remove_item[1]]
KeyError: 'music'

Reproduce:
1) Remove music plugin
2) And click again in remove

**Comment by c10ud** [comment] 2012-05-30 09:59
before/after some specific commit?

@pepeleproso

**Comment by Sbte** [comment] 2012-05-30 11:16
Would be interesting to have a git bisect here. To see whether it's my or pepe's fault :P

**Comment by zipatei** [comment] 2012-05-30 13:09
@c10ud I dont know... just test this yesterday

**Comment by pepeleproso** [comment] 2012-06-02 22:26
I can't reproduce this. Maybe is fixed in master?

**Comment by zipatei** [comment] 2012-06-03 13:12
Not fixed yet...

You remove plugin, but remove button not dissappear, and click again in remove, and error.

**Comment by pepeleproso** [comment] 2012-06-03 15:58
zipatei can you try this https://github.com/pepeleproso/emesene/commit/951ad161565def75bf391932d8487cb1092dbe3f

I can reproduce it once, but then it's gone again.

**Comment by zipatei** [comment] 2012-06-03 16:18
this commit not fix this issue

**Comment by moneycat** [comment] 2012-06-06 08:59
I think the problem is due to after remove plugin, the remove_item still remain ( the selected key and value selected in previous step). I've try to reset it and try this commit please: 6a6b93fe0f0cf68cc082b22e616b5106919a3dd6.

**Comment by Sbte** [comment] 2012-06-06 09:06
That is an ugly hack, because the remove button shouldn't be clickable after you have removed something. I'll look into this tomorrow.

**Comment by moneycat** [comment] 2012-06-06 09:42
The Download button has the similar problem too. It will download twice for the same plugin.

**Comment by moneycat** [comment] 2012-06-06 10:00
@Sbte Something like this? 368aa5f7e89df1876d87c505b9d343532f8aa79d

**Comment by moneycat** [comment] 2012-06-07 10:08
0696b378dc27ab4c198501de986d0159e72f33e1

**Comment by Sbte** [comment] 2012-06-07 19:01
Go push it ;)

**Closed as completed** 2012-06-08 02:27 UTC
