### ISSUE TITLE
not enabled to add msn contact

### ISSUE THREAD

**Issue by zodman** [emesene/emesene#735] opened 2011-07-17 02:43 UTC
<pre>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/site-packages/emesene/e3/papylib/Worker.py", line 131, in run
    self._process_action(action)
  File "/usr/lib/python2.6/site-packages/emesene/e3/base/Worker.py", line 181, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/usr/lib/python2.6/site-packages/emesene/e3/papylib/Worker.py", line 851, in _handle_action_add_to_group
    papycontact = self.address_book.contacts.search_by('account', account)[0]
  File "/usr/lib/python2.6/site-packages/papyon/service/AddressBook/address_book.py", line 53, in __getitem__
    raise IndexError("Index out of range")
IndexError: Index out of range
</pre>

**Comment by Sbte** [comment] 2011-07-17 09:55
Are you trying to add the contact to a specific group too?

**Comment by zodman** [comment] 2011-07-17 16:10
yes!

**Comment by c10ud** [comment] 2011-08-09 17:37
i'll mark this a duplicate of #543

**Closed as completed by c10ud** 2011-08-09 17:37 UTC
