### ISSUE TITLE
[DEBUG emesene] e3.common.Signal:Signal handler

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1356] opened 2012-06-22 19:34 UTC
``` python
(20:07:06) e3.common.Signal:Signal handler (_on_contact_attr_changed._on_contact_attr_changed) error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```

**Comment by Sbte** [comment] 2012-06-22 22:10
Duplicate of #1347

**Closed as completed by Sbte** 2012-06-22 22:10 UTC

**Comment by KinG-InFeT** [comment] 2012-06-23 07:41
not duplicate... all depends is installed.... something lacking?

**Comment by c10ud** [comment] 2012-06-23 09:54
The name org.freedesktop.Notifications was not provided by any .service files

aka fix your python-notify install

**Comment by KinG-InFeT** [comment] 2012-06-23 12:50
i have installed the depends...... 

``` bash
depends=('python2' 'pygtk' 'python-dnspython' 'pylint' 'python-notify' 
         'openssl' 'papyon' 'python-imaging' 'dbus-python' 'xorg-xprop' 'libnotify')
```

https://aur.archlinux.org/packages/em/emesene2-git/PKGBUILD

**Comment by moneycat** [comment] 2012-06-23 15:26
@KinG-InFeT try something like `notification-daemon` as I said in #1340 and ref: http://git.gnome.org/browse/notification-daemon/commit/?id=1ad20d22098bc7718614a8a87744a2c22d5438d0

**Comment by KinG-InFeT** [comment] 2012-06-24 10:11
undestand... package for archlinux is http://www.archlinux.org/packages/extra/i686/notification-daemon/ 
but exit this error #1364
