### ISSUE TITLE
Open profile in contacts list

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#884] opened 2011-10-01 01:42 UTC
If you access
http://members.msn.com/email@email.com

You see the profile of that contact, it's possible to add an option to "view profile", when you click with right button in contact?
Or maybe a link in contact information....

I think emesene 1 used to have that feature.
Thanks.

**Comment by arielj** [comment] 2011-10-01 01:57
Duplicate of https://github.com/emesene/emesene/issues/814

**Closed as completed by arielj** 2011-10-01 01:57 UTC
