### ISSUE TITLE
Notification within Tabs

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#216] opened 2010-11-24 02:56 UTC
Currently when a message arrives, I am notified by the green envelope in the indicator-applet and the Bold font in the dock-bar (notification pop-ups are turned off). However, when I open the Conversation window, there is no indication of which tab has the new message.

This can be problematic to some users if they have a large amount of tabs open, making them scan each of the tabs to find the new message. In order to avoid this, I propose adding a notification to the tab title that contains the new message. This notification could be bolding the font, changing the background color, etc. It would also be wise to accommodate the possibility that there may be more than one tab that contains a new message.

**Comment by c10ud** [comment] 2010-11-24 09:06
the tab emblems turns to red with a !

**Comment by c10ud** [comment] 2010-11-24 09:58
closing the issue

**Comment by Ancanus** [comment] 2010-11-24 19:29
I just noticed. However, it only seems to change to the red ! icon if I do not have the conversation window open.

Bug reproduction:
1) Open two tabs with friends.
2) Ask a friend to send you a message, then switch to the the other tab.
3) When you receive the message, the red ! icon will not appear, but the green envelope will light up, and the window title in the dockbar will be bolded.

EDIT: On the same note, would you say that the red ! is a bit too similar to the busy icon?

**Comment by edualberice** [comment] 2010-11-24 23:27
To be sincere, I just noticed that the icon becomes a red ! because you told here. It's almost the same of the busy icon. A good thing to do is to change this icon for something that calls the attention.

**Comment by c10ud** [comment] 2010-11-25 13:37
i can't reproduce the issue, apart from the nasty color, i get the attention emblem correctly

**Comment by c10ud** [comment] 2010-11-26 13:50
pushed some change to fix this stuff, please test

**Closed as completed by c10ud** 2010-11-26 13:50 UTC
Labels: gtk, core, bug
