### ISSUE TITLE
please add feature to start emesene minimized/sitting in the system tray

### ISSUE THREAD

**Issue by crenedecotret** [emesene/emesene#752] opened 2011-07-31 17:21 UTC
(edited this post at Mystro256's request to clear things up)

The emesene main window always starts maximized. It would be nice if the preferences screen could be modified to add an option to change this, in the same way that conversation can be started minimized. The idea would be to allow emesene to load at login, go directly to the tray, automatically connect to MSN, and sit there quietly until I want to start a conversation or receive a notification event.

The way it is setup now, the main window appears when the app is launched, and I must wait for connection to MSN before I can close it. Once connected, closing the window works as expected/wanted.

I'm using arch linux, with openbox as a window manager. I am using tint2 as a taskbar/tray.

**Comment by Mystro256** [comment] 2011-07-31 18:02
The option is under <b>conversation window</b> not main window. The main window doesn't have this option, if you want to request it, please post a request not a bug report.

Also I assumed you mean <i>"but the emesene main window <b>never</b> starts minimized"</I> or am I misinterpreting what you mean?

**Comment by Sbte** [comment] 2011-07-31 18:12
Closing while not connected yet is a feature to allow people to close emesene when it's not yet connected.

The other thing is what Mystro said. So this is actually a feature request to have an option to start emesene minimized.

**Comment by crenedecotret** [comment] 2011-07-31 19:07
I'm sorry.. I just re-read my bug report... I must have still be sleeping. What I meant to say is that emesene always starts MAZIMIZED even if in the preferences page, I select "Start minimized/iconified."... as Mystro interpreted what I was saying

If emesene only minimizes after connecting to MSN, that's OK too.. it only takes a moment. I guess the important is that the "start minimized/iconified" allows me to work on my computer without emesene being in the way of my desktop without out me manually having to close the window to send it to the tray, which I suppose is why the option exists.

thanks for the lightning fast replies

**Comment by Sbte** [comment] 2011-07-31 19:11
Yes, but that option only works for conversations, not the main window. So this is basically a feature request for a similar option for the main window.

**Comment by crenedecotret** [comment] 2011-07-31 19:29
yup.. just looked at the preferences screen again, and you're right... it's quite clear now. Sorry, I just switched over from aMsn this morning because of theming issues with some apps since GTK3 came out... So yes, this shouldn't be a bug request, it's a feature request to add similar option to the main window.

**Comment by Mystro256** [comment] 2011-08-01 03:34
Can you just edit your first post (and title of issue) to avoid any more confusion?

Please and Thanks :)

**Comment by crenedecotret** [comment] 2011-08-01 04:23
done. thanks again, i'm very impressed at how quick the response was
when I filed the issue!

On Sun, 31 Jul 2011 20:34:10 -0700
Mystro256
reply@reply.github.com
wrote:

> Can you just edit your first post (and title of issue) to avoid any
> more confusion?
> 
> Please and Thanks :)

**Comment by Sbte** [comment] 2011-08-09 09:30
This would need a reimplementation of when the tray icon is drawn, because now it's done upon drawing the main screen.

**Comment by c10ud** [comment] 2011-08-09 09:36
no need for that, just add some option to command line's optparser and/or preference window and call hide()|iconify() in the right places

**Comment by Sbte** [comment] 2011-08-09 10:04
Yeah, but what to do with NoTrayIcon. It will be instantiated, and then there's NOWAY to close/unhide emesene anymore. Unless of course we disable that.

And this should be saved in the global settings right? Not the local ones.

**Comment by c10ud** [comment] 2011-08-09 10:15
global settings, yes.. as for NoTrayIcon: we assume you know what you're doing

**Comment by Mystro256** [comment] 2011-08-09 15:02
How bout just minimizing it, not hiding it?

**Comment by Sbte** [comment] 2011-08-09 15:20
I think most people, unlike me, don't like having it minimized, but rather hidden to tray.

**Comment by Mystro256** [comment] 2011-08-09 15:24
I meant if the no tray icon option is invoked :P

**Comment by Sbte** [comment] 2011-08-09 15:34
Mystro, problem is we don't know what tray icon will be used in the session itself, because we have to hide the window before we know that.

**Comment by Mystro256** [comment] 2011-08-09 15:37
Oh, thought it was a global setting, how does emesene decide what tray type to use before login then?

**Comment by Sbte** [comment] 2011-08-09 15:40
The default one. It would be better to implement the tray icon also as a global setting, but currently, no extensions are saved to the global config. When I implemented this I thought it might be a lot of work to implement it like that, so I went for the easy way. If it's implemented for one extension however, it should also be easy to do it for others.

**Comment by Mystro256** [comment] 2011-08-09 15:52
Ah ic, I guess that makes sense. It would probably make sense to have a global setting, as it's per user settings (desktop user not session user), although that's if someone wants to go to the trouble to implement it ;P

**Closed as completed** 2011-08-10 12:12 UTC
Labels: gtk, core, feature
