### ISSUE TITLE
Label too long in the new systray

### ISSUE THREAD

**Issue by lylambda** [emesene/emesene#1486] opened 2012-08-27 21:31 UTC
An icon appear in the new systray (notification area) when "indicator" is selected with "tray icon" . Perfect ! :)
But it's seems the label (comment) is very long and with some weird number.

On Cairo-Dock, that don't look like very good : http://uppix.net/4/b/b/aa16fa7d80213a75b3e9209e66fea.png
Here, an example of a correct label : http://uppix.net/4/a/0/1ad5455b850cfbef99c82cd1e6ca7.png

Can you fix that ? Thanks :-)

**Comment by moneycat** [comment] 2012-08-28 03:15
Should we sync the tooltip like https://github.com/emesene/emesene/blob/master/emesene/gui/common/TrayIcon.py#L91

@Sbte

**Comment by c10ud** [comment] 2012-08-28 07:31
the ayatana Indicator doesn't have tooltips, see: https://github.com/emesene/emesene/blob/master/emesene/gui/common/Indicator.py

The tooltip must be made by the dock itself, we have no control over it

**Comment by c10ud** [comment] 2012-08-28 07:35
please note that the tooltip is probably the app name we give to the indicator constructor (see the uuid() call) but IIRC that's because if you open multiple emesenes the indicator would go crazy if the name was the same.
however since that code is quite old, you can try modifying and put the account instead of uuid and see what happens

**Comment by moneycat** [comment] 2012-08-28 08:01
@c10ud  You are right, the id should be unique.

**Comment by c10ud** [comment] 2012-08-28 08:05
http://developer.ubuntu.com/api/ubuntu-12.04/c/appindicator/libappindicator-app-indicator.html#AppIndicator--id

however, i think it could be safely changed to "emesene - %s" % account... in the end you don't always have two or more emesene opened with the Indicator and the same account (but when you do... jk ;))

@moneycat can you try the change?

**Comment by moneycat** [comment] 2012-08-28 08:08
I've try to but at the init. time, there is no account in self, handler, etc. If the id cannot be changed after login, I think we cannot do it.

**Comment by c10ud** [comment] 2012-08-28 08:11
Ah, right. - then the only way would be using "emesene" only..and break in case of multiple emesenes, or make the cairo dock guys fix their implementation of indicators

**Comment by Sbte** [comment] 2012-08-28 08:36
emesene -s is currently the default. You could check for single instance emesene, and in that case use "emesene" as id.

**Comment by matttbe** [comment] 2012-08-28 08:47
Hello,

It seems that with the latest version of Indicator, the title is automatically added.
So now, on Ubuntu Quantal, the dock can see the 'Title' property which is 'emesene' (and it displays 'Emesene'). It seems it uses the name of the application (e.g. if I move '/usr/bin/emesene' to '/usr/bin/emesene2' and launch emesene2, the name should be 'emesene2').

Note that if you want to have more control about this tooltip, you can use the PyGI version: => from gi.repository import AppIndicator3 as appindicator
The API is available there: http://developer.ubuntu.com/api/ubuntu-12.04/python/AppIndicator3-0.1.html

BTW, thank you for all these quick answers ;)

**Comment by c10ud** [comment] 2012-08-28 10:11
Unfortunately we don't have (yet) a gtk3 port, the main issue is that ubuntu discourages IMs from using indicators (and pushes to use the messaging menu instead) so @Sbte's suggestion maybe the best here but checking for single instance is not so easy because:     def **init**(self, handler, main_window=None)

**Comment by Sbte** [comment] 2012-08-30 14:53
``` python
        options = optionprovider.PluggableOptionParser.get_parsing()[0]
        if options.single_instance:
            app_name_hax = "emesene"
        else:
            app_name_hax = "emesene-%s" % uuid.uuid1()
```

**Comment by c10ud** [comment] 2012-08-30 14:59
it's only needed because cairo-dock haxes indicators but indicators are not supposed to have tooltips (at least, the version we're using)
more: you're not supposed to use indicator but messaging menu (ubuntu guidelines)

so i'm sorry but won't fix

**Closed as completed by c10ud** 2012-08-30 14:59 UTC

**Comment by matttbe** [comment] 2012-08-30 17:45
> it's only needed because cairo-dock haxes indicators but indicators are not supposed to have tooltips (at least, the version we're using)

Yes, it's just because you're using the old Python API. But Indicators are not only used in Unity (Cairo-Dock, Gnome-Panel, other docks, etc.) and the API is more and more similar to KDE's new systray which has a title, etc. (in fact, the base is the same but one uses dbusmenu-gtk with its daemon and the other one uses dbusmenu-qt with its daemon)

Now more and more applications use the 'title' property (e.g. with Network-Manager to display a few informations about the connexion) and I guess that it's not only for Cairo-Dock.
But I guess it's maybe better to not add a tooltip in the dock if the title is so long.

**Comment by c10ud** [comment] 2012-08-30 17:55
If you try a standard ubuntu installation you will see that there's no
tooltip in the indicators

greets

2012/8/30 Matthieu Baerts notifications@github.com

**Comment by Sbte** [comment] 2012-08-30 18:00
@matttbe didn't you just say that the title property in Quantal is derived from the name of the application? Wouldn't it be reasonable to expect the same behaviour from other docks/panels?

**Comment by matttbe** [comment] 2012-08-30 18:01
Oh sorry, I didn't know that Emesene was only designed to Ubuntu with Unity.
That's ok know, I understand why this issue is closed!

**Comment by Sbte** [comment] 2012-08-30 18:04
@matttbe it is not. But since Indicators are an Ubuntu thing, other things that make use of them should support them in the same way Ubuntu does. If they do not then it's probably a bug on their end.

**Comment by matttbe** [comment] 2012-08-30 18:07
@Sbte yes, I think it's better to not display the ID but other guys prefer to display something than nothing to not have a "gap" and also because sometime it's not easy to know which icons are linked to which applications (e.g. with Emesene, we don't have Emesene's icon ;) )

**Comment by matttbe** [comment] 2012-08-30 18:10
> @matttbe it is not. But since Indicators are an Ubuntu thing, other things that make use of them should support them in the same way Ubuntu does. If they do not then it's probably a bug on their end.

@Sbte yes but don't forget that Indicators API is very similar than KDE's new systray (and I guess this is why we now have the Title property even if this information is not displayed in Unity's panel)

**Comment by Sbte** [comment] 2012-08-30 18:20
@matttbe I'll update my vm with Quantal and see what they do there.

**Comment by Sbte** [comment] 2012-08-30 19:45
Ah, I can reproduce it in 12.04 too. It's used in the HUD:

Press Alt
Type "disconnect"
You'll see: Untitled indicator (emesene-uuid) > Disconnect

**Comment by Sbte** [comment] 2012-08-30 20:32
There you go sir ^^
