### ISSUE TITLE
NO TRAY ICON UBUNTU 11.04 CLASSIC UBUNTU

### ISSUE THREAD

**Issue by webmaker703** [emesene/emesene#504] opened 2011-05-04 22:42 UTC
i dont know is this is a bug of ubuntu or emesene but the tray icon of emesene2 its not being showed on the notification area as skype and fusion icon..

i've tryied with phyton-gtk-extras but doesnt appear.. so.. here its my report

by the way... thank you to much for emesene2 i really like emesene!!

**Comment by arielj** [comment] 2011-05-05 00:08
did you choose the trayicon's extension on preferences > extensions?

**Comment by Mirkilin** [comment] 2011-05-05 01:00
Same problem, no tray icon

**Comment by Fabio-pereira** [comment] 2011-05-05 01:58
For me emesene appears on the messaging menu (the one with the small letter icon)

**Comment by Mystro256** [comment] 2011-05-05 02:06
This is a duplicate of #340 and/or an extension of it :P

**Comment by Sbte** [comment] 2011-05-05 07:44
Ubuntu has the memenu. It's in there. Other than that, it's a duplicate of #340, because there should be an option to get the old tray icon back, but that option doesn't work.

**Closed as completed by Sbte** 2011-05-05 07:44 UTC

**Comment by c10ud** [comment] 2011-05-05 08:30
the messaging menu is still there even with classic ubuntu, i guess.

2011/5/5 webmaker703
reply@reply.github.com:

**Comment by Mystro256** [comment] 2011-05-05 15:23
Yeah the classic is based off of Maverick but with updated versions and the complete indicator applet

**Comment by pjalegria** [comment] 2011-05-07 13:04
installing indicator-applet and indicator-applications solved for me
