### ISSUE TITLE
problematic nickname(s)

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#8] opened 2010-03-12 20:14 UTC
see link

**Comment by c10ud** [comment] 2010-03-12 20:15
http://emesene.pastebin.com/rBfQZcZN

**Comment by c10ud** [comment] 2010-03-12 20:48
another one http://emesene.pastebin.com/u8xUdEEw

**Comment by cando** [comment] 2010-05-14 09:49
i get this exception...maybe it's related:
Traceback (most recent call last):
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/gtkui/Renderers.py", line 114, in on_render
    layout = self.get_layout(widget)
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/gtkui/Renderers.py", line 123, in get_layout
    'utf-8')))
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/gtkui/Renderers.py", line 177, in msnplus_to_list
    dct = Plus.msnplus(txt, do_parse_emotes)
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/base/Plus.py", line 262, in msnplus
    _dict_gradients(dictlike)
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/base/Plus.py", line 229, in _dict_gradients
    _dict_gradients(subdict)
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/base/Plus.py", line 229, in _dict_gradients
    _dict_gradients(subdict)
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/base/Plus.py", line 229, in _dict_gradients
    _dict_gradients(subdict)
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/base/Plus.py", line 228, in _dict_gradients
    _gradientify(subdict)
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/base/Plus.py", line 206, in _gradientify
    colors = _color_gradient(param_from, param_to, _nchars_dict(msgdict))
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/base/Plus.py", line 138, in _color_gradient
    stepR =((float(R2dec)-float(R1dec))/(float(length)-float(1)))
ZeroDivisionError: float division

**Comment by c10ud** [comment] 2010-05-14 16:11
...only if you provide the nickname! :p

**Comment by cando** [comment] 2010-05-14 19:10
it doesn't appears in the exception...i'm investigating...

**Comment by marianoguerra** [comment] 2010-05-18 17:16
nick or gtfo :P

maybe the length of the nick is 1?

that would make (float(length)-float(1))) == 0 and you have a nice ZeroDivisionError.

also, you only need to cast one number to float, not all of them

stepR =((R2dec-R1dec)/(length-1.0))

**Comment by cando** [comment] 2010-05-21 08:59
i've found the nickname:
[i][B][c=12]☆[/c=0][c=0]☆[/c=12][c=12]☆[/c=0](W)  [c=12]Bellamezz[/c=49](F) [c=0]☆[/c=0][c=12]☆[/c=12][c=0]☆[/c=0][/B][/i]

**Comment by cando** [comment] 2010-05-21 09:44
this nick doesn't show emoticons: 
(ip)(B)[b]CAVO[/b](B)(ip)....(L)(L)(L)

github shows the second [/b] as /b but in the nick there is [/b]

**Comment by c10ud** [comment] 2010-05-21 09:52
cando: this doesn't except http://github.com/c10ud/emesene/commit/bb0f028b96045ece222318716d25aac7754ac42e however this is a fix which doesn't know what's happening. we need boyska advice in here (and thanks mariano for the hints :P) there are a nice group of problematic nicks in dummy backend :D

**Comment by marianoguerra** [comment] 2010-05-21 10:43
every time you find a problematic nick, add it to the dummy backend so it's easy to test and fix

**Comment by EibrielInv** [comment] 2010-07-12 04:39
Other One:
http://emesene.pastebin.com/rjdqRqBx

**Comment by c10ud** [comment] 2010-07-20 13:03
i worked on this issue bringing emesene1 fuckedup parsers to emesene2 and they seem to work really nice apart a small bug:

irc-coloured-nicknames break when there's a newline (you can see this issue with the dummy backend). i don't get why it works (quite) good without the newline, maybe it's some span issue? if anyone could take a look, then we would have perfect plus parsing

note: antiplus works perfect.

**Comment by andreskru** [comment] 2010-07-20 15:14
Sun Jul 18 22:07:27 2010
[b][c=6].....:PLAURITA.!!!:) ...[/c]lttttt[/b]
[$small]laurat_14@hotmail.com[$/small]
[$small](online) - le dije a mi (L) no cometas el crimen, si no vas a cumplir la condena!!!![$/small]
<span><b><span color="#9C009C">.....</span></b></span>,<gtk.gdk.Pixbuf object at 0xafc9784 (GdkPixbuf at 0xbb33450)>,<span><b><span color="#9C009C">LAURITA.!!!</span></b></span>,<gtk.gdk.Pixbuf object at 0xafc9a04 (GdkPixbuf at 0xbaf2998)>,<span><b><span color="#9C009C"> ...</span>lttttt</b>
<small>laurat_14@hotmail.com</small>
<small>(online) - le dije a mi (L) no cometas el crimen, si no vas a cumplir la condena!!!!</small></span>

**Comment by c10ud** [comment] 2010-07-20 15:23
i didn't push changes to master yet, so, that's why you're getting this :)

**Comment by c10ud** [comment] 2010-07-22 18:02
pushed to master, we're ok with conversation etc.

there's an issue with personal messages containing emoticons. Since we're applying blindly the <small> [personalmessagewithemoticons] </small> tags, if there's an emoticon it won't work as expected.

**Comment by arielj** [comment] 2010-07-25 03:51
I think I got the pms with emoticons fixed!

Now there's only 3 problematic nicks on the dummy backend (the one with "o.O random stuff O.o" should be easy to fix, the problem is only the ·$28 at the end, the other two seems more difficult)

**Comment by arielj** [comment] 2010-07-25 04:27
The problem happens only on the contact list because we add our own [$small], [$b] and [$i] tags before the replacement of the smilies and the balancing of the < span > tags. Also, it only happens with the old plus codes (·$ codes).

I think that it would be easier to fix if we add those tags AFTER we have already done the rest, we will have a list of strings and images, we only need to add the correct open and close tag to the strings at the begining and at the end of the string.

ping Mariano!

**Comment by c10ud** [comment] 2010-07-25 08:07
but if you simply replace them after:
 [q][$customtag] «tag small» text «/tag small», pixbuf, «tag small» other text «/tag small» [/$customtag] [/q] 
you get

«customtag», «tag small» text «/tag small», pixbuf, «tag small» other text «/tag small», «/customtag»
which i think breaks the markup 
btw i'll try your branch asap :D

edit: blah github craps my message :(
edit2: «» saved the day

**Comment by c10ud** [comment] 2010-07-25 09:16
about the old irc color codes: in emesene1 we "closed" those tags that can be found in some stupid nicks with some "special" character "­" or something like that, now we're parsing the entire string so the color continues till the end, that's the main reason of the problem, we're not closing the tag after the nick is parsed, so it remains opened and applies the markup to the subsequent text. 

In emesene1 parser we used the UserListDataType parser to handle this issue, but from what i've seen it wants a "model" string with a list of stuff, and that's why emesene1 work. however since emesene2 supports a "custom" userlist markup i couldn't find a way to use this parser instead of the PangoDataType one, which works great in labels, etc. 

see emesene1 UserList.py as example, the "model" is something like %s\n«pangotagthatmeanssmall»«pangotagthatsetsfgcolor»%s«/»«/» and it's been given to the parser along with nick and pm.. if we can find a way to replicate that, then we're done

edit: userlistdatatype, not conversation

**Comment by c10ud** [comment] 2010-07-25 09:30
loud thinking:
what if the user list template would be something like sobstituting the [$account], [$displayname] stuff with %s instead and then returning a string ready for the UserListDataType parser? so $small tags become correct pango markup span small tags with the given fields represented as %s, and the template returns a string with all of this AND a list of what it needs to be passed to the UserList Parser (emesene1-like)
now i don't have the time for doing this since i'm going out, but this could save us from modifying ANYTHING from the "old" parsers, which is a thing we all want to avoid since they're DANGEROUS ;)

**Comment by c10ud** [comment] 2010-07-25 09:33
ofcourse this needs a bit of change in gtkui/ContactList.py, and a new userlist-specific CellRenderer that uses a brand new method in Renderers other than "msnplus_to_list" that handles this kind of data coming from the contactlist. in the end, who the hell would want to change the gtk cellrenderer we use in the gtk ui? i'd only leave plus/noplus as global option and keep only one cellrenderer. saves asses, lazyness, big cleanup in code etc.

**Comment by arielj** [comment] 2010-07-25 14:36
I made some hack that works really good with the default layout and works pretty good with other custom layouts.

I just made the color affect until the first " \ n ", on the default layout it works great, no more broken email/status/pm, but if I remove the [$NL] from the template, the color extends until the end of the line over the email and pm. I just need to find out where I need to put that special closing char ;)

**Comment by arielj** [comment] 2010-07-25 15:08
I have an idea but I can't make it work, are you sure about that "& # 1 7 3 ;" char?

I want to try this... when we replace the template with the actual values on ContactList.py, I check if there's some "·$" code and, if true, add that color-break char at the end of that part, so, the char will be there on the right position!. The problem is that I put that char at the end of the nick but the color keeps working until the end of the line.

I just need to know how to add that or how to add anything that means "paint until here". I think I can create my own special string and then replace those strings with "< / span >", but it's really ugly :P

**Comment by arielj** [comment] 2010-07-25 15:46
my last propouse of a special string that means "no-more-plus-color" works! what do you think? I know it's really ugly :P

I've put a todo, maybe someone can fix that using msgplus color codes (that special char)

**Comment by arielj** [comment] 2010-07-25 15:50
the only problematic nicks left are the one with the flag and the one with all those Xxxx, the "·#" code means bold and the "·&" code means italic ("·@" means underlined)

EDIT: we consider them as plus codes, but we wait for a closing code (the same code), if I change the nicks of the dummy backend and close the italic or bold using the same code ("·#" at the end) it works!!

I think we are not considering them as msgplus color codes on Plus.py but I have no idea how to fix that :P.

**Comment by c10ud** [comment] 2010-07-25 18:11
i'll re-pull your branches asap, however i noticed when hacking that the irc color codes (·# ·& etc.) worked when no newline was available. 

breaking the previous colors on newline seemed a sane option, maybe an even better one is forcing breaking any Plus! markup when substituting the nick/pm template. i.e. [$nick] should really mean "[start layouting] nick that will be parsed [stop every layout]" instead of just "nick that will be parsed".

i don't have some clear ideas since i didn't check your branch, i'll try and write l8r :)

**Comment by arielj** [comment] 2010-07-25 18:31
I have done more hacks and now it works for every nick!

It now closes @#&' codes and then closes teh ·$ color codes with a < / span > and it works really good :D

All the nick on the dummy backend works and I've tested some nicks that had problems that were not on the dummy backend, everything displays as it should!

check my latest commit

**Comment by c10ud** [comment] 2010-07-25 18:52
wow m3n! lemme check it out, i didn't even time to have dinner and you say me you fixed everything!

**Comment by c10ud** [comment] 2010-07-25 18:54
yeah, everything works good as expected! congrats ariel! now i'll tidy up a bit and push to master! :D

**Comment by c10ud** [comment] 2010-07-25 19:12
i haxed noplus, now it works ok :D i think in future we should get rid of choosing a different widget for plus/noplus behaviour...this should be moved to a simple runtime killswitch. meanwhile, this issue is CLOSED!

**Closed as completed** 2010-07-25 19:29 UTC
Labels: Logging
