### ISSUE TITLE
Annoyances that won't allow to use 2.0 

### ISSUE THREAD

**Issue by hit** [emesene/emesene#36] opened 2010-06-06 15:18 UTC
a) No autofocus to input box in conversation window;
b) No (custom) emoticons and text formatting, at least with adium;
c) Sounds can't be turned off;
d) Notifications and sounds are displayed/played twice sometimes;
e) No shift-enter to get a newline in input box;
f) Avatar not always updated in contact list and/or user panel and/or conversation (theme).

This is not a bug report, but more like a to-do list :)

**Comment by sledgehammer999** [comment] 2010-06-06 15:44
I cannot reproduce number a. 
Can you give more steps on that?

**Comment by hit** [comment] 2010-06-06 15:57
i.e open some tabs and switch between them, cursor should be placed to input box.

**Comment by sledgehammer999** [comment] 2010-06-06 22:00
Ok I have confirmed it. My cb84a47 commit fixes the element a of this issue. It is a dirty hack though. See the code comment for more info and this link I found through google-->http://www.mail-archive.com/pygtk@daa.com.au/msg17755.html

**Comment by arielj** [comment] 2010-06-26 15:41
My http://github.com/arielj/emesene/commit/2d878386e124c8e203797109672b0c6e0220cd6f commit should fix item D.

**Comment by arielj** [comment] 2010-06-26 15:44
Item E is already fixed too.

**Comment by c10ud** [comment] 2010-06-26 16:34
ok, so what do we have left?
B, C, F?

**Comment by arielj** [comment] 2010-06-26 17:05
B - Text formatting works on the gtk TextBox widget, the problem is only on the AdiumTextBox.

C - I'll start with the mute sound option.

EDIT: item C done - http://github.com/arielj/emesene/commit/18e068c9bbe7fe01cbd911082088b9ad9187445b

I can't try B since I can't use Adium Themes on Windows.

Maybe we can use separated Issues for items F and B, so we can close this and make a better debug on a new Issue? F looks harder to debug, I've never use emesene with my normal account so I can't even confirm this.

**Comment by c10ud** [comment] 2010-06-27 10:08
ok

**Closed as completed by c10ud** 2010-06-27 10:08 UTC
