### ISSUE TITLE
.config/emesene2 folders mess

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#6] opened 2010-02-27 22:23 UTC
Hi, I think we need a better way to handle all those folders...

I mean... I have a lot of folders inside there, one for every contact on the list of each account that have ever logged in and also a folder for each server that was used (dummy, gtalk's, messenger, facebook) with the accounts used on those servers.

I think that the best solution is:
One folder for each server
One folder for each logged account inside each server
A "contacts_cache" folder or something like that inside each logged account with all the folders created for the contact list's users

What do you think? I'm not sure yet what do I have to touch to fix that, but I'd like your feedback before doing anything...

EDIT: also, some parts of the code uses "-at-" instead of @ for logged users, what should we use? I think that @ is better

**Comment by arielj** [comment] 2010-02-27 22:31
EDIT: removed message

**Comment by c10ud** [comment] 2010-03-19 23:59
i add: we should support XDG if available

p.s. the mess is growing

**Comment by arielj** [comment] 2010-03-21 00:44
I think the folder mess is almost fixed now (thanks cando I think!), the only bug I found is that the server folder is not the right one when autologin.

Steps to reproduce:
1-Remove the dummy.server folder from .config/emesene2
2-Log in using papyon with the AutoLogin option enabled
3-close emesene
4-start emesene

the dummy.server folder will be created and all the data will be stored there instead of the hotmail server folder.

This doesn't happen if the autologin option is not enabled.

@c10ud: That XDG this is really easy to implement, but I can't test it on windows. the patch for emesene1 was really simple, just expand some variable and use that instead of .config, the rest is unchanged

**Comment by cando** [comment] 2010-03-22 20:50
yes i've moved something and now it's almost fixed , but i've not created a directory only for contacts_caches directories..Do you think is it necessary?

**Comment by arielj** [comment] 2010-03-23 01:40
Necesarry? of course not hahaha, just to make it cleaner, to don't mix all the contact's folders with our own folders (there's no folders there by now, but it may be in the future, I like emesene1 directories :P).

But no, it's not necesarry, though we should make a decission before emesene2 launch.

**Comment by cando** [comment] 2010-03-23 09:16
ok!:)..however i've tried to reproduce your problem...but here doesn't happens...

**Comment by cando** [comment] 2010-03-23 10:06
forget me...i've reproduced your error...

**Comment by cando** [comment] 2010-05-05 18:28
maybe that mariano has fixed that with his lasts commits...

**Comment by c10ud** [comment] 2010-05-05 22:13
so, is this working good? we should consider moving to xdg folders btw

**Comment by cando** [comment] 2010-05-06 08:54
yeah,why not? btw now i'm using emesene2 and i can't reproduce that error...so i think it's fixed...

**Comment by c10ud** [comment] 2010-05-11 16:58
so, i mark this as fixed. pull from emesene/emesene and if something bad happens reopen the issue

**Closed as completed by c10ud** 2010-05-11 16:58 UTC

**Comment by cando** [comment] 2010-05-11 17:44
ok!
