### ISSUE TITLE
Problems with file transfers (trying receive files)

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#683] opened 2011-06-24 20:02 UTC
I get notification that there are invitations to transfer, but nothing appears.

**Comment by Mystro256** [comment] 2011-06-26 21:56
is this a duplicate of #677? If so, please close this and post an comments there. If not, can you go into detail at all?

**Comment by c10ud** [comment] 2011-06-27 22:55
yep, duplicate of #677 and probably others i lost track of :(

**Closed as completed by c10ud** 2011-06-27 22:55 UTC
