### ISSUE TITLE
File transfer problem

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#499] opened 2011-05-04 05:28 UTC
I am using emesene 2 in Ubuntu 11.04 and i cant send or recieve files with my msn contacts . I also use msn protocol !!!

When i send a file , my contact dont see anything . The same thing happens when my contact sends me a file : A notification appears on the right side of my screen but i cant see the file to press accept

With emesene1 i didnt have the same issue . Everything was allright

Any idea? Is it a bug ?

**Comment by rockybalboa** [comment] 2011-05-04 07:02
In Ubuntu 11.04 the emesene version is 2.0.git.blabla. Enable natty-proposed in Software Sources (you can find it in Software Center / Edit menu) and install the version 2.11.4.

**Comment by ghost** [comment] 2011-05-04 10:31
My version is allready 2.11.4 but still having the issue !!!

version 2.11.4 is stable ?

**Comment by rockybalboa** [comment] 2011-05-04 11:40
Yes, it is the stable. But I have problem with file transfer too. But it isn't a big problem for me, I don't use it too much.

**Comment by ghost** [comment] 2011-05-04 14:54
whats your problem ?

Also do you know where can i find plugins for emesene2 ? From preferences menu plugins tab is absolutely empty ...

**Comment by Mystro256** [comment] 2011-05-04 18:02
The MSN protocol seems to generally be glitchy with transferring period, I've actually had my best experience with transferring with emesene to be honest. This may not be a problem with emesene/papyon, as I've had just as many issues with using the official client between each other.

Is your contact using the latest emesene or the latest official client?

**Comment by Fabio-pereira** [comment] 2011-05-04 18:14
I am experiencing the same problem here. A contact tried to send me a file, I saw the notification but nothing else happened.

OS.: Ubuntu 11.04
Emesene: 2.11.4

**Comment by ghost** [comment] 2011-05-04 18:23
I switched back to emesene 1.6.3 ... to many bugs emesene2 

Lately my contacts coyld not send me also messages !!!!

**Comment by Mystro256** [comment] 2011-05-04 18:30
This isn't normal, and believe it or not, emesene 1.6.3 seems to have more issues. DId you try going into preferences and hitting the Live messenger tab, because changing your image using that link supposedly fixes a lot of issues for whatever reason. Apparently using Emesene 1.6.3 undo's this though.

**Comment by Fabio-pereira** [comment] 2011-05-04 18:35
I already used "the sacred" Live messenger tab, it really fixed a lot of things (specially the private message and avatar), but the file transfer issue happened after that.

**Comment by Mystro256** [comment] 2011-05-04 18:39
Hmm, well the only other thing to suggest is using the latest papyon (currently 0.5.5.1ubuntu1.1 in natty pre-prosed) or trying it again with the latest git

**Comment by c10ud** [comment] 2011-05-05 08:59
with natty-proposed packages you get all the protocol specific issues fixed, if there's some other bug emesene-related, just explain better, "filetransfers don't work" doesn't really mean something to me :)

**Comment by rockybalboa** [comment] 2011-05-05 09:17
It's a little bit offtopic, but when emesene 2.11.4 is move to Ubuntu "normal" repo from natty-proposed?

**Comment by c10ud** [comment] 2011-05-05 10:02
never, it will be in oneiric though. natty-proposed is quite safe to keep anyway

2011/5/5 rockybalboa
reply@reply.github.com:

**Comment by Mystro256** [comment] 2011-05-05 15:17
Well I'm sure there will be more versions of emesene between then and now, I take that means oneiric will have outdated software? :/

**Comment by c10ud** [comment] 2011-05-05 15:23
i guess packagers will take care of that before releasing the new
ubuntu version just like they did with natty

2011/5/5 Mystro256
reply@reply.github.com:

**Comment by Mystro256** [comment] 2011-05-05 15:24
I guess it's better than nothing

**Comment by Fabio-pereira** [comment] 2011-05-06 14:03
Today I figured out that the issue is probably related to the tabbed conversation. I unmarked tabbed conversation and started using different windows for each conversation. After that, file transfers are working ok.

**Comment by invazor** [comment] 2011-05-23 19:44
Hi, I have the same problem.

Terminal.
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
No handlers could be found for logger "emesene"

**Comment by Zincr0** [comment] 2011-06-05 05:29
Same problem (not the same bug -maybe-?):

[00:58:15 WARNING papyon.msnp2p.transport.switchboard] Invalid TLP chunk in SB message: TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 8e ea 2f 21 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00
ef 72 6b 1d ff fe 62 13 ca 02 00 00 00 00 00 00

**Comment by c10ud** [comment] 2011-06-05 08:57
everyone please make sure you have python-papyon >= 0.5.5

also, receiving files could be affected by a ui-bug which we were unable to find/fix as of now

**Comment by spyalert01** [comment] 2011-06-21 19:01
Emesene 2.11.5 + Python-Papyon 0.5.5-2 - still Emesene / Empathy will not set message to MAC MSN, but it can receive message sent by MAC MSN.
Any work around?
When using Pidgin, I can send to MAC MSN and Receive from MAC MSN as well. 
But I still like Emesene

**Comment by c10ud** [comment] 2011-06-21 19:22
i asked papyon devs but no luck so far.. maybe you have better luck,
try contacting them!

2011/6/21 spyalert01
reply@reply.github.com:

**Comment by pepeleproso** [comment] 2011-06-28 02:04
please retry with lastest git, I think original issue it's fixed now.

**Comment by c10ud** [comment] 2011-07-27 19:09
OP didn't say anything, assuming fixed

**Closed as completed by c10ud** 2011-07-27 19:09 UTC
