### ISSUE TITLE
Error message at Emesene 2.12.9 login

### ISSUE THREAD

**Issue by rrogger** [emesene/emesene#1545] opened 2012-10-29 16:00 UTC
Emesene 2.12.9 does not connect. If I run it from the terminal I get the following message;

Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in **bootstrap_inner
    self.run()
  File "/usr/share/emesene/emesene/e3/base/Logger.py", line 882, in run
    self.logger = Logger(self.path, self.db_name)
  File "/usr/share/emesene/emesene/e3/base/Logger.py", line 364, in __init**
    self._load_events()
  File "/usr/share/emesene/emesene/e3/base/Logger.py", line 396, in _load_events
    self.execute(Logger.SELECT_EVENTS)
  File "/usr/share/emesene/emesene/e3/base/Logger.py", line 598, in execute
    self.cursor.execute(query, args)
OperationalError: no such table: d_event

Violación de segmento (`core' generado)

OS: Ubuntu 12.10 64bit

**Comment by pepeleproso** [comment] 2012-10-31 22:22
Seems your log db is broken. Please delete ~/.config/emesene2 and retry. Anyway the cause of the crash is bug #1537

**Comment by rrogger** [comment] 2012-11-01 12:32
Dear Jose,

Thank you for your reply. I deleted ~/.config/emesene2 but unfortunately 
I get the same error message.

```
Gtk-Message: Failed to load module "overlay-scrollbar"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9:
reading configurations from ~/.fonts.conf is deprecated.
Exception in thread Thread-3:
Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 552, in
__bootstrap_inner
     self.run()
   File "/usr/share/emesene/emesene/e3/base/Logger.py", line 882, in run
     self.logger = Logger(self.path, self.db_name)
   File "/usr/share/emesene/emesene/e3/base/Logger.py", line 364, in
__init__
     self._load_events()
   File "/usr/share/emesene/emesene/e3/base/Logger.py", line 396, in
_load_events
     self.execute(Logger.SELECT_EVENTS)
   File "/usr/share/emesene/emesene/e3/base/Logger.py", line 598, in
execute
     self.cursor.execute(query, args)
OperationalError: no such table: d_event
```

Kind regard,

Roberto Roggerone

---

**Comment by Sbte** [comment] 2012-11-03 00:14
This is probably a duplicate of #1537. The broken database comes from a crash that happens before a database operation is completed. This means that the next time you start emesene, you get this traceback.

**Closed as completed by Sbte** 2012-11-03 00:14 UTC
