### ISSUE TITLE
[Endpoint notification] Emesene disconect and reconnect

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1367] opened 2012-06-25 03:07 UTC
emesene is disconnect yourself, and reconnects, it appears that we are connected elsewhere.

**Comment by moneycat** [comment] 2012-06-25 03:10
@zipatei Please give me more details of the scenario or reproduce steps, thanks.

**Comment by moneycat** [comment] 2012-06-25 04:37
OK...I reproduced it. It seems the guid or machine_guid is replaced by a new one. Steps:
1) login into emesene
2) disconnect (eg. unplug) the network and reconnect it as soon as possible
3) click 'reconnect now'
4) the added event trigged

ps. the event is not triggered every time, it shown 3 times out of 10 test in my case.

@c10ud any idea?

**Comment by pepeleproso** [comment] 2012-06-25 12:57
maybe we could store the guid in config? I think somewhere we have a FIXME comment about this.

**Comment by moneycat** [comment] 2012-06-26 08:52
Strangely...I dig into the codes of login procedure and all logic seems well. When disconnect and reconnect, a new session start and also got a new uid.

I think it is a problem due to msn server because the endpoint disconnection procedure is slow at that time. Then we got the last one ep id (which is disconnected).

**Comment by moneycat** [comment] 2012-06-26 09:52
@pepeleproso Is it possible to add a pending signal when network disconnected? If it is possible, it can help us to send a endpoint_disconnected signal of the previous ep_id if possible.

**Comment by c10ud** [comment] 2012-06-26 19:05
i always wanted to set the uuids the "hard way" which means:
- we generate an uuid for the emesene install, or account
- we save it in config
- we load it and force it in papyon in every session

so it would be more wlm-like

it shouldn't be difficult but right now i don't remember the proper code to touch

**Comment by c10ud** [comment] 2012-06-26 19:05
short story: if you want to do it, it should be easy

**Comment by moneycat** [comment] 2012-06-27 01:51
@c10ud OK. I'll give a try. :)

**Comment by moneycat** [comment] 2012-06-28 07:51
OK, it seems the implementation is done. Before commit to mainstream, if you want to test, the code is here: https://github.com/moneycat/emesene

**Comment by c10ud** [comment] 2012-06-28 09:19
code looks good, just push it ;) (didn't test but checked briefly)

also, some information about papyon:
i am keeping track of modifications we do to papyon in emesene/papyon repository; i committed your latest endpoints changes and i will commit your uuid ones. but if you want you can commit them directly, you should have the rights (or if you don't you just ping me)

**Comment by moneycat** [comment] 2012-06-28 09:29
I'll ping you if there are useful commits for papyon. :)

Then I have a question about papyon. Will it be mess if user have installed python-papyon package and there is a built-in version (with modifications) in emesene when import papyon? Like here: emesene/e3/papylib/papyon/papyon/**init**.py

**Comment by c10ud** [comment] 2012-06-28 10:12
the python-papyon package in most distributions will simply not work
because of missing features: emesene will import the version we have
in our tree and if there's none it will try to fallback to system
version.. unless you mess with the source, it will only use the
provided version ;)

2012/6/28 moneycat
reply@reply.github.com:

**Closed as completed** 2012-06-28 10:13 UTC
Labels: feature, papylib

**Comment by zipatei** [comment] 2012-06-28 11:58
Not fixes. I returned to have the same problem.

**Comment by c10ud** [comment] 2012-06-28 12:11
just tested and it works, check you're really with latest git
