### ISSUE TITLE
Coversation mixing

### ISSUE THREAD

**Issue by andreskru** [emesene/emesene#58] opened 2010-07-13 18:03 UTC
I was chating with two friends in separate tabs, and when i change the tabs i note that the conversation has mixed. In other words, a message of "conversation 1" appeared in "conversation 2". Really weird. It happen to me a couple of times before.
See attach.
http://img411.imageshack.us/img411/8418/conversartionmix.jpg

**Comment by c10ud** [comment] 2010-07-14 22:00
ouch! which backend were you using? i guess msn (papyon)

p.s. eze es un chico culeado!

**Comment by andreskru** [comment] 2010-07-14 23:21
Im using msn (papyon). 
p.s. que culeado!!!

**Comment by marianoguerra** [comment] 2010-08-14 19:27
can someone post reproducible steps for this one?

**Comment by c10ud** [comment] 2010-08-15 09:17
i think it maybe a bug in papylib where an already opened conversation connects signals twice, or more on switchboard reconnect, due to the recent changes to papyon lately (it supports msnp18, multiple point of presence, p2pv2, etc.) the whole code requires some check, but i didn't have time yet and cando disappeared :P

**Comment by c10ud** [comment] 2010-10-27 15:28
confirm it's still broken or i'll close this issue

**Comment by andreskru** [comment] 2010-10-27 23:49
I doesnt see again, still testing.

**Comment by c10ud** [comment] 2010-10-28 13:49
if you see it again please open another issue

**Closed as completed by c10ud** 2010-10-28 13:49 UTC
Labels: papyon
