### ISSUE TITLE
Saveable emoticons

### ISSUE THREAD

**Issue by hit** [emesene/emesene#709] opened 2011-07-04 13:10 UTC
You should be able to right-click on emoticons in conversation and save them.

**Comment by arielj** [comment] 2011-07-04 13:47
It's implemented and it worked before (at least with adium themes), but now is broken (I don't know why), this is a regression, I'll try to fix it when I get some time.

**Comment by Mystro256** [comment] 2011-07-05 20:46
How far back are we talking about? I did a git bisect from master to v2.11.4 and there doesn't seem to be any support for it along the lines.

I'll take a skim through the commits but I don't remember this ever working, so I'm a little puzzled haha ;)

**Comment by Sbte** [comment] 2011-07-05 22:13
I think this commit: cb49e849e9e2a7ea69a9fa186ac5519c74df285d

**Comment by arielj** [comment] 2011-07-06 00:54
yeap, that commit, at least it was working back then :P

**Comment by Mystro256** [comment] 2011-07-06 01:11
I'll take a look, I'll see if I can narrow down the cause of misfunction at least.

**Comment by Mystro256** [comment] 2011-07-06 14:41
I did a git reset like so:

```
git reset --hard cb49e84
```

All I get from right clicking a custom emotion is <i>select all</i> and <i>clear</i>. Am I missing something? :/

**Comment by arielj** [comment] 2011-07-06 16:45
Just tested it using latest git on windows and it works, maybe it's not working only on linux? I developed that function on windows XP, can you try it on your windows, @Mystro256

EDIT: tested on Ubuntu, it's not working here

**Comment by arielj** [comment] 2011-07-06 18:46
Just commited a fix for this on Ubuntu, I have to check if it's still working on Windows :P (I might have broke it)

**Comment by Mystro256** [comment] 2011-07-07 22:56
This doesn't fix it lol... I tried master with no luck, then tried the git reset with that one commit as well.

**Comment by Sbte** [comment] 2011-07-08 09:16
Read the comments on 957e2ce84bf95ef3cc13ddecb8bf2812f7d9d9f6

**Closed as completed** 2011-07-09 08:53 UTC

**Comment by hit** [comment] 2011-08-12 09:22
With some emoticons I get:

Traceback (most recent call last):
File "/home/hit/Apps/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 173, in on_download_requested
self.add_emoticon_cb(download.get_uri())
File "/home/hit/Apps/emesene/emesene/gui/gtkui/Conversation.py", line 204, in steal_emoticon_cb
groupdict = matches.groupdict({'alt': ''})
AttributeError: 'NoneType' object has no attribute 'groupdict'

Trying to figure out what's really happening there.

**Comment by Sbte** [comment] 2011-08-12 09:41
It would help if you could find out what shortcut they have. Apparently it's not in the text...

**Comment by hit** [comment] 2011-08-12 10:08
At least one of them was with shortcut "üüuus", so maybe an encoding problem again.

**Comment by Sbte** [comment] 2011-08-12 11:05
Works fine here... Not sure what the issue is. Could you open a new issue for this btw?
