### ISSUE TITLE
possible bug (model.get_value(iter, 0))

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1424] opened 2012-07-25 17:54 UTC
``` python
[19:58:16 ERROR papyon.msnp2p.session_manager] Session_id == 0
/usr/share/emesene2/gui/gtkui/__init__.py:96: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
[19:58:17 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[19:58:17 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[19:58:17 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[19:58:17 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
/usr/share/emesene2/gui/gtkui/Renderers.py:699: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  if model.get_value(iter, 0) == image:
[19:58:22 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 04 79 94 57 00 00 00 00 00 00 00 00
49 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
59 b6 d8 13 dc a1 b7 5b 49 01 00 00 00 00 00 00
```

**Comment by Sbte** [comment] 2012-07-25 18:48
Any way to reproduce this? What do you have enabled under Options?

**Comment by KinG-InFeT** [comment] 2012-07-26 14:22
the options are set by default the only thing I changed was the magnitude of the avatars from 32 to 42

**Comment by moneycat** [comment] 2012-07-26 17:15
I can't reproduce this error. Maybe cause by an animated avatar?

**Comment by KinG-InFeT** [comment] 2012-07-26 17:38
possible... my avatar is a .gif... cause this error?

**Comment by Sbte** [comment] 2012-08-05 09:14
I can't reproduce this even with an animated avatar (both sending and receiving). It could be that this is solved by changing `gobject.TYPE_OBJECT` to `gobject.TYPE_PYOBJECT` in Renderers.py. Could you try that?

**Comment by c10ud** [comment] 2012-08-05 10:20
is there some actual error other than the warning?

**Comment by Sbte** [comment] 2012-08-05 10:21
It could be that an image is not properly drawn when the treeview does not find the right type. Better to have the least amount of warnings possible :P

**Comment by c10ud** [comment] 2012-08-06 12:58
http://stackoverflow.com/questions/7032233/mysterious-gobject-warning-assertion-g-is-object-object-failed

seems to suggest what sbte said

**Comment by c10ud** [comment] 2012-08-06 13:04
also: here model.get_value(iter, 0) == image is line 704, so you may want to test with latest git first and see if issue persists

**Comment by c10ud** [comment] 2012-08-06 13:06
update: sbte's suggestion breaks stuff

**Comment by Sbte** [comment] 2012-08-06 16:43
I am wondering though what we put in there that gives a warning.

**Comment by Sbte** [comment] 2012-08-16 15:40
I can't reproduce this with or without animated avatars. Also, it's a warning, not an error message of any kind. If you find that something is actually broken, or if you have a way to reproduce this warning, please reopen this bug. I'm closing it for now.

**Closed as completed by Sbte** 2012-08-16 15:40 UTC
Labels: gtk
