### ISSUE TITLE
No Plus rendering inside chat

### ISSUE THREAD

**Issue by igorsantos07** [emesene/emesene#716] opened 2011-07-06 02:49 UTC
Plus format ([b] form or the old one) are not properly rendered in the chat window, only in the contact list.

**Comment by Mystro256** [comment] 2011-07-06 03:20
I can confirm this, [c=1]text[/c=5] does not change the text colour of my message. Although, might I ask, was this even supported in emesene 1?

**Comment by igorsantos07** [comment] 2011-07-06 03:24
Yes, it was. I think there were a config (plugin?) that would disable that.
I have some friends that use this kind of formatting in their nicks, and they used to appear colored and etc in the chat window too.
Also, I used to use [b] and [u] here and there.

**Comment by Mystro256** [comment] 2011-07-06 03:34
Ah okay, then it can be considered a regression from emesene 1 to 2. If anyone has time, it probably should be fixed, unless there's any objections from the dev's  (ie reasons for leaving it out)

**Comment by c10ud** [comment] 2011-07-06 08:15
won't do it unless someone implements it as a plugin. we have plus in contact list because not having it often lead to unreadable names, but for text, it's useless

**Closed as completed by c10ud** 2011-07-06 08:15 UTC

**Comment by igorsantos07** [comment] 2011-07-06 14:43
But not having it for text lead to unreadable names in chat window too :|

**Comment by c10ud** [comment] 2011-07-06 16:20
different issue than the color plugin featured in emesene1, we're
giving conversations nicks with markup while we should just pass them
stripped..

2011/7/6 igorsantos07
reply@reply.github.com:

> But not having it for text lead to unreadable names in chat window too :|
> 
> Igor Santos
>   Programador Web
> 
> On Wed, Jul 6, 2011 at 05:15, c10ud <

**Comment by igorsantos07** [comment] 2011-07-06 20:39
Should I reopen the bug? Open a new one?

I still think it's a regression, because if it's implemented in the contact list it should be implemented in the chat window too; I think it's confusing to have colored nicks in the list and not in the chat.
