### ISSUE TITLE
Offline message issues

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#943] opened 2011-11-16 17:22 UTC
Two issues in emesene 2.11.11:
1. When start-up and the offline message window popup, the messages still not shown in the conversation log area. As this figure: http://imageshack.us/photo/my-images/204/screenshot2dw.png/
2. In the same window, if I'm in conversation with the contact, only the messages I sent will show. Like this one:  http://imageshack.us/photo/my-images/198/screenshot3bic.png/

P.S. One of my friend use digsby and I cannot receive his offline message. But I can receive the offline messages from this friend whom use MS MSN.

**Comment by c10ud** [comment] 2011-11-17 09:47
1. i think is a webkit webview initialization bug regarding oims/info
   messages ping @pepeleproso
2. we're trying to debug this issue, if you can reproduce and maybe
   get us a debug trace when the problem is happening it would be great

2011/11/16 moneycat
reply@reply.github.com:

**Comment by moneycat** [comment] 2011-11-17 10:10
OK, I'll try with debug mode and attach the result if I could this night.

**Comment by moneycat** [comment] 2011-11-17 14:28
Hi all,
I've created a new msn account (B) and added myself (A) as contact both side. A use emesene 2.11.11, B use MSN 2009.
Here is my test step:
1. try both side online, and the messages sent are all correctly.
2. A offline and B sent offline messages.
3. Make A online but status is invisible. The messages arrived and the notification shown, but the message area is nothing.
4. Make A online with status away. Same result.

Here is some quotes from log I fetched via "emesene -vv 2 > logs", and is the only error of python:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/emesene/e3/base/Logger.py", line 821, in run
    quit = self._process(data)
  File "/usr/lib/python2.7/site-packages/emesene/e3/base/Logger.py", line 842, in _process
    cid=cid)
  File "/usr/lib/python2.7/site-packages/emesene/e3/base/Logger.py", line 585, in add_event
    (id_src_info, id_src_acc) = self.insert_info(src.account, src.id,
AttributeError: 'Contact' object has no attribute 'id'

[21:59:29 WARNING e3.common.Signal] Method called on dead object: _on_message._on_message
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene/e3/common/Signal.py", line 66, in emit
    if callback(_args, *_kwargs) == False:
  File "/usr/lib/python2.7/site-packages/emesene/e3/common/Signal.py", line 115, in __call__
    self.f(self.c(), *arg)
  File "/usr/lib/python2.7/site-packages/emesene/gui/base/ConversationManager.py", line 98, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/usr/lib/python2.7/site-packages/emesene/gui/base/Conversation.py", line 388, in on_receive_message
    self.output.receive_message(self.formatter, msg)
  File "/usr/lib/python2.7/site-packages/emesene/gui/gtkui/TextBox.py", line 394, in receive_message
    text = formatter.format(msg)
  File "/usr/lib/python2.7/site-packages/emesene/e3/common/MessageFormatter.py", line 106, in format
    formated_time = time.strftime('%c', time.gmtime(timestamp))
TypeError: a float is required

On the other hand, is this line the offline messages started?
[22:10:45 DEBUG papyon.transport] <<< MSG Hotmail Hotmail 1452^

**Comment by c10ud** [comment] 2011-11-17 16:21
sbte fixed the second bug in emesene-master... as for the first, it's the first time we see it, but i never looked into logging....

**Comment by Sbte** [comment] 2011-11-17 16:40
It's added to the log in papyon worker, so something goes wrong between papyon and the conversation window...

**Comment by Sbte** [comment] 2011-11-17 16:42
The second issue is actually the same bug, because _on_message was unsubscribed due to the error. 

Fixed by 3dc05bfd5531d778884b05073a021068966ef68b

**Closed as completed by Sbte** 2011-11-17 16:42 UTC

**Comment by moneycat** [comment] 2011-11-17 17:04
Please forgive my for not checking with the latest development version. This issue fixed by it correctly. Thanks a lot.
