### ISSUE TITLE
Chat history doesn't work

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#139] opened 2010-10-30 18:57 UTC
When I go to View Information -> Chat history, I get the two calendars and a white screen for every person. Even for the ones I talked to. Chats set from september 30 to october 30. The only message I get on the terminal when going to View Information is

*\* Message: console message: undefined @1: ReferenceError: Can't find variable: scrollToBottom

I'm not sure if this is supposed to work, but for me it sure doesn't ;)

EDIT: When going to View Information for the first time during a session I get this:

Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/base/Logger.py", line 779, in check
    callback(result)
  File "/home/sven/emesene/emesene/gui/gtkui/ContactInformation.py", line 331, in _on_chats_ready
    for (stat, timestamp, message, nick) in results:
TypeError: 'NoneType' object is not iterable

EDIT2: I also stumbled across this error when shutting down emesene with a message window open. Maybe it has something to do with it?

Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/home/sven/emesene/emesene/e3/base/Logger.py", line 745, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

**Comment by 4javier** [comment] 2010-11-01 19:57
How did you get those messages? I have the same problem, but also launching emesene.py -vv I can't get get anything useful clicking View Information and Chat History.

**Comment by Sbte** [comment] 2010-11-01 23:32
I just launch emesene/emesene. Other than that, there is a description above on how to reproduce the messages.

**Comment by marianoguerra** [comment] 2010-11-08 04:50
fixed the bug of iteration over None, the second is not a bug, it's the result of closing the program with some threads still running, can be fixed with a join and a wait while closing, it was like this before, someone removed it.

chat history still doesn't work but this issue is fixed.

there is another issue for chat history not working, we should continue there.

**Comment by Sbte** [comment] 2010-11-08 08:37
Which one? You mean #145? That only happens in months with 31 days. So that should have low priority, because it only happens again at the end of December.

**Comment by marianoguerra** [comment] 2010-11-08 12:05
yep, it's a little specific but we should fix it, also the other big problems seem to be fixed now, I have a strage TypeError comming from nowhere that I must find but other than that I think I can make it work in some days.

**Comment by Sbte** [comment] 2010-11-08 12:13
I have that too. I sometimes get the same message during chats too, but I didn't manage to find out exactly when it happens. At least it also happens when I open a chat window, but maybe that has nothing to do with it.

Anyways, is the db corrupt, and should I delete it, or is the chat history reader still unable to display what's in it? Because I still can't see anything in the chat history window.

**Closed as completed** 2010-11-08 12:50 UTC
Labels: HARD, core
