### ISSUE TITLE
"Enter" conflict "Imput Method" at InputText

### ISSUE THREAD

**Issue by chy168** [emesene/emesene#159] opened 2010-11-03 16:59 UTC
In "InputText", we always use "ENTER" to send message.
I got a problem with "ENTER" event send.

I use "gcin" (a Imput Method) to type my language. I cannot use "ENTER" sending out my words to InputText. The InputText will capture the "ENTER" signal FIRST. This cause my IM cannot perform the right action.

How can we adjust the event capture priority in a good way?

**Comment by c10ud** [comment] 2010-11-03 20:26
how do other clients handle this?

**Comment by chy168** [comment] 2010-11-04 08:23
ok, I think that is my IM problem. I use another IM will solve this problem.
I think there are some strange hackings in that one.

**Comment by c10ud** [comment] 2010-11-04 09:04
glad you somehow solved it :)

**Comment by chy168** [comment] 2010-11-04 09:25
hmmm ... I am still pending this problem. Maybe there have some tool, let me monitor where the signal goes ?
The problem is, "ENTER" signal is emitted. It's captured by emesene FIRST, not IM.

(should I discuss problem in closed issue ?)

**Comment by c10ud** [comment] 2010-11-04 09:52
i reopened it. does this happen with emesene-1 too? or other clients such as amsn, pidgin, etc.?

**Comment by chy168** [comment] 2010-11-04 10:08
it's NOT happened in emesene-1.
I've meet the same problem in xchat (IRC client).

**Comment by c10ud** [comment] 2010-11-04 10:51
unfortunately i don't use any input method, so i can't help :(

**Comment by chy168** [comment] 2010-11-04 11:03
how can we modify the "enter" signal priority ?

**Comment by c10ud** [comment] 2010-11-04 11:10
i don't know if there're "priorities" in signals :S maybe you could ask in #gtk

**Comment by chy168** [comment] 2010-11-04 11:13
hmmm ... ok thank you !! :)

Why we use ScrollWindow to be InputText not HBox ?

**Comment by c10ud** [comment] 2010-11-04 11:20
no idea, we should wait mariano's opinion on this one :p meanwhile, if you can do some tests...:)

**Comment by chy168** [comment] 2010-11-04 11:45
No problem !!
I will trace or test what I could think .... :p

**Comment by marianoguerra** [comment] 2010-11-07 20:35
we use ScrollWindow because we want the text to scroll if the user enters more text than the space available.

about the signal handling, I tried connection the signal after the default signal and it doesn't send the message. In emesene 1 we did it in a different way that is hard to reproduce, I will see if I can find something.

**Comment by marianoguerra** [comment] 2010-11-07 20:48
chy168: I ported the way emesene 1 did things, can you test it?

anyone else, if someone finds something strange going on with input/output let me know.

**Comment by chy168** [comment] 2010-11-08 03:24
Yes, I test it. It works good now.

marianoguerra: what difference between two signal behave ?

**Comment by marianoguerra** [comment] 2010-11-08 04:02
I'm processing the signal after the other signals now, so the default treatment for the input method are handled now.

closing.

**Closed as completed by marianoguerra** 2010-11-08 04:02 UTC
Labels: gtk
