### ISSUE TITLE
Contacts Avatar

### ISSUE THREAD

**Issue by amoksito** [emesene/emesene#722] opened 2011-07-11 22:56 UTC
My problem is that I can't see the avatar from certain contacts. Some of the same users show the avatar in Pidgin. Others not. And, at the same time, some avatar that I can see in Emesene 2.11.5 can't be viewed in Pidgin. 

Some advice?

Mi problema es que no puedo ver el avatar de algunos contactos. En Pidgin puedo ver la imagen de algunos contactos que no puedo ver en Emesene 2.11.15 y viceversa. 

Algun consejo?

**Comment by Mystro256** [comment] 2011-07-26 15:19
is this perhaps a duplicate of #602?

I've noticed that in 2.11.5, compared to 2.11.4, there's a lot less avatars in my contact list, but I can't tell or confirm if it's a regression, as all many of my contacts could have removed their pictures lol.

**Comment by Sbte** [comment] 2011-07-26 20:11
Yeah, we need to wait for the msnobj to be ready. We know what the problem is, but I don't know a proper fix not involving a glib timeout. 

Closing as dupe of #602, and I think some other bug also around.

**Closed as completed by Sbte** 2011-07-26 20:11 UTC
