### ISSUE TITLE
Error while delivering message - it is delivered

### ISSUE THREAD

**Issue by Smile4ever** [emesene/emesene#1172] opened 2012-04-16 17:58 UTC
I get an "Error while delivering message" from papylib (see debug output)

Debug output (error only):
(19:43:26) papylib.Events:Error sending message: 4 1
(19:43:35) papylib.Events:Error sending message: 4 1

Full output (anonymised):

papyon.protocol.switchboard_manager:Requesting switchboard for participant(s) Si___XSnoopy@hotmail.com
(19:29:36) papyon.protocol.switchboard_manager:Using already opened switchboard 569288862
(19:29:36) papyon.protocol.switchboard_manager:Handler <SwitchboardP2PTransport peer="Si___XSnoopy@hotmail.com" guid="0a660ac8-6e78-407d-8fea-336abbeca268"> attached to switchboard 569288862
(19:29:36) papyon.msnp2p.session:Session 246299585 disposed
(19:29:36) papyon.msnp2p.transport:Cleaning up session 246299585
(19:29:36) papylib.Events:Error sending message: 4 1
(19:29:36) papyon.msnp2p.transport.switchboard:Received error: 1 (type=4)
(19:29:36) papyon.msnp2p.transport:Unregistering transport <SwitchboardP2PTransport peer="Si___XSnoopy@hotmail.com" guid="594174f6-41f2-4a0f-9b05-932b94dd415b">
(19:29:36) papyon.protocol.switchboard_manager:Closing switchboard handler <SwitchboardP2PTransport peer="Si___XSnoopy@hotmail.com" guid="594174f6-41f2-4a0f-9b05-932b94dd415b">
(19:29:36) papyon.msnp2p.transport.switchboard:Received error: 1 (type=4)
(19:29:36) papyon.msnp2p.transport:Unregistering transport <SwitchboardP2PTransport peer="Si___XSnoopy@hotmail.com" guid="0a660ac8-6e78-407d-8fea-336abbeca268">
(19:29:36) papyon.protocol.switchboard_manager:Closing switchboard handler <SwitchboardP2PTransport peer="Si___XSnoopy@hotmail.com" guid="0a660ac8-6e78-407d-8fea-336abbeca268">
(19:29:36) papylib.Events:Error sending message: 4 1
(19:31:05) papyon.profile:Set contact Si___XSnoopy@hotmail.com flags to 1
(19:31:15) papyon.profile:Set contact Si___XSnoopy@hotmail.com flags to 1
(19:31:22) papylib.Events:Contact's client capabilities changed: <papyon.Contact id='826c1443-eda4-4192-9020-fece4a6bfb01' network='1' account='Si___XSnoopy@hotmail.com' memberships='FORWARD | ALLOW | REVERSE'>
(19:31:44) papyon.profile:Set contact marieke__horseslover@live.nl flags to 1
(19:32:58) papylib.Events:Contact's client capabilities changed: <papyon.Contact id='ed635471-2f8e-4474-992e-1f793e7d5864' network='1' account='pleun-_m_a_e_@hotmail.com' memberships='FORWARD | ALLOW | REVERSE'>
(19:32:58) papyon.profile:Set contact pleun-_m_a_e_@hotmail.com flags to 1
(19:32:58) e3.common.Signal:Signal handler (_on_contact_attr_changed._on_contact_attr_changed) error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
(19:33:03) e3.common.Signal:Signal handler (_on_message._on_message) error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
(19:33:19) e3.common.Signal:Signal handler (_on_message._on_message) error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
(19:34:07) e3.common.Signal:Signal handler (_on_message._on_message) error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
(19:34:23) papyon.profile:Set contact Si___XSnoopy@hotmail.com flags to 1

This is a related bug, but not the same: https://github.com/emesene/emesene/issues/1160

**Comment by Smile4ever** [comment] 2012-04-16 18:25
Emesene -vvv output:

http://pastebin.com/0Ku7Def7

**Comment by c10ud** [comment] 2012-04-17 09:00
From what i see here your friend is NAK-ing p2p data, that maybe because his msn version is crap or something like that

**Comment by Smile4ever** [comment] 2012-04-19 15:43
My friend is using Windows 7 with MSN version 2009. It seems to be related to #1171 but at the moment I'm not sure yet if it's the same bug: in the other bug a possible cause is the use of non-hotmail addresses, but here a hotmail.com address is used by my contact. However, I'm using a hotmail.be address.

**Comment by c10ud** [comment] 2012-04-20 15:50
p2p and text are treated the same way by papyon: put in a queue with an ID and then they check if they succeed or fail
when they're checked, there's currently no way to identify if that a was a p2p or text message

see switchboard_manager.py for reference

**Comment by c10ud** [comment] 2012-04-22 19:35
setting this as duplicate of #1171

**Closed as completed by c10ud** 2012-04-22 19:35 UTC
