### ISSUE TITLE
Avatar cropping window is outside the desktop

### ISSUE THREAD

**Issue by Fabio-pereira** [emesene/emesene#494] opened 2011-05-03 14:41 UTC
I am using a notebook with a native resolution of 1280x800 and when I select a new avatar image, the cropping window (where I am supposed to select the desired portion of the image), the window is simply too big to fit the desktop. I can't see any buttons (I suppose they are on the bottom of the window) and I am unable to select the new avatar.

If I was able to resize the window I could manage to (at least) see the buttons. 

OS.: Ubuntu 11.04
Emesene: 2.11.4

**Comment by arielj** [comment] 2011-05-04 16:08
I can not reproduce this, I've set a resolution of 640x480 and an image of 1080x726 and it's resized to fix all inside the screen, maybe it's something only on widescreen resolutions?

**Comment by Mystro256** [comment] 2011-05-04 18:08
Maybe it's specific to a file type? Can you post the image? Or is this happening regardless of the image type and size?

**Comment by Fabio-pereira** [comment] 2011-05-04 18:23
Hi,

It happens with jpg and png files, I didn't test with other image formats as I don't think it is related to that. The picture is 800x600 pixels. I captured the screen image, how can I post it?

**Comment by Mystro256** [comment] 2011-05-04 18:33
Use a image uploading website, like http://imgur.com then post it here with the direct link using html.

for example: /img src=LINK/

but with < and > instead of the /'s

**Comment by Fabio-pereira** [comment] 2011-05-04 18:40
Thank you Mystro256!

Here it is:
<img src=http://i.imgur.com/oDs2s.jpg>

**Comment by Mystro256** [comment] 2011-05-04 18:47
I meant the image you're using as an avatar, not a screenshot, so it can be reproduced.

Also if you want a workaround, you can grab the window while holding the alt key.

**Comment by Fabio-pereira** [comment] 2011-05-04 18:55
I updated the comment with the avatar picture (the one I wanted to crop).

Ohhh,  and thanks for your hint on grabbing the window with alt key pressed!

**Comment by arielj** [comment] 2011-05-05 01:22
Wait for my changes to be applied and this should be fixed

The problem was an if condition, your picture had just the limit resolution to be resizied and was not detected right.

**Closed as completed** 2011-05-05 07:39 UTC
