### ISSUE TITLE
Warning: g_object_set_qdata

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1346] opened 2012-06-18 18:20 UTC
I use:
OS: ArchLinux 
emesene verson: Last GIT
WM: fluxbox with GTK3

emesene -vvv output

Reproducible:
1) Open emesene
2) login
3) open conversation
4) close conversation and close emesene window with ESC key

use single-window mode

``` python
/bin/sh: xprop: command not found

** (process:3087): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:3087): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:3087): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
[20:19:31 ERROR papyon.msnp2p.session_manager] Session_id == 0
/usr/share/emesene2/gui/gtkui/__init__.py:96: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
[20:19:32 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[20:19:32 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[20:19:36 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 fe 65 06 00 00 00 00 00 00 00 00 00
c5 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
0c be 7a 05 16 9c 58 1b c5 02 00 00 00 00 00 00
[20:19:37 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 03 20 01 00 00 00 00 00 00 00 00 00
4d 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
88 49 f9 12 18 9c 58 1b 4d 01 00 00 00 00 00 00
[20:19:37 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 c3 8b 2c 33 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00
ca ad 2b 6b bb a0 59 01 be 02 00 00 00 00 00 00
[20:19:37 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 04 20 01 00 00 00 00 00 00 00 00 00
7a 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
bf 93 ea 28 19 9c 58 1b 7a 02 00 00 00 00 00 00
[20:19:37 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 d9 1f df 79 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00
28 8a 03 67 bd a0 59 01 4b 01 00 00 00 00 00 00
[20:19:37 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 73 d1 97 27 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00
83 60 a3 52 be a0 59 01 77 02 00 00 00 00 00 00
[20:19:38 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 1d 31 27 6a 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00
64 35 fb 3a c0 a0 59 01 4d 01 00 00 00 00 00 00
[20:19:38 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 2b c5 dd 32 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00
c7 ea 9d 00 c1 a0 59 01 79 02 00 00 00 00 00 00
[20:19:38 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[20:19:39 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 ac 2f 0f 00 00 00 00 00 00 00 00 00
4c 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
8f 38 07 40 1c 9c 58 1b 4c 01 00 00 00 00 00 00
[20:19:39 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 19 5f f0 30 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00
19 01 e9 54 c4 a0 59 01 79 01 00 00 00 00 00 00
[20:19:39 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 ad 2f 0f 00 00 00 00 00 00 00 00 00
79 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
36 65 85 73 1d 9c 58 1b 79 02 00 00 00 00 00 00
```

**Comment by Sbte** [comment] 2012-06-18 19:47
Duplicate of #1094

**Closed as completed by Sbte** 2012-06-18 19:47 UTC
