### ISSUE TITLE
right to left direction

### ISSUE THREAD

**Issue by ammarabdulsalam** [emesene/emesene#857] opened 2011-09-12 10:58 UTC
Hello,
can we implement right to left text direction in Adium for Arabic language?

**Comment by c10ud** [comment] 2011-09-26 15:59
we need some dev that's able to handle this kind of stuff (unfortunately we're all ltr)

anyway, if you could attach some screenshot to the bug (with wrong-expected behaviour) maybe someone sees it and is able to fix it :D

**Comment by c10ud** [comment] 2011-11-14 14:00
reopen if you have more info on the issue

**Comment by ammarabdulsalam** [comment] 2011-11-21 09:25
hello and sorry for too late in response,
this is a test message:
تجربة test رسالة message
to read this message correctly, you shpuld read it from left to right.
where it should read from right to left.
the right message should be:
message رسالة test تجربة
Regards.

**Comment by c10ud** [comment] 2011-11-25 10:19
we're not alone with this one: https://bugs.launchpad.net/adium-theme-ubuntu/+bug/538632
i'll see if i can find something useful, i'll leave this post as a reminder

**Comment by c10ud** [comment] 2011-11-25 10:23
we need to try a newer renkoo theme @sbte

**Comment by c10ud** [comment] 2011-11-25 10:51
tried with renkoo from adium's hg master and no luck

**Comment by c10ud** [comment] 2012-02-12 10:41
i've been told that's an issue with (probably) webkit and it has been resolved with an upgrade! I don't know the exact versions though, but a system upgrade solved this RTL-LTR issues

**Comment by c10ud** [comment] 2012-03-05 17:12
i'll close this issue since it depends on webkit, thanks to jamesaxl for the debug

**Closed as completed by c10ud** 2012-03-05 17:12 UTC
Labels: feature
