### ISSUE TITLE
sound issue

### ISSUE THREAD

**Issue by pengshao** [emesene/emesene#498] opened 2011-05-04 01:55 UTC
I am using 2.11.4 tarball

I usually leave "play sound on first received message" and "play sound on received message" both checked.

when I start emesene2, if my friend, assuming he is called "A", sends me a message, it plays a sound, which is normal, then I open the conversation window, then minimize it. Then if A sends me another message, emesene2 does NOT play any sound. Then I close the conversation window, let A send me another message. Now emesene2 plays sound no matter if it is a first message, inactive conversation window, or even active conversation window( say even when the conversation window has focus, it still plays a sound) . 

Thank you for paying attention.

**Comment by pengshao** [comment] 2011-05-04 03:08
I did some further tests, and it looks like this only happens when I choose "Tabbed conversations" in the interface options. If I uncheck the "Tabbed conversations" then emesene2 only plays a sound when I receive a first message from A, and as long as I give focus to the conversation window, it does NOT play sound anymore unless I close the conversation window and do it again.

**Comment by rockybalboa** [comment] 2011-05-04 07:04
Something isn't okay for me too. And yes I think the problem source is the tabbed conversation maybe.

**Comment by Sbte** [comment] 2011-05-04 08:31
Do the text notifications work in the right way? Just wondering. If they do, sounds should just be played at the same time.

**Comment by arielj** [comment] 2011-05-04 12:51
Please, test with the latest sound refactoring (just update your repo), I think it's fixed as a consequence of that refactor :P

**Comment by pengshao** [comment] 2011-05-04 16:28
@Sbte It looks like the notification working well.

**Comment by Sbte** [comment] 2011-05-04 16:29
@shallpion, then it's most likely fixed by arielj's commit. Please test it ;)

**Comment by pengshao** [comment] 2011-05-04 16:30
@arielj. Thanks for the advice. I am using gentoo, and I think everything here is updated. I also tested the git version, which still has this problem...

**Comment by pengshao** [comment] 2011-05-04 16:33
@Sbte sorry I am little confused... what did you mean by "sound refactoring"?... I may try something similar here on gentoo.   Thanks

**Comment by arielj** [comment] 2011-05-04 16:54
Just update your code with the latest commits of the main emesene repo and you're done, test if it works fine now.

**Comment by pengshao** [comment] 2011-05-04 17:08
@arielj How stupid was I, thanks for the explanation. I just tried the latest git version and it indeed changed the behavior, now emesene plays a sound as long as I receive a message under whatever condition, no matter if it is tabbed, in active, inactive...

**Comment by arielj** [comment] 2011-05-04 17:19
so, it's ok? can we close this issue?

**Comment by pengshao** [comment] 2011-05-04 17:26
Sorry one more last stupid question, I remember I saw in another bug report that currently the feature "disable sound when window is active" is not implemented, so this is the supposed way, at least temporarily. Am I right? If I am, then please close this issue, thanks:)

**Comment by pengshao** [comment] 2011-05-04 17:35
And, I just realize that now the "play sound on first received message" is not functioning normally. If I UNCHECK the "play sound on received message" and CHECK the "play sound on first received message", in the past emesene2 plays a sound only on the first message, but now it doesn't plays sound at all

**Comment by Sbte** [comment] 2011-05-04 21:35
```
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(*args, **kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), *arg)
  File "/home/sven/emesene/emesene/emesene.py", line 642, in on_new_conversation
    self.soundPlayer(gui.theme.sound_send)
TypeError: 'SoundPlayer' object is not callable
```

I got this. No clue when it happened.

**Comment by arielj** [comment] 2011-05-04 21:53
check with my last commit, it should fix both shallpion and Sbte bugs (it's the same bug actually :P)

**Comment by pengshao** [comment] 2011-05-04 23:21
@arielj, thanks for the heads up. I just tried the latest git and I still have the problem Sbte described, or on my side, emesene doesn't play sound for the "first received message", which it did before yesterday. I have exactly the same error output as Sbte. Thanks :)

**Comment by arielj** [comment] 2011-05-05 00:01
you have to wait until someone merge my commit on emesene repo or pull from my repo

**Comment by Sbte** [comment] 2011-05-05 07:40
Pulled. @shallpion, try again.

**Comment by pengshao** [comment] 2011-05-06 04:10
Sorry for the late reply, I just returned from work. It works fine now! Thank you for correcting it so quick :) I close this issue. Thank you again.

**Comment by pengshao** [comment] 2011-11-12 01:05
I am sorry to reopen this ticket. I am still experiencing the similar, if not the same issue. I am currently using 2.11.10-devel and if I check both "play sound on first received message" and "play sound on received message", the old problem came back: emesene plays sound on the first received message, and if I open the conversation window, it won't play any sound in future no matter if the window is out of focus or in focus, unless I close it and wait for a new incoming message.

I tried to play around with these two check boxes and it seemed there was no way to let emesene2 to act like : play a sound only for the new incoming message, or when the existing window is out of focus, 

Thanks for taking care of it.

**Comment by Sbte** [comment] 2011-11-12 12:08
Is it better now? I just might have fixed something and I can't think of anything else. The only thing I could think of is that you're logged in as BUSY.

**Comment by pengshao** [comment] 2011-11-12 12:27
No it is still not working well, and I am very sure mu status is always available :(

Also I noticed that another weird problem again as before: if I check  "tabbed conversation", emesene will not play asound when a conversation window which is OUT of focus received the first incoming message, however, if I leave that window out of focus by not touching the message, emesene will play sounds for all the following incoming messages.

**Comment by Sbte** [comment] 2011-11-12 12:30
Maybe there's something wrong with the message_waiting property of the conversations then. I'll see if I find anything useful while someone's talking to me.

**Comment by pengshao** [comment] 2011-11-12 12:31
Thanks a lot for taking care of it :)

**Comment by Sbte** [comment] 2011-11-13 00:55
I think I just heard it too. My unity launcher extension worked though, so it's not a bug in the message_waiting property. I have no idea what's going on...

**Comment by pengshao** [comment] 2011-11-13 01:04
T_T

**Comment by Sbte** [comment] 2011-11-13 11:42
Found the issue. message_waiting is set after the sound is supposedly played.

**Closed as completed** 2011-11-13 11:52 UTC
Labels: bug

**Comment by pengshao** [comment] 2011-11-14 05:46
I just tested it, working perfectly. Thanks a lot :)
