### ISSUE TITLE
error in switchboard_manager.py

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#939] opened 2011-11-15 20:17 UTC
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 236, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 174, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError

**Comment by Sbte** [comment] 2011-11-15 20:24
@c10ud, you said this was fixed? See #593

**Comment by KinG-InFeT** [comment] 2011-11-15 20:36
i utilized 2.11.12-devel a few seconds ago

**Comment by Sbte** [comment] 2011-11-15 22:56
it would be awesome if you could reproduce this and get a full log of emesene -vvv. I really want to trace this error down. I already have one full log, but seeing what's common in two logs would really help.

**Comment by Sbte** [comment] 2011-11-15 23:16
I suppose checking for state == ProtocolState.OPEN in request_switchboard when reusing the switchboard might help. I currently think it's a race condition, where the switchboard is being closed (state CLOSING) and reused at the same time. @c10ud, what do you think?

**Comment by KinG-InFeT** [comment] 2011-11-16 14:42
When booting from urxvt emesene-2-vvv else save a log where all output? if you where?

**Comment by Sbte** [comment] 2011-11-17 20:56
What? I don't understand you...

If you mean where to put the output, just mail it to me directly or put it somewhere where I can download it. It's only useful if you happen to reproduce the error or have some lost messages.

**Comment by KinG-InFeT** [comment] 2011-11-17 23:28
Forgive my bad English.
I just wanted to know if the output of "emesene-vvv" was saved in some file

**Comment by Stiveknx** [comment] 2011-11-18 03:18
I didn't find the log file, but you can do this:

Create a log file
$ touch /var/log/emesene
Permissions
$ chmod 777 /var/log/emesene

than run emesene:
$ ./emesene -vvv 2&>> /var/log/emesene

**Comment by Sbte** [comment] 2011-11-18 06:28
Yes, that's what you should do more or less. We can't just save them automatically I think because they can contain personal information (email addresses and names).

You could also just run `emesene -vvv &> emesenelog.txt`.

**Comment by Stiveknx** [comment] 2011-11-18 10:31
If it's automatic that also would be a huuuuuuuge file ...

**Comment by KinG-InFeT** [comment] 2011-11-20 13:04
I understand perfectly, I will try to reproduce the error and give you the correct response in verbose.

**Comment by KinG-InFeT** [comment] 2011-11-20 18:24
emesene -vvv

[19:11:32 INFO papyon.protocol.switchboard_manager] Handler <SwitchboardP2PTransport peer="xxxxxx@hotmail.it" guid="None"> attached to switchboard 1646659714.224195178.21817583
Errors occurred while importing jabber backend: No module named xmpp
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 470, in _sb_message_received
    handler._on_message_received(message)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/switchboard.py", line 138, in _on_message_received
    self._on_chunk_received(peer, peer_guid, chunk)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 150, in _on_chunk_received
    self.__send_chunk(peer, peer_guid, ack_chunk)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 233, in __send_chunk
    self._send_chunk(peer, peer_guid, chunk)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/switchboard.py", line 109, in _send_chunk
    (self._on_message_error, peer, peer_guid, chunk))
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 108, in _send_message
    self._process_pending_queues()
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 236, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 174, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError
[19:11:32 INFO papyon.protocol.switchboard_manager] Requesting switchboard for participant(s) xxxxx@hotmail.it

---

is repeated many times:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 236, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 174, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError

---

If I give you the entire log veil, but is very long!

**Comment by Sbte** [comment] 2011-11-20 19:13
The errors are known, but not what happens before them. Please send the whole log to my email (svenb.linux@gmail.com).

**Comment by KinG-InFeT** [comment] 2011-11-21 21:04
email with complete log send, my email king.infet@gmail.com

**Comment by Sbte** [comment] 2011-11-21 21:15
Exactly what I thought:

[21:51:54 INFO papyon.protocol.switchboard_manager] Using already opened switchboard 1794309343.187120105.196182117

But I'm not sure whether we can also use switchboard with status != CLOSED | CLOSING. I think checking for those two will help for sure

**Comment by Sbte** [comment] 2011-11-21 23:19
Please test. Should be fixed by 16552b0175b96779b3360a7bf2f604e612df7520.

Also please keep logging everything just in case a different error happens. Then I can fix that immediately.

**Comment by KinG-InFeT** [comment] 2011-11-22 15:13
no feedback with the last commit more errors in the log (FIXED?)

**Comment by c10ud** [comment] 2011-11-25 10:29
i assume sbte's modifications fixed the issue, in case it persists, please reopen (or sbte will, because he's been annoyed by this too :))

**Closed as completed by c10ud** 2011-11-25 10:29 UTC

**Comment by gracegreen** [comment] 2011-12-07 03:06
I meet this issue with one of my msn account , but it never happen with my another msn account.

**Comment by KinG-InFeT** [comment] 2011-12-08 00:24
Sorry, but you better specify the error? preferably with a degub accurate? Would you help so much.
