### ISSUE TITLE
always crash  in Ubuntu 12.10

### ISSUE THREAD

**Issue by gracegreen** [emesene/emesene#1542] opened 2012-10-25 01:27 UTC
(gdb) bt
#0  0x00000000004b5c78 in ?? ()
#1  0x000000000048a56a in ?? ()
#2  0x00007ffff6360ffa in ?? () from /usr/lib/python2.7/dist-packages/glib/_glib.so
#3  0x00007ffff6087108 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff6089bc2 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff6089de8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff608a1e2 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff2b78c77 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#8  0x00007ffff32254d8 in ?? () from /usr/lib/python2.7/dist-packages/gtk-2.0/gtk/_gtk.so
#9  0x0000000000460654 in PyEval_EvalFrameEx ()
#10 0x00000000004602b7 in PyEval_EvalFrameEx ()
#11 0x00000000004602b7 in PyEval_EvalFrameEx ()
#12 0x0000000000467209 in PyEval_EvalCodeEx ()
#13 0x00000000004d0242 in PyEval_EvalCode ()
#14 0x00000000005102bb in ?? ()
#15 0x000000000044a466 in PyRun_FileExFlags ()
#16 0x000000000044a97a in PyRun_SimpleFileExFlags ()
#17 0x000000000044b6bc in Py_Main ()
#18 0x00007ffff6f0576d in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#19 0x00000000004ce0ad in _start ()

**Comment by Sbte** [comment] 2012-10-25 05:24
Duplicate of #1537

**Closed as completed by Sbte** 2012-10-25 05:24 UTC
