### ISSUE TITLE
Tabs in conversation windows

### ISSUE THREAD

**Issue by andreskru** [emesene/emesene#98] opened 2010-10-23 16:20 UTC
I don't like when I open several tabs, appear some arrows at the corners of the tab bar, its not "productive".

**Comment by marianoguerra** [comment] 2010-10-23 20:22
we have a really nice problem, we are using a custom widget to display the user nick on the tabs, that widget is really cool displaying emoticons and msn+, the problem is that it doesn't have ellipsize correctly implemented and our cairo wizzard seems to be retired.

that measn two things:
- to get this feature we can go back to straight labels and lose the cool effect on tabs
- or wait until someone implements ellipsize correctly in TabWidget

until then we will have that problem. In emesene 1 we are using labels, we could go back to that if this feature is more importante than the eye candy on tabs.

ideas?

**Comment by andreskru** [comment] 2010-10-23 20:50
I dont like do clicks in arrows to see if i have a new message. Go label...

**Comment by boyska** [comment] 2010-10-24 10:11
let's make a category, so everyone can choose his taste :D

**Comment by c10ud** [comment] 2010-10-24 14:27
iirc it's like this because _i_ liked mozilla-like tabs, not because ellipsing, i think it can be done easily

**Comment by andreskru** [comment] 2010-10-24 21:06
Chrome like tab behavior? i like that!

**Comment by c10ud** [comment] 2010-10-30 15:18
Revert tabs behaviour to good'ol emesene-1 like one.

This could please some users, fortunately we now have the 'b_conv_tab_mozilla_like' config value that if set to True someway will bring back mozilla-like fixed-width tabs. Closed by 9ad612e3cfdb7e08344bbf4c56002f4f0e5e6d0b

**Closed as completed** 2010-10-30 22:18 UTC
Labels: gtk, core

**Comment by edualberice** [comment] 2010-11-24 19:16
Isn't it possible to open new conversation in new windows? Sincerely I don't like to have all conversations in one windows, it's confusing.
Another thing I noticed is that there is no highlight on the label of the contact that sent the message. I lost some conversations because of this.

**Comment by marianoguerra** [comment] 2010-11-24 19:49
edualberice: this issue is closed and the issues you commented are both opened issues, you can comment on those.
