### ISSUE TITLE
Email problem

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#948] opened 2011-11-23 19:26 UTC
I use Emesene 2.11.11 on Windows XP SP3. When I clic on the Email botom, Emesene don´t open my email aconunt in Internet Explorer, or Mozilla Firefox or any other browser. My Windows XP is 32Bits. And I already reported this problem before in Emessene 2.11.7 and the problem was not resolved.

**Comment by Sbte** [comment] 2011-11-23 23:03
Duplicate of #947

**Closed as completed by Sbte** 2011-11-23 23:03 UTC
