### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by Alepou** [emesene/emesene#920] opened 2011-11-10 14:01 UTC
Starts with some problems ... login today, not login after after 1-2 hours ... all contacts was offline (but I sign in), or nobody was in privacy list ... And now, I am try to login many days and I can't. I use 1.5.1 ... 1.6.2 .... all versions of 2  ... nothing! I am behind windows 7, I try and windows xp ... I don't have linux ... maybe emesene not work with windows anymore?

**Comment by Sbte** [comment] 2011-11-10 14:02
Duplicate of #915

This should be fixed in the next release

**Closed as completed by Sbte** 2011-11-10 14:02 UTC

**Comment by Alepou** [comment] 2011-11-10 14:05
I prefer version 1.6.3 because version 2 has no plugins that I need (invisible ... ) Maybe this will fix too? 
thank you for the answer

**Comment by Sbte** [comment] 2011-11-10 14:09
No, we don't support 1.6.3 any more. You could try to port the plugins yourself, or ask the original author of the plugin if he could do it. You could also try to make a request for a certain plugin in one of the plugins repositories.

https://github.com/emesene/emesene-supported-plugins
https://github.com/emesene/emesene-community-plugins

Or you could of course wait until someone releases an unofficial version of emesene 1 that works for you.

**Comment by astagi** [comment] 2011-11-10 19:28
Try to read here
http://blog.emesene.org/2011/11/emesene-is-unable-to-connect.html

On Thu, Nov 10, 2011 at 3:01 PM, Aria
reply@reply.github.com
wrote:

> Starts with some problems ... login today, not login after after 1-2 hours ... all contacts was offline (but I sign in), or nobody was in privacy list ... And now, I am try to login many days and I can't. I use 1.5.1 ... 1.6.2 .... all versions of 2  ... nothing! I am behind windows 7, I try and windows xp ... I don't have linux ... maybe emesene not work with windows anymore?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/920

## 

/*

---
- Use the class below to talk with me *
  *********************************
  */

public class =.4ndrea.Stagi=
{
   public Blog = http://4spills.blogspot.com/ ;
   private Skype = andrea.stagi.2 ;
   private Gtalk = stagi.andrea ;
   private MSN = andreastagi<at>hotmail<dot>com ;
   public Twitter = 4ndreaSt4gi ;
   private Facebook = http://facebook.com/andrea.stagi ;
};

**Comment by Alepou** [comment] 2011-11-11 07:18
Hello 4ndrea, I saw this post, I try to do this ... I dont know about linux, I have windows, I downloaded this file, but I don't know how use it ... how can I run this script! 
Thank you for the answer

**Comment by astagi** [comment] 2011-11-13 23:09
Hi ^^ we made a new windows package, install it and problems will be fixed..

Windows installer: http://www.mediafire.com/?01uo2a3mcqiy44y
Windows portable (really portable): http://www.mediafire.com/?ozbx6olbv78zjvw

Windows portable note: use only portable.exe or portable_debug.exe, if
you change the exe's name it WON'T be portable anymore (you can use
whatever as exe name at least it ends with portable.exe or
portable_debug.exe)

Regards,

=.4.S.=

On Fri, Nov 11, 2011 at 8:18 AM, Sofia
reply@reply.github.com
wrote:

> Hello 4ndrea, I saw this post, I try to do this ... I dont know about linux, I have windows, I downloaded this file, but I don't know how use it ... how can I run this script!
> Thank you for the answer
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/920#issuecomment-2705597

## 

/*

---
- Use the class below to talk with me *
  *********************************
  */

public class =.4ndrea.Stagi=
{
   public Blog = http://4spills.blogspot.com/ ;
   private Skype = andrea.stagi.2 ;
   private Gtalk = stagi.andrea ;
   private MSN = andreastagi<at>hotmail<dot>com ;
   public Twitter = 4ndreaSt4gi ;
   private Facebook = http://facebook.com/andrea.stagi ;
};

**Comment by astagi** [comment] 2011-11-14 16:46
You can now download them from https://github.com/emesene/emesene/downloads#download_148653 too
