### ISSUE TITLE
Issue about resizing emoticons

### ISSUE THREAD

**Issue by sagitman** [emesene/emesene#982] opened 2012-01-10 16:57 UTC
Hi,
The emoticons resizing is actually working
but there is a small issue
the transparent space remained in the image after resizing
Here are the screenshots
http://s18.postimage.org/s8krojljt/bug.png
http://s17.postimage.org/feqe66zm7/viewer.png

Thank you!
and sorry for my poor English

**Comment by arielj** [comment] 2012-01-10 17:19
any step to reproduce it? like...

1-download this .png file
2-add it with any shortcut
3-bug
4-anything else

that would make it easier to debug, specially if we have the file that's being resized

**Comment by Sbte** [comment] 2012-01-10 17:45
Also, do you have imagemagick installed? If so what version?

**Comment by Sbte** [comment] 2012-01-10 18:05
@arielj, I looked at the code, and I was wondering why the resize function is in Cache.py and not EmoticonCache.py

**Comment by arielj** [comment] 2012-01-10 20:49
@Sbte, there's no reason, I guess I put it there because I didn't realize only EmoticonCache uses it, it can be moved.

**Comment by Sbte** [comment] 2012-01-10 20:53
another question: Why do we use imagemagick and not just the Image module? It's not like either of both is always present on every system, but since we're already using python, maybe the Image module is more reliable?

**Comment by Sbte** [comment] 2012-01-10 20:58
Sorry, just read the original thread again. Forget that question ^

**Comment by sagitman** [comment] 2012-01-11 07:02
Sorry for replying lately
I am using Arch Linux right now and my imagemagick verison is 6.7.4.0-1

Actually, it was a gif I made in Windows in the past (using Ulead GIF animator 5)
It is a fake animation gif for forcing Windows live Messenger to resize it as 50x50 emoticons

Here is the original image I made
http://s17.postimage.org/aydk7640v/original.gif
and this is the one Emesene resized
http://s17.postimage.org/an0p85cyn/resized.gif

and changes on shortcut name are getting the same result...

**Comment by Sbte** [comment] 2012-01-11 08:01
Works fine for me if I do:

`convert -resize '50x50>' 'original.gif' 'noriginal.gif'`

That doesn't work for you either?

**Comment by sagitman** [comment] 2012-01-11 08:18
No... i get the same image as the one Emesene resized
so is it imagemagick's bug?
I tried to reinstall the giflib and libnsgif but no help
Do I miss any packages that is required to install?

**Comment by Sbte** [comment] 2012-01-11 19:56
@sagitman, what version of imagemagick do you use?

**Comment by c10ud** [comment] 2012-01-12 11:32
@sbte last time i checked python's STL didn't have the ability to resize animated gifs so either trying with PIL or Imagemagick seemed a right choice

**Comment by sagitman** [comment] 2012-01-12 15:50
My imagemagick verison is 6.7.4.0-1

**Comment by Sbte** [comment] 2012-01-12 18:22
I have 6.6.0-4. Maybe it's a regression?

**Comment by Sbte** [comment] 2012-01-12 20:50
I guess `mogrify -resize '50x50>' 'original.gif'` won't work either? That will overwrite the original file.

**Comment by sagitman** [comment] 2012-01-13 03:48
I think I find the problem.
I tried 6.6.0-10 to resize gif image and it is working!
but the latest version 6.7.4-6 not.
It seems that they are still fixing it

I found this thread only which is rated to the problem from official changelogs
http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=19734

**Comment by Sbte** [comment] 2012-01-13 06:30
Ok then. Not an emesene bug, so closing.

**Closed as completed by Sbte** 2012-01-13 06:30 UTC
