### ISSUE TITLE
Qt4 while set conversation window type as Single window , will cause hang

### ISSUE THREAD

**Issue by shwangdev** [emesene/emesene#1488] opened 2012-08-28 08:29 UTC
While Set conversation window type as Single window in Gtk version before. 
And reopen Emesene in qt version , after closing a conversation window , it will hang , no response.

And other issue, I found that the Handle_Action_Set_Status function will call more than 5 times when I trigger status change.

**Comment by c10ud** [comment] 2012-08-28 09:50
don't use Qt frontend unless you fix it ;) is the set_status issue reproducible in gtk? are you sure you're not recursively calling it from the webqq or it's reproducible in other backends?

**Comment by shwangdev** [comment] 2012-08-28 10:35
_I remove the ~/.config/emesene2 whole folder, this issue can not be
reproduced..._

On Tue, Aug 28, 2012 at 5:50 PM, Riccardo notifications@github.com wrote:

> don't use Qt frontend unless you fix it ;) is the set_status issue
> reproducible in gtk? are you sure you're not recursively calling it from
> the webqq or it's reproducible in other backends?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/emesene/emesene/issues/1488#issuecomment-8086472.

## 

_Best Regards~_

_Xiang Wang_

_CDC, TrendMicro_

**Comment by shwangdev** [comment] 2012-08-28 10:37
_But anther issue occurred. *
*
*
*When create a new conversation window, you can not just close it._
*While click close, emesene will hang.
*
On Tue, Aug 28, 2012 at 6:35 PM, Xiang Wang wxjeacen@gmail.com wrote:

> _I remove the ~/.config/emesene2 whole folder, this issue can not be
> reproduced..._
> 
> On Tue, Aug 28, 2012 at 5:50 PM, Riccardo notifications@github.comwrote:
> 
> > don't use Qt frontend unless you fix it ;) is the set_status issue
> > reproducible in gtk? are you sure you're not recursively calling it from
> > the webqq or it's reproducible in other backends?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/emesene/emesene/issues/1488#issuecomment-8086472.
> 
> ## 
> 
> _Best Regards~_
> 
> _Xiang Wang_
> 
> _CDC, TrendMicro_

## 

_Best Regards~_

_Xiang Wang_

_CDC, TrendMicro_

**Comment by c10ud** [comment] 2012-08-28 10:50
During Qt4 window refactoring I've been aggressive with deletion, emesene sort of segfaults, pepeleproso will give it a look this week

**Comment by shwangdev** [comment] 2012-08-28 10:53
@c10ud  ok, Another question to ask u.

I can not find a button to change current status (online , busy, idle ect.) 
Each time login, it will call the _handle_action_set_status with parameter "offline".

Can u give me some information on this issue?

**Comment by c10ud** [comment] 2012-08-28 10:56
Don't use the Qt4 ui since it's not ready for daily use and development (it can trigger weird bugs)

The initial status is set from the Login window, there's a status button

**Comment by shwangdev** [comment] 2012-08-28 11:01
@c10ud , ok , But , no matter which status I choose on login window , the parameter is always "offline" for handle_action_set_status ...

**Comment by shwangdev** [comment] 2012-08-28 11:01
You mean , We can not change status even after login?

**Comment by Sbte** [comment] 2012-08-28 11:08
Maybe because it's not implemented. As @c10ud said, qt4 is full of bugs. Just implement it yourself, or else don't report bugs for qt. Once the qt4ui is ready for testing, we'll let you know.

**Comment by shwangdev** [comment] 2012-08-28 11:10
@Sbte , Got u , thanks.

**Comment by c10ud** [comment] 2012-08-28 11:32
After login you can change status through the main menu, the user panel
button and the eventual tray icon
If you don't see it it's probably because you didn't set the change status
capabilities in the Session?

2012/8/28 Xiang Wang notifications@github.com

**Comment by shwangdev** [comment] 2012-08-28 11:37
@c10ud , Got u, Thanks in a great deal. I finally found the root cause.

**Comment by Sbte** [comment] 2012-08-28 11:38
Ok, since the original issue is not reproducible, I'm closing this

**Closed as completed by Sbte** 2012-08-28 11:38 UTC
Labels: qt4
