### ISSUE TITLE
Preferences does not work after 2 times

### ISSUE THREAD

**Issue by gustavodeandrade** [emesene/emesene#181] opened 2010-11-08 23:31 UTC
Option - > Preferences . Don't work after open/close 2 times. Necessary reboot.

**Comment by Sbte** [comment] 2010-11-09 10:03
Confirmed. I had this too, but forgot to report

**Comment by flavioribeiro** [comment] 2010-11-09 21:11
It seems I fixed this bug adding one line at gui/gtkui/Preferences.py. 

Since it was just one line, i though that make a patch to be applied would be too burocratic. The diff is here http://pastebin.ca/1986710

**Comment by ghost** [comment] 2010-11-10 02:23
This patch works here!

**Comment by c10ud** [comment] 2010-11-10 17:03
closing, ty

**Closed as completed by c10ud** 2010-11-10 17:03 UTC
