### ISSUE TITLE
About dialog will not display

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#656] opened 2011-06-12 08:29 UTC
Traceback (most recent call last):
  File "/Users/Josh/emesene/Builds/Current/emesene2/emesene/emesene/gui/gtkui/MainMenu.py", line 236, in <lambda>
    lambda *args: self.handler.on_about_selected())
  File "/Applications/emesene.app/Contents/Resources/emesene/gui/base/Handler.py", line 186, in on_about_selected
    gui.theme.logo)
AttributeError: 'Theme' object has no attribute 'logo'

The about dialog will not open when clicked

emesene 2.11.6-devel
OS X Snow Leopard 10.6.7

**Comment by Sbte** [comment] 2011-06-12 09:02
I already fixed this last evening.

Closing as duplicate of #652

**Closed as completed by Sbte** 2011-06-12 09:02 UTC
