### ISSUE TITLE
do not leave the information on the message and nick saved

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1549] opened 2012-11-07 16:05 UTC
I updated the git version emesene and suddenly will not come out the information on my nick and my personal message saved

LOG: http://sprunge.us/BPhd

Screen: http://i.imgur.com/O5rhl.png

I tried to restart emesene several times, but the problem persists

emesene versione: last git 
OS: ArchLinux 32bit
Package: emesene2-git in AUR

**Comment by c10ud** [comment] 2012-11-07 16:42
Hello,
as errors say, this is a network issue (with SSL).
Please fix your network

2012/11/7 Vincenzo notifications@github.com

**Comment by KinG-InFeT** [comment] 2012-11-07 16:56
and why a 5 or 6 commits behind development everything works without any problems?

**Comment by c10ud** [comment] 2012-11-07 17:09
You tell me, no change in papyon since lots of time, feel free to find the
offending commit with git bisect

greets

2012/11/7 Vincenzo notifications@github.com

**Comment by KinG-InFeT** [comment] 2012-11-07 17:11
the problem is that I just updated emesene and commit very few, and I have not made ​​any network changes or something.

**Comment by Sbte** [comment] 2012-11-07 18:31
So try to do a git bisect to see where the problem lies.

**Comment by KinG-InFeT** [comment] 2012-11-07 19:41
I think they are committed by the Oct 08, 2012 onwards

**Comment by Sbte** [comment] 2012-11-07 19:47
Could you please just do a git bisect?

**Comment by Sbte** [comment] 2012-11-07 19:56
Maybe this commit: beae34b1f00981e90b3e7bc4b4d00dbc84a03c2c

Also, if that is the case, could you please try to attach a full log?

**Comment by c10ud** [comment] 2012-11-07 20:08
I doubt it, since the error is with login.live.com

2012/11/7 Sven Baars notifications@github.com

**Comment by KinG-InFeT** [comment] 2012-11-07 20:10
perhaps something central transition to the new mailbox Outlook Web?

**Comment by Sbte** [comment] 2012-12-30 13:18
Closing because of the lack of information provided

**Closed as completed by Sbte** 2012-12-30 13:18 UTC
Labels: incomplete

**Comment by KinG-InFeT** [comment] 2012-12-30 15:32
What other information should I give in addition to the log?

[17:04:41 ERROR root] Could not find any typelib for MessagingMenu
[17:06:05 WARNING papyon.service] Transport Error : Connection to login.live.com:443 (SSL TCP) failed: 
[17:06:05 WARNING papyon.service] Transport Error : Connection to login.live.com:443 (SSL TCP) failed: 
[17:06:05 ERROR papyon.service.content_roaming] Content Roaming service got error: Connection to login.live.com:443 (SSL TCP) failed: 
[17:06:05 ERROR papyon.service.content_roaming] Content Roaming service got error: Connection to login.live.com:443 (SSL TCP) failed: 
[17:06:05 ERROR papylib.Events] Client got an error: 5 Connection to login.live.com:443 (SSL TCP) failed: 
[17:06:05 ERROR papylib.Events] Client got an error: 5 Connection to login.live.com:443 (SSL TCP) failed:

**Comment by Sbte** [comment] 2012-12-30 15:35
A git bisect to see what commit caused this, as you stated that it works fine in previous versions. Since we can't reproduce this, it is the only way for us to find out what causes it.

**Comment by KinG-InFeT** [comment] 2012-12-30 15:39
must lose time which unfortunately I just ... as soon as I can find the problem I open a new issues.
