### ISSUE TITLE
'Nick Format Help' hidden behind preferecnces

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#739] opened 2011-07-21 17:50 UTC
In Preferences when you open up either 'Nick Format Help' or 'Group Format Help' , the windows are hidden behind Preferences. There is no way to get them on top of Preferences.

**Comment by Mystro256** [comment] 2011-07-26 15:14
Is this a recent regression? Because I'm not getting this, although I'm a bit out of date.

Also, is this OS specific?

**Comment by Sbte** [comment] 2011-07-26 15:25
Windows only issue I guess. Can't reproduce.

**Comment by ghost** [comment] 2011-07-26 15:31
Yea might be Windows only. I just updated to the latest commit (fd1ad845bd3cf30203edc039e23562574756cd33) and its still present.

**Comment by ghost** [comment] 2011-07-26 15:41
In Dialog, I changed the window type to WINDOW_TYPE_HINT_DIALOG and it now appears on top like it should.
Only problem now (what i can see at least) is that doing this makes the help window re-sizable when it probably shouldn't be.

On a side note, preferences is also re-sizable and probably shouldn't be.

**Comment by Mystro256** [comment] 2011-07-26 15:47
The issue with that is the window close button doesn't show on Gnome 3. I guess a close button could be added to the dialog, like the preference window.

EDIT, see 6a09cc8

**Comment by Mystro256** [comment] 2011-07-26 15:53
I think the dialog crashes on OSX, so it's probably a good idea to change it back to DIALOG and add a close button.

**Comment by Sbte** [comment] 2011-07-26 19:40
I think I read something about forcing a window to have a close button while leaving it a dialog, even on gnome3, but I forgot where...

**Comment by Mystro256** [comment] 2011-07-27 05:31
Oh really? That definitely should be implemented if someone figures it out.

Although if that can't be done for the hint dialog, there's also the option of just adding a button that closes on the somewhere in the dialog, like the preference window.

**Comment by Sbte** [comment] 2011-07-27 09:13
I don't know about gnome3, but maybe try setting 

dialog.set_property('deletable', True)

Not sure if it works.

**Comment by c10ud** [comment] 2011-07-27 13:07
we must fix once and for all this dialog weirdness: add buttons to MODAL windows etc. and of course don't use the HINT_MENU. can someone tell me where the problems are so we can put them in a list for brave devs?

**Comment by Mystro256** [comment] 2011-07-27 19:47
Well it seems like WINDOW_TYPE_HINT_MENU is the issue (on Windows and Mac), so after a quick string search, two instances are located:

<b><i>emesene/gui/gtkui/Dialog.py</b> line 222</i>
<b><i>emesene/gui/gtkui/ContactInformation.py</b> line 47</i>

So both need to be changed to WINDOW_TYPE_HINT_DIALOG and some way of closing the dialogs need to be added to both to work with gnome 3, ie close button or window close button if possible. I don't know anything about GTK bindings, so I'll let someone take care of it ;)

**Comment by Mystro256** [comment] 2011-07-27 19:51
Also, if WINDOW_TYPE_HINT_DIALOG is used, there needs to be a way to disable the resize for the window, unless this is the intended effect

**Comment by Sbte** [comment] 2011-07-27 22:18
That last thing is easy to do. Just override the internal method on the window used by all dialogs and add an if case.

Anyway, I want grome3 to test this (dialog close button), and a bug in ubuntu is prohibiting me from testing it in oneiric (x doesn't boot). If someone else case test it out, please do.

**Comment by Mystro256** [comment] 2011-07-27 23:04
Well, if you make a commit or tell me what to change, I can test it on my Arch install posthaste. I'm not what you call the best programmer but I'll do my best to help :)

**Comment by Sbte** [comment] 2011-07-28 11:37
Change the hint here 

https://github.com/emesene/emesene/blob/master/emesene/gui/gtkui/Dialog.py#L222

to

WINDOW_TYPE_HINT_DIALOG

and somewhere around here

https://github.com/emesene/emesene/blob/master/emesene/gui/gtkui/Dialog.py#L960

set

window.set_property('deletable', True)

See if the help dialogs have a close button.

**Comment by Mystro256** [comment] 2011-07-28 21:07
No good. It doesn't seem like that Dialog allows for a close button what so ever.

Although through some trial and error and a quick google search, perhaps It would be better to change all instances of WINDOW_TYPE_HINT_MENU and WINDOW_TYPE_HINT_DIALOG to WINDOW_TYPE_HINT_NORMAL?

I didn't find anything adverse using this method instead. Thoughts? Any reason this hasn't been used instead?

**Comment by Sbte** [comment] 2011-07-28 21:47
Because I think it acts like a main window (window buttons, task bar appearances, et al.). Also, most dialogs are actually dialogs.

**Comment by Mystro256** [comment] 2011-07-30 03:15
well I guess the two option are to make them main windows, which I would assume is non-preferred, or add a button. As well, I would assume the intention of the preference window is a dialog, not another main window?

Although in GNOME 3, you can right click the title bar and click close or use ALT+F4. So I guess there's also the third, lazy way by adding a message of "Close this windows by hitting ALT+F4, etc." at the bottom haha ;P

**Comment by c10ud** [comment] 2011-08-09 09:18
did we fix all this madness already? update me

**Comment by Sbte** [comment] 2011-08-09 09:26
No

**Comment by c10ud** [comment] 2011-08-09 09:35
do eet plz

**Comment by c10ud** [comment] 2011-08-17 21:29
ok no more _HINT_MENU 7510bed59388029fa28f84e100c4752f7a7f4d94

now report which dialogs are broken and we'll fix em

**Comment by c10ud** [comment] 2011-08-17 21:29
open new issues please

**Closed as completed by c10ud** 2011-08-17 21:29 UTC
Labels: easy, gtk, important, sʍopuıʍ
