### ISSUE TITLE
Conversation filled with blank lines

### ISSUE THREAD

**Issue by abranches** [emesene/emesene#483] opened 2011-05-01 18:30 UTC
If you or your contact sends a message with more than 3 lines and ending with a blank line, it will create a gap of blank lines in the conversation window.

It's self explanatory here: http://i.imgur.com/UuqXn.png

The size of that gap of blank lines is proportional with the number of lines of text on the message sent.

I noticed this bug when I did a copy of the text on a conversation window and send it. You can recreate that and see it by yourself.

**Comment by Sbte** [comment] 2011-05-01 18:36
Here it doesn't. Maybe that's a natty bug?

**Comment by abranches** [comment] 2011-05-01 18:45
Hmm, maybe.. I'm gonna try in a Ubuntu 10.10 that I have here with me.

**Comment by c10ud** [comment] 2011-05-01 18:46
i don't exactly get what's wrong in that screenshot :p

2011/5/1 abranches
reply@reply.github.com:

**Comment by abranches** [comment] 2011-05-01 18:51
eheh :p. i get your point, but notice the scrolling bar at the right? it's at the bottom, so it isn't a newly created window. that screenshot would only be "normal" if the scrolling bar hadn't appeared yet (it only happens when the text doesn't fill the entire window weight)

**Comment by Mystro256** [comment] 2011-05-01 20:02
@c10ud The blank gap between the 1 to 8 message to the bottom of the conversation space shouldn't be there, as abranches said, see the scroll bar on the right, it's allowing him to scroll lower than the available messages

**Comment by abranches** [comment] 2011-05-02 22:30
I've been investigating and I think this is a webkit problem. No python-webkit, but really webkit. I saved the html code of the conversation to a file, opened with google chrome(webkit) and the problem also appears. Tried with firefox(gecko) and there's nothing wrong with it.

If someone could try it, I appreciate it. http://www.sendspace.com/file/z1egvb . Just unzip, edit test.html and replace every occurrence of "file:///home/pedro/Área de Trabalho" with your path to the test folder. Then you open test.html with whatever browser you want and check if the problem is there or not

**Comment by abranches** [comment] 2011-05-02 22:46
Installed google-chrome in a fresh Ubuntu 10.04 and the bug also exists. Didn't try with 10.10

**Comment by c10ud** [comment] 2011-05-03 09:01
right, happened in chromium11 also (ubuntu10.04) but with ff4 is ok. seems like a bug (feature?) in newer versions of webkit then

**Comment by arielj** [comment] 2011-05-08 00:01
If it's a webkit problem, shouldn't we close this issue?

**Comment by abranches** [comment] 2011-05-08 02:44
i will search for the bug in webkit bug tracker, install latest version and so on to see if it's fixed. I it's not, then I'll fill in a new bug report to webkit devs. don't know if you wanna keep this opened or not. it would just be to update you guys when I have some news.

**Comment by Sbte** [comment] 2011-05-08 07:29
Just keep it open so you can update us on the status. Also, if it's not a bug but a feature, we should still fix it.

**Comment by abranches** [comment] 2011-05-08 12:14
while this is not solved, a simple message.rstrip() would be enough

**Closed as completed** 2011-05-08 14:49 UTC
Labels: AdiumTextBox, bug
