### ISSUE TITLE
Emoicons with shorter shortcuts have an higher priority than those with longer ones

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#377] opened 2011-04-08 23:19 UTC
When you send an emoticon whose shortcut contains the exact character combination than another icon, the one with the shortest string overrides the second one.
For instance, ">:(" interfers with ":(" , the later would override the former, resulting in a simple sad face. And it does that even on my contact's emoticons,  which is pretty annoying considering that emesene is the only messaging client I know that does that.

Expected behaviour:
Emesene should parse for emoticons with longer shortcuts first, and only then look for these with a shorter one.

**Comment by Sbte** [comment] 2011-04-09 08:30
The < and > are replaced by irreplacable tags. It's not the length of the emote name. Looking in to this right now ;)

**Comment by Sbte** [comment] 2011-04-09 08:37
Ok, fixed in my local branch. I just want to know first why the code I just removed to get it to work was even there.

**Comment by Sbte** [comment] 2011-04-09 09:01
Actually, duplicate of #335.

**Closed as completed by Sbte** 2011-04-09 09:01 UTC
