### ISSUE TITLE
Can't see my contacts' avatars

### ISSUE THREAD

**Issue by fgoujeon** [emesene/emesene#308] opened 2011-02-11 07:31 UTC
I can't see my contacts' avatars, neither in the contact list nor in the conversation window, though I can see mine.
Is there another Python lib needed for this?

**Comment by Sbte** [comment] 2011-02-11 09:24
I think new avatars don't get downloaded any more. But I can't really find where this problem comes from. Dupe of #299 ?

**Comment by fgoujeon** [comment] 2011-02-11 09:48
Since I'm a new emesene 2 user, my cache is still empty, so new avatars are indeed not downloaded anymore… or at least not displayed. Do you want me to check with Wireshark ?
My bug report and #299 are indeed related.

**Comment by Sbte** [comment] 2011-02-11 09:55
Someone probably just broke the code that downloaded them, and papyon has the right link to the right avatar if you look in the terminal, so I don't think Wireshack will help here. 

I'll try to do a regression test later today. Maybe if you could do one that would be even better. As soon as avatars start appearing, you'll know it works in that version. Then you could deleted your .config/emesene2 directory (back it up if there's important stuff in there) and try again with the next version git bisect picks for you.

**Comment by c10ud** [comment] 2011-02-11 11:23
seems like it's not working with clients < msnp18 which use the old p2pv1 (e.g. stock amsn in ubuntu10.04)
e.g. try opening two emesene2 and try changing the dp, it works.

otherwise you get:
(12:21:19) papyon.msnp2p.transport.switchboard:Invalid TLP chunk in SB message: TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 3d 4c 0a 00 00 00 00 00 00 00 00 00
c9 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
64 c7 91 68 a9 49 84 48 c9 02 00 00 00 00 00 00

i think papyon's being too restrictive or something else is broken in there, noone touched emesene2's code

**Comment by Sbte** [comment] 2011-02-11 19:37
Exactly that. Maybe it's since papyon 0.5.4 then? Because it worked for me until recently.

**Comment by c10ud** [comment] 2011-02-12 15:35
we really need to ask papyon devs. of course if we can reach them :D

note: if everyone is being forced to p2pv2 this should disappear soon, but i think webservices, macs and strange clients will retain compatibility..microsoft forces to update only desktops :(

**Comment by Sbte** [comment] 2011-02-25 19:51
I do see the right avatars for most people if I start with a clean .config/emesene2 directory (tried it on a different pc). Do we also blame this on papyon?

**Comment by c10ud** [comment] 2011-02-26 13:24
are you seeing correct avatars even for contacts which have a bad avatar in your "main emesene"?

**Comment by Sbte** [comment] 2011-02-26 13:31
Yes

**Comment by c10ud** [comment] 2011-02-26 13:42
mmm interesting. i guess we should try cleaning the entirely avatar cache dir and see what happens.. maybe there're cache hits for invalid avatars..?

**Comment by Sbte** [comment] 2011-02-26 13:43
Well, at least for one person I know he is using an avatar he has used before (so it is also in the avatar dir). Maybe that's the problem?

**Comment by c10ud** [comment] 2011-02-26 13:50
i tried removing the entire cache for every contact i had, but i came up with the same avatars..maybe this could be related to some old version of emesene keeping a bad cache or something like that?

**Comment by Sbte** [comment] 2011-02-26 13:53
You means a cache of an old version of emesene on your pc? Can emesene 2 interact with that?

**Comment by c10ud** [comment] 2011-02-26 14:04
nope, i mean an older version of emesene2

**Comment by c10ud** [comment] 2011-03-26 18:40
see https://bugs.freedesktop.org/show_bug.cgi?id=35702

**Closed as completed by c10ud** 2011-03-26 18:40 UTC
Labels: papyon
