### ISSUE TITLE
Copy & paste in windows

### ISSUE THREAD

**Issue by MrMartijn** [emesene/emesene#792] opened 2011-08-21 15:41 UTC
In emesene 2.11.7 I can't copy text from the chat windows.

**Comment by c10ud** [comment] 2011-08-21 16:38
CTRL+C/V works fine here -- please be more descriptive: which OS? adium output or plain text? how are you trying to copypaste?

**Comment by MrMartijn** [comment] 2011-08-21 16:42
I'm using Windows 7 x64
Adium output
Ctrl+C is not working. The context menu doesn't have a copy option.

**Comment by shuhaowu** [comment] 2011-08-28 00:59
I'm not familiar to the Windows installation, but I DO know for a fact that some GTK installations are faulty such that they prevent copying to application that's not using the same GTK library.

Try copy something from the chat window to the chatbox within emesene

**Comment by MrMartijn** [comment] 2011-08-28 01:01
I can copy within emesene. not to windows notepad.

**Comment by shuhaowu** [comment] 2011-08-28 01:04
Exactly. What GTK installation are you using?

**Comment by MrMartijn** [comment] 2011-08-28 01:04
where can I find that?

**Comment by shuhaowu** [comment] 2011-08-28 01:13
Given the fact that you don't know (as you probably never installed a GTK bundle by yourself), it's probably the GTK version bundled with emesene.

Is your Windows 7 64 or 32 bit?

**Comment by MrMartijn** [comment] 2011-08-28 01:37
I've got Win7 x64 (listed in the 3rd comment)

**Comment by c10ud** [comment] 2011-08-28 09:02
ah, that could be some gtk error then, and i don't think we can do anything..

**Comment by shuhaowu** [comment] 2011-08-28 15:52
Some GTK installation doesn't have the problem. Perhaps we should find those..

**Comment by Mystro256** [comment] 2011-08-28 20:40
On a side note... was copy ever implemented in the right click menu? Because I've only had select all and clear. Maybe it could be implemented as a fix for scenarios/cases like this.

**Comment by c10ud** [comment] 2011-08-28 20:58
not in adium, we need to hax the webkit view because the rightclick
menu is built-in -- also i don't even know if we can do it (?)

2011/8/28 Mystro256
reply@reply.github.com:

**Comment by Mystro256** [comment] 2011-08-28 21:12
Well it most likely can be done, but getting someone that has the time and interest to figure it out is another ;)

**Comment by arielj** [comment] 2011-09-04 01:38
Here, testing on windows, 32bits ctrl+c works, but there's no copy option on the right click menu.

I think there were copy/paste items in the menu before though

**Comment by shuhaowu** [comment] 2011-09-04 02:40
It's the 64bit. I had the same issue with pidgin on Win 7 x64.

Also does this mean we need to implement the right click copy/paste?

**Comment by arielj** [comment] 2011-09-04 22:42
I don't thinks so, it's a regression, so it's already there, the problem is the code that remove some unused button, it's removing the copy/paste buttons too an it shouldn't.

**Comment by arielj** [comment] 2011-09-05 11:52
can you try with latest git?

**Comment by arielj** [comment] 2011-09-08 00:00
@MrMartijn, can you try latest git? I've reenabled the copy option on the right click menu, I just need to know it works on your x64 system to close this issue (the ctrl+c part is a gtk 64bits error)

**Comment by MrMartijn** [comment] 2011-09-08 00:49
I've got the last git running, but ctrl+c doesn't work and the context menu also doen't work.

**Comment by shuhaowu** [comment] 2011-09-08 02:32
I'm pretty sure this is a GTK issue. I tried copy via context menu in pidgin before as well when I ran Win x64.

**Comment by c10ud** [comment] 2011-09-08 08:34
oh well, that is why i'd like to keep code-specific issues here and not packaging's :)

**Comment by arielj** [comment] 2011-09-22 12:01
So, this is an issue in pygtk/gtk 64bits or Windows, we can't do anything about it. It's supposed to be fixed on pygtk 2.4.5

https://bugzilla.gnome.org/show_bug.cgi?id=653995

**Closed as completed by arielj** 2011-09-22 12:01 UTC
Labels: sʍopuıʍ
