### ISSUE TITLE
Messege Sent cannot be received

### ISSUE THREAD

**Issue by spyalert01** [emesene/emesene#671] opened 2011-06-18 01:25 UTC
I am new here, I have just installed my Ubuntu11.04, 
I found a strange problem, I tried send message to a friend, and the message was not received by the friend. But she can send message to me, and I can received without problem, but when I try to reply again, she can't received it.
I tried using emesene, amsn, and empathy all problem persists, I even tried to Completely remove all of them, and gwibber as well, but problem still persist.
When I logged on to MSN using browser, and chat to the user, I don't have any problem, when I tried to run MSN Messenger from VirtualBox, I can also chat with the user without problem.
Is there any hidden file in Ubuntu that blocked me from doing this?
Please help.

**Comment by Sbte** [comment] 2011-06-18 09:51
What does the person you're trying to send messages to use? If it's MSN for OSX, read this: #511

**Comment by c10ud** [comment] 2011-06-18 14:52
also, since this is not an emesene specific issue, probably this is
not the best place to ask.. the only thing i can think of is what
@Sbte said. If you try with pidgin and it works, it's definitely what
Sbte said

2011/6/18 spyalert01
reply@reply.github.com:

**Comment by spyalert01** [comment] 2011-06-18 16:20
@c10ud and @Sbte
I have just installed emesene 2.11.5, I will try on monday. if it doesn't work, I will try with Pidgin. But what did @sbte said about pidgin? I went to #511 but I don't see anything about pidgin...

**Comment by Sbte** [comment] 2011-06-18 16:54
emesene and empathy both use papyon. If it works with pidgin, but not with those two, the problem is in papyon.

**Comment by spyalert01** [comment] 2011-06-18 17:08
I see. For my case, aMSN also not working, I can received from her, but she can't receive my message, when I tried using aMSN as well, does aMSN also use papyon?

**Comment by c10ud** [comment] 2011-06-19 16:36
no, but they could suffer of the same problem. can you ask your buddy if the client is really MAC messenger? so we can close this as a duplicate of #511

**Comment by spyalert01** [comment] 2011-06-20 04:12
Pidgin is working. I can send and receive from her now.
So this is really papyon issue? Anybody is wokring on this?

**Comment by Mystro256** [comment] 2011-06-21 14:45
@spyalert01

As @c10ud said, what client is your friend using? Providing this information can help fix it.

**Comment by handelcamilo** [comment] 2011-07-21 02:53
Hi, I had the same issue with Emesene2. I send my messages but the person in the other side can't receive it!
My OS is Ubuntu 11.04 and my friends OS is windows!

Thank you!
ps: sorry about my english.

**Comment by c10ud** [comment] 2011-08-01 11:07
closing: incomplete

**Closed as completed by c10ud** 2011-08-01 11:07 UTC
