### ISSUE TITLE
when someone talk, the tab comes over the actual tab on focus

### ISSUE THREAD

**Issue by DragaO** [emesene/emesene#114] opened 2010-10-26 13:20 UTC
i was talking with someone on a tab and, when i was writing a message, another people (which wasn't talking with me at this moment) said something. this new tab gained focus and the rest of the text i was writing goes to this new tab

steps to reproduce:

1 - open a window with someone
2 - wait for another people start a conversation

my system :
Python 2.6.4
Fedora 13 i686
kernel 2.6.34.7-61.fc13.i686.PAE

**Comment by c10ud** [comment] 2010-10-27 16:07
confirmed, when a new tab opens, it steals focus

**Comment by arielj** [comment] 2010-11-07 03:14
I guess it's caused by line 510 of emesene.py

> self.conversations.set_current_page(conversation.tab_index)

it sets the new conversation as the current tab, can't we just remove that? is it necessary?

also, line 513 looks like another focus-stealer line

> self.conversations.get_parent().present()

I think we can remove both, but I was not the one that put them there so I don't know

**Comment by c10ud** [comment] 2010-11-07 11:03
neither do i, just remove them, test and see what happens....hax it! lol (i'm in a hurry so i can't do it myself right now) if it works, push :D

**Comment by arielj** [comment] 2010-11-07 18:15
ok, done, it seems to work, but more testing is welcomed :P

**Comment by arielj** [comment] 2010-11-07 18:29
New conversations don't steal focus of current conversation. Closed by 898c2c02ff8d78a4f56cdd6c6ce237373b2b9841

**Comment by c10ud** [comment] 2010-11-07 18:43
found the issue: it's not raising focus when we start the conversation (e.g. clicking on the contact list)

**Comment by c10ud** [comment] 2010-11-07 19:37
ok now it should be ok

**Closed as completed** 2010-11-08 02:29 UTC
Labels: gtk, core

**Comment by edualberice** [comment] 2010-11-24 19:19
What version is this one that doesn't steal focus? I downloaded yesterday the emesene 2.0 from github and mine is stealing focus.
