### ISSUE TITLE
sudden reconnection and reconnection ... login infinite(login mad ....)

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1534] opened 2012-10-04 16:59 UTC
just connected to msn ... suddenly breaks the connection and tries to reconnect ... but it goes on and on ....

Complete LOG: http://sprunge.us/KNKT

**Comment by pepeleproso** [comment] 2012-10-08 22:50
are you sure this isn't network problems?

**Comment by Sbte** [comment] 2012-10-09 06:56
@pepeleproso probably, but there's a real error in the log.

**Comment by pepeleproso** [comment] 2012-10-09 14:09
seems we don't disconnect an extension change notification on reconnect, but here that notification is properly disconnected

**Comment by KinG-InFeT** [comment] 2012-10-09 16:48
@pepeleproso no, no network error

**Comment by KinG-InFeT** [comment] 2012-10-09 19:01
other LOG: http://sprunge.us/jdME

**Comment by KinG-InFeT** [comment] 2012-10-14 19:10
other LOG: http://sprunge.us/QBdS

**Comment by Sbte** [comment] 2012-10-14 20:23
As we've seen before with your system, your DBus seems to be messed up. I'm not sure if those errors are a mistake on our end. 

For the other issue, it's probably the same as #1536. You open your hotmail, and then weird stuff starts to happen. Maybe you could try an earlier version of emesene and a git bisect if needed to see if that's a regression on our end or just Microsoft messing with us.

**Comment by KinG-InFeT** [comment] 2012-10-16 17:33
NO! connect or not connect?
LOG: http://sprunge.us/ObaO
Screen: http://i.imgur.com/JVWN2.png

why???????????????
single window problem? possible?

**Comment by Sbte** [comment] 2012-10-16 17:40
Yes, closing as a duplicate of #1536

**Closed as completed by Sbte** 2012-10-16 17:40 UTC

**Comment by c10ud** [comment] 2012-10-16 18:18
DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect
to socket /run/dbus/system_bus_socket: File o directory non esistente

means your dbus install is messed up

[19:30:20 WARNING papyon.service] Transport Error : Connection to
login.live.com:443 (SSL TCP) failed:
[19:30:20 ERROR papyon.service.content_roaming] Content Roaming service got
error: Connection to login.live.com:443 (SSL TCP) failed:
[19:30:20 ERROR papylib.Events] Client got an error: 5 Connection to
login.live.com:443 (SSL TCP) failed:

means you cannot connect to login.live.com:443 because your network is
messed up, it cannot connect over SSL, or some other error

[19:35:46 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server
Error) from local-sn-people.directory.live.com:443

means the server rejected you, most probably due to the previous errors

2012/10/16 Vincenzo notifications@github.com
