### ISSUE TITLE
IdentationError

### ISSUE THREAD

**Issue by kirotawa** [emesene/emesene#348] opened 2011-03-18 12:02 UTC
Today while I  tried run emesene (like a tester) gotta this bug message:

Traceback (most recent call last):
  File "./emesene", line 30, in <module>
    from emesene import emesene
  File "/home/kirotawa/Desenvolvimento/emesene/emesene/emesene.py", line 22, in <module>
    from e3.common.utils import project_path
  File "/home/kirotawa/Desenvolvimento/emesene/emesene/e3/**init**.py", line 1, in <module>
    from base import *
  File "/home/kirotawa/Desenvolvimento/emesene/emesene/e3/base/**init**.py", line 24, in <module>
    from Worker import Worker
  File "/home/kirotawa/Desenvolvimento/emesene/emesene/e3/base/Worker.py", line 25, in <module>
    import Logger
  File "/home/kirotawa/Desenvolvimento/emesene/emesene/e3/base/Logger.py", line 559
    <<<<<<< HEAD
    ^
IndentationError: expected an indented block

**Comment by marianoguerra** [comment] 2011-03-18 12:06
you have a conflict on your repo, try fixing the conflict or checkout the repo again.

closing, this is not a bug.

**Closed as completed by marianoguerra** 2011-03-18 12:06 UTC
