### ISSUE TITLE
[ERROR] Send/Received Files (DEBUG)

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#973] opened 2011-12-31 14:20 UTC
I use emesene git version (31/12/2011) on Gentoo Linux.

If I send a file, this file or get empty, or not at right. This happens with emesene client and another client on the other side.

But with both clients emesene happens that if I send the request arrives, but I can not accept the transfer.

Here is my DEBUG (Only errors):
[14:53:52 INFO papyon.protocol.switchboard_manager] Using already requested switchboard for same contacts
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/Worker.py", line 135, in run
    self._process_action(action)
  File "/usr/lib/python2.7/site-packages/emesene/e3/base/Worker.py", line 183, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/Worker.py", line 1387, in _handle_action_send_message
    papyconversation.send_text_message(msg)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/conversation.py", line 337, in send_text_message
    self._send_message_ex(content_type, body, headers, callback)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/conversation.py", line 365, in _send_message_ex
    return self._send_message(message, callback, errback)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/conversation.py", line 491, in _send_message
    callback=callback, errback=errback)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 108, in _send_message
    self._process_pending_queues()
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 174, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError

AND

[14:52:53 INFO papyon.protocol.switchboard_manager] Handler <SwitchboardP2PTransport peer="ToboeWR@live.it" guid="8ffc5470-37eb-47bc-aae6-96728b6d2116"> attached to switchboard 719098375
/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/switchboard_manager.py:227: Warning: gsignal.c:2392: instance `0xa968460' has no handler with id`9245'
  contact.disconnect(handle)

Complete LOG: http://hotfile.com/dl/139196963/5881981/debug.html

**Comment by Sbte** [comment] 2011-12-31 14:46
Relevant part of the debug before the assertion error:

```
[14:53:52 INFO papyon.msnp2p.transport] Transport is not ready to send, bail out
[14:53:52 DEBUG papyon.transport] <<< NAK 1
[14:53:52 INFO papyon.msnp2p.transport.switchboard] Received error: 1 (type=4)
[14:53:52 INFO papyon.msnp2p.transport] Unregistering transport <SwitchboardP2PTransport peer="first_contact@live.it" guid="0868f99b-de6b-4f36-be09-57d0cab15f8c">
[14:53:52 INFO papyon.protocol.switchboard_manager] Closing switchboard handler <SwitchboardP2PTransport peer="first_contact@live.it" guid="0868f99b-de6b-4f36-be09-57d0cab15f8c">
[14:53:52 INFO papyon.protocol.switchboard] Leaving switchboard 537281008
[14:53:52 DEBUG papyon.transport] >>> OUT
[14:53:52 DEBUG papyon.transport] <<< NAK 2
[14:53:52 DEBUG papyon.transport] <<< NAK 3
[14:53:52 DEBUG papyon.transport] <<< NAK 4
[14:53:52 DEBUG papyon.transport] <<< NAK 3
[14:53:52 INFO papyon.msnp2p.transport.switchboard] Received error: 1 (type=4)
[14:53:52 INFO papyon.msnp2p.transport] Unregistering transport <SwitchboardP2PTransport peer="second_contact@hotmail.it" guid="None">
[14:53:52 INFO papyon.protocol.switchboard_manager] Closing switchboard handler <SwitchboardP2PTransport peer="second_contact@hotmail.it" guid="None">
[14:53:52 INFO papyon.protocol.switchboard] Leaving switchboard 485326421.934247.2251985
[14:53:52 DEBUG papyon.transport] >>> OUT
[14:53:52 INFO papyon.protocol.switchboard_manager] Requesting switchboard for participant(s) first_contact@live.it
[14:53:52 INFO papyon.protocol.switchboard_manager] Using orphaned switchboard 537281008
[14:53:52 INFO papyon.protocol.switchboard_manager] Handler <SwitchboardConversation participants="first_contact@live.it"> attached to switchboard 537281008
[14:53:52 INFO papyon.protocol.switchboard_manager] Requesting switchboard for participant(s) first_contact@live.it
[14:53:52 INFO papyon.protocol.switchboard_manager] Using already requested switchboard for same contacts
```

I replaced the email addresses of the contacts

**Comment by Sbte** [comment] 2011-12-31 14:51
@c10ud, maybe we should replace all instances of 

```
if handler_participants == switchboard_participants:
```

in papyon with

```
if handler_participants == switchboard_participants and \
   (switchboard.state == msnp.ProtocolState.OPEN or \
    switchboard.state == msnp.ProtocolState.OPENING):
```

What do you think?

**Comment by Sbte** [comment] 2011-12-31 15:01
@KinG-InFeT uploaded a possible fix to my own fork for you to try out:

https://github.com/Sbte/emesene/commit/bffda4baecdbb5cfb7e7bb9f0b599c4974175839

**Comment by c10ud** [comment] 2012-01-01 18:35
@Sbte your fix could work

but NAKs could also mean something else not in our control, just sayin
other than that, i'm cool with your hack

**Comment by Sbte** [comment] 2012-01-01 18:38
Should be fixed by 950607e8d3cc5ab19bf3f057b1a0dede43fa97a3

**Comment by KinG-InFeT** [comment] 2012-01-01 22:43
solved the traceback but the file was not sent! I can not neither send nor to accept a file.

**Comment by Sbte** [comment] 2012-01-01 22:44
Can you give us a new -vvv log?

**Comment by KinG-InFeT** [comment] 2012-01-02 21:14
complete log: http://hotfile.com/dl/139591758/b21889e/emesene.html

**Comment by KinG-InFeT** [comment] 2012-01-02 22:03
complete log of the client, perhaps it can be useful.
http://hotfile.com/dl/139598335/f142430/emesene.html

**Comment by KinG-InFeT** [comment] 2012-01-04 02:21
At the end of the file transfer does NOT WORK!

**Comment by Sbte** [comment] 2012-01-04 09:11
The log was removed

**Comment by KinG-InFeT** [comment] 2012-01-04 14:04
File transfer is successful in emesene (I) and the other aMSN but not read the file after send.

My Log: http://hotfile.com/dl/139898291/1be162a/emesene.html

**Comment by Sbte** [comment] 2012-01-04 14:07
What do you mean? That the file is corrupt?

**Comment by KinG-InFeT** [comment] 2012-01-04 14:26
so it seems
I sent an email to sven

**Comment by Sbte** [comment] 2012-01-04 21:37
Ok, so all your attempts to file transfers give a NAK to both you and your contact...

@c10ud, he's using Gentoo^. I guess that could be why? Should we just close this as a Gentooism?

**Comment by Sbte** [comment] 2012-01-04 21:48
@KinG-InFeT, can you do file transfers with other clients than emesene with the same account you used for the above logs? If that works all the time then it could be a papyon problem, but I don't think it is. Maybe you blocked p2p from your OS or maybe MS blocked you from their server due to illegal practices, who knows...

**Comment by KinG-InFeT** [comment] 2012-01-06 01:21
As I said before the transfer takes place with amsn but the files get corrupted.

**Comment by Sbte** [comment] 2012-01-06 10:20
I mean this:

emesene -> emesene
amsn -> emesene
emesene -> amsn
amsn -> amsn

What happens for all of those setups? If it doesn't work for any of those, then your account is probably banned or something. I don't know.

**Comment by c10ud** [comment] 2012-01-06 11:03
i'd say since papyon has the best p2p implementation around so far, it
could be amsn's fault.  bugs needs to be checked against wlm

2012/1/6 Sven reply@reply.github.com:

**Comment by KinG-InFeT** [comment] 2012-01-06 13:17
Will try to test with various clients and I will make a ladder like this:

emesene -> WLM
WLM -> emesene

Same thing with aMSN, Pidgin, I would say are the most used and see what happens, and you have a log for each test ;)

**Comment by KinG-InFeT** [comment] 2012-01-06 15:05
Tested emesene -> pidgin

emesene on windows XP
pidgin on windows vista

and file transfer works without problems.

**Comment by Sbte** [comment] 2012-01-15 14:53
Any news on this? I still don't see a complete list :P

**Comment by KinG-InFeT** [comment] 2012-01-16 13:30
You forgive me, but I had problems with my hard drive, and I'm restoring things altarpieces. (I have not forgotten about this bug quiet :D )

**Comment by KinG-InFeT** [comment] 2012-01-16 20:26
else is the classic problem that I can not accept the file .... basically I can only cancel the transfer.

**Comment by Sbte** [comment] 2012-01-16 20:31
If you can give us a way to reproduce that, please do.

**Comment by KinG-InFeT** [comment] 2012-01-16 21:51
simply anyone who sends me a file, I can not accept it.

**Comment by AlineFreitas** [comment] 2012-01-16 22:08
I've been experiencing the same bug here, ever since I upgraded to emesene 2.\* I don't know how to help you to understand what's going on, so I ask now: What should I do help you identify what's going on?

**Comment by Sbte** [comment] 2012-01-16 22:51
Well, I simply can't reproduce it. Having a way to reproduce it that always works would help.

**Comment by KinG-InFeT** [comment] 2012-01-17 20:03
Apparently not just me having this kind of problem ... and you do not understand how to fix this bug, the thing is too strange.

**Comment by KinG-InFeT** [comment] 2012-01-28 16:27
@AlineFreitas, what OS are you using?

**Comment by AlineFreitas** [comment] 2012-01-30 04:20
Ubuntu Linux 11.10 Problem is, sometimes transfere works, sometimes it doesn't.. And I don't see a pattern to distinguish. That's just.. Awkward

**Comment by KinG-InFeT** [comment] 2012-01-30 16:42
Perhaps this problem does not affect those who use Ubuntu as both systems of communication ... but when it affects the operating systems are as diverse as ubuntu -> gentoo

**Comment by Stiveknx** [comment] 2012-02-29 20:23
I received the file, but didn't get here, I only saw in notification, not the option to cancel/approve the transfer

My emesene version: latest github version
Friend's msn: WLM 2011
Error:
`(17:14:21) papyon.msnp2p.session_manager:No handler could handle euf-guid {41D3E74E-04A2-4B37-96F8-08ACDB610874}`

Info:
`(17:14:21) papyon.msnp2p.transport:Registering transport <SwitchboardP2PTransport peer="kaio1337@hotmail.com" guid="eb260dd0-6237-48a0-8c2e-32ffa7bba79d">
(17:14:21) papyon.protocol.switchboard_manager:Handler <SwitchboardP2PTransport peer="kaio1337@hotmail.com" guid="eb260dd0-6237-48a0-8c2e-32ffa7bba79d"> attached to switchboard 2049844848.191179181.7640118
(17:14:21) papyon.msnp2p.session_manager:No handler could handle euf-guid {41D3E74E-04A2-4B37-96F8-08ACDB610874}
(17:14:21) papyon.msnp2p.transport:Received transport request from kaio1337@hotmail.com;{eb260dd0-6237-48a0-8c2e-32ffa7bba79d}`

Debug:

``````
(17:14:21) papyon.transport:<<< MSG kaio1337@hotmail.com Kaio 118
    TypingUser: 'kaio1337@hotmail.com'\r\n
    Content-Type: 'text/x-msmsgscontrol'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    \r\n
(17:14:21) papyon.transport:<<< MSG kaio1337@hotmail.com Kaio 253
    P2P-Src: 'kaio1337@hotmail.com;{eb260dd0-6237-48a0-8c2e-32ffa7bba79d}'\r\n
    P2P-Dest: 'andre-stein@hotmail.com;{b75d3405-f2bb-4a0b-98a8-43e522811ea0}'\r\n
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    [P2P message (601 bytes)]
(17:14:21) papyon.msnp2p.transport:Registering transport <SwitchboardP2PTransport peer="kaio1337@hotmail.com" guid="eb260dd0-6237-48a0-8c2e-32ffa7bba79d">
(17:14:21) papyon.protocol.switchboard_manager:Handler <SwitchboardP2PTransport peer="kaio1337@hotmail.com" guid="eb260dd0-6237-48a0-8c2e-32ffa7bba79d"> attached to switchboard 2049844848.191179181.7640118
(17:14:21) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0xfe3f833d: blob 0, RAK, SYN, SLP Message
    INVITE MSNMSGR:andre-stein@hotmail.com;{b75d3405-f2bb-4a0b-98a8-43e522811ea0} MSNSLP/1.0\r\n
    To: <msnmsgr:andre-stein@hotmail.com;{b75d3405-f2bb-4a0b-98a8-43e522811ea0}>\r\n
    From: <msnmsgr:kaio1337@hotmail.com;{eb260dd0-6237-48a0-8c2e-32ffa7bba79d}>\r\n
    Via: MSNSLP/1.0/TLP ;branch={BB9946C3-2583-4FF8-B15F-4F003A0C0A5A}\r\n
    CSeq: 0 \r\n
    Call-ID: {40D1EC11-5121-40ED-9130-1DBDA3168061}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-sessionreqbody\r\n
    Content-Length: 105\r\n
    \r\n
    EUF-GUID: {41D3E74E-04A2-4B37-96F8-08ACDB610874}\r\n
    SessionID: 1818932002\r\n
    AppID: 35\r\n
    RequestFlags: 16\r\n
    \r\n
    \x00
(17:14:21) papyon.msnp2p.transport.switchboard:>>> TLPv2 chunk 0x72506a71: blob 0, ACK 0xfe3f857e, RAK, SYN,
(17:14:21) papyon.transport:>>> MSG 40 D 252
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    P2P-Src: 'andre-stein@hotmail.com;{b75d3405-f2bb-4a0b-98a8-43e522811ea0}'\r\n
    P2P-Dest: 'kaio1337@hotmail.com;{eb260dd0-6237-48a0-8c2e-32ffa7bba79d}'\r\n
    [P2P message (28 bytes)]
(17:14:21) papyon.msnp2p.session_manager:No handler could handle euf-guid {41D3E74E-04A2-4B37-96F8-08ACDB610874}
(17:14:21) papyon.transport:<<< MSG kaio1337@hotmail.com Kaio 253
    P2P-Src: 'kaio1337@hotmail.com;{eb260dd0-6237-48a0-8c2e-32ffa7bba79d}'\r\n
    P2P-Dest: 'andre-stein@hotmail.com;{b75d3405-f2bb-4a0b-98a8-43e522811ea0}'\r\n
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    [P2P message (780 bytes)]
(17:14:21) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0xfe3f857e: blob 1, SLP Message
    INVITE MSNMSGR:andre-stein@hotmail.com;{b75d3405-f2bb-4a0b-98a8-43e522811ea0} MSNSLP/1.0\r\n
    To: <msnmsgr:andre-stein@hotmail.com;{b75d3405-f2bb-4a0b-98a8-43e522811ea0}>\r\n
    From: <msnmsgr:kaio1337@hotmail.com;{eb260dd0-6237-48a0-8c2e-32ffa7bba79d}>\r\n
    Via: MSNSLP/1.0/TLP ;branch={E9D6542F-D4BD-4591-B07B-4937B53797B5}\r\n
    CSeq: 0 \r\n
    Call-ID: {CBF5773F-18FC-4E55-85D9-65D485C48B14}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-transreqbody\r\n
    Content-Length: 302\r\n
    \r\n
    NetID: 2012558769\r\n
    Conn-Type: Port-Restrict-NAT\r\n
    TCP-Conn-Type: Port-Restrict-NAT\r\n
    UPnPNat: false\r\n
    ICF: false\r\n
    IPv6-global: \r\n
    Capabilities-Flags: 1\r\n
    Nat-Trav-Msg-Type: WLX-Nat-Trav-Msg-Direct-Connect-Req\r\n
    Bridges: TRUDPv1 TCPv1 SBBridge TURNv1\r\n
    Hashed-Nonce: {65DD646F-2414-9E0A-FFBC-B9AE88DAC383}\r\n
    \r\n
    \x00
(17:14:21) papyon.msnp2p.transport:Received transport request from kaio1337@hotmail.com;{eb260dd0-6237-48a0-8c2e-32ffa7bba79d}
(17:14:22) papyon.transport:<<< ACK 40
(17:14:22) papyon.transport:<<< MSG kaio1337@hotmail.com Kaio 252
    P2P-Src: 'kaio1337@hotmail.com;{eb260dd0-6237-48a0-8c2e-32ffa7bba79d}'\r\n
    P2P-Dest: 'andre-stein@hotmail.com;{b75d3405-f2bb-4a0b-98a8-43e522811ea0}'\r\n
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    [P2P message (16 bytes)]
(17:14:22) papyon.msnp2p.transport.switchboard:<<< TLPv2 chunk 0xfe3f8882: blob 0, ACK 0x72506a71,
(17:14:24) papyon.transport:>>> MSG 41 U 127
    TypingUser: 'andre-stein@hotmail.com'\r\n
    Content-Type: 'text/x-msmsgscontrol'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    \r\n
    \r\n```
``````

**Comment by c10ud** [comment] 2012-04-05 13:24
2.12.3

**Closed as completed by c10ud** 2012-04-05 13:24 UTC
Labels: incomplete
