### ISSUE TITLE
Messages not sent

### ISSUE THREAD

**Issue by the98** [emesene/emesene#851] opened 2011-09-09 01:47 UTC
Weird issue. Some message aren't sent. I haven't found out a pattern. I think it's totally random. Updating to the latest devel and removing the entire config directory didn't do anything.

This is what happens, you type some message send it and you see some entry adds into the conversation that has your avatar and everything, the message in there is blank, and the contact doesn't receive it.

Screenshot: http://img842.imageshack.us/img842/5769/capit.png

Regards.

**Comment by shuhaowu** [comment] 2011-09-09 03:37
This bug? https://github.com/emesene/emesene/issues/693

**Comment by Sbte** [comment] 2011-09-09 05:35
Any command line output? Because I don't think I have seen blank message lines before...

**Comment by c10ud** [comment] 2011-09-13 15:22
probably when pepe was refactoring, update or we assume it's gone

**Comment by pepeleproso** [comment] 2011-09-13 15:41
This issue was before my refactoring, so I think it's not related

**Comment by c10ud** [comment] 2011-09-13 15:52
then we need debug output, yay

**Comment by c10ud** [comment] 2011-09-26 15:00
we're approaching a release (if everything goes well), please provide feedback or we'll close this issue

**Comment by the98** [comment] 2011-09-26 16:02
It hasn't happen in a while. As I've said, I haven't found a pattern or something. It's a random thing.

Sorry.

**Comment by c10ud** [comment] 2011-09-26 16:13
ok, reopen if it happens again

**Comment by the98** [comment] 2011-10-04 15:35
It happened again. This is the output, I think there's nothing relevant here...

TERMINAL:

[18:15:06 WARNING papyon.service] Metadata: Invalid metadata
[18:16:40 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from rsi.hotmail.com:443
[18:16:40 WARNING papyon.service] Transport Error : HTTP Error (500): Internal Server Error
[18:16:40 ERROR papylib.Events] Client got an error handling offline messages: 6 Offline Message Error (s:NotAllowed): The message was not found in the OIM folder

Actually there were no outputs in the terminal. This output is when the contact spoke to me while being offline.

DEBUG Output:

(18:17:55) papyon.transport:>>> MSG 5 N 143

```
X-MMS-IM-Format: 'FN=Sans; EF=; CO=2424ae; CS=1; PF=00'\r\n
Content-Type: 'text/plain; charset=utf-8'\r\n
MIME-Version: '1.0'\r\n
\r\n
sii
```

(18:17:55) papyon.transport:>>> MSG 6 N 138

```
X-MMS-IM-Format: 'FN=Sans; EF=; CO=2424ae; CS=1; PF=00'\r\n
Content-Type: 'text/plain; charset=utf-8'\r\n
MIME-Version: '1.0'\r\n
\r\n
```

(18:17:58) papyon.transport:>>> MSG 7 N 138

```
X-MMS-IM-Format: 'FN=Sans; EF=; CO=2424ae; CS=1; PF=00'\r\n
Content-Type: 'text/plain; charset=utf-8'\r\n
MIME-Version: '1.0'\r\n
\r\n
```

(18:18:00) papyon.transport:>>> MSG 8 N 138

```
X-MMS-IM-Format: 'FN=Sans; EF=; CO=2424ae; CS=1; PF=00'\r\n
Content-Type: 'text/plain; charset=utf-8'\r\n
MIME-Version: '1.0'\r\n
\r\n
```

(18:18:05) papyon.transport:>>> MSG 9 N 148

```
X-MMS-IM-Format: 'FN=Sans; EF=; CO=2424ae; CS=1; PF=00'\r\n
Content-Type: 'text/plain; charset=utf-8'\r\n
MIME-Version: '1.0'\r\n
\r\n
vooooos?
```

As you can see, before the line "vooooos?" I wrote "vos?" (not shown because it wasn't sent). I don't know what's the difference, but sometimes when you extend the length of the word, the message gets sent.

**Comment by c10ud** [comment] 2011-10-04 17:37
I see a bunch of nasty server errors, other than that, seems like sending the oim actually failed (papyon doesn't provide an abstraction on top of this, so we (i) just check some private members and choose (hopefully) for the best) there could be something failing in all those checks

**Comment by c10ud** [comment] 2011-10-04 17:38
also: that would explain your last report, not OPs since the screenshot shows the other party is busy...did you experience the same behaviour with empty lines added?

**Comment by the98** [comment] 2011-10-04 18:41
Yes, same.

I've made a little screencast and discover some other bug. As you can see in the video, I had opened 2 accounts, one of them was of offline. When I tried to talk from the online account to the offline account I got this on my terminal:

[15:18:39 ERROR papyon.protocol.notification] Notification got error : 509 16 103
'<error><recipient n="Mymail@hotmail.com" t="1"/><details>535</details><subcode>500</subcode></error>'

And the offline account never got the first message (no window popped-up), even though it wasn't a blank message. The second one was a blank message.

Here is the link to the screencast: http://www.megaupload.com/?d=RJ3QRBRX

I hope this helps.

**Comment by Sbte** [comment] 2011-10-04 20:00
```
Traceback (most recent call last):
  File "/home/sven/emesene-dev/emesene/e3/papylib/papyon/papyon/service/SOAPService.py", line 230, in _response_handler
    handler(callback, errback, response, user_data)
  File "/home/sven/emesene-dev/emesene/e3/papylib/papyon/papyon/service/OfflineIM/rsi.py", line 63, in _HandleGetMessageResponse
    run(callback, run_id, seq_num, m.get_payload().decode('base64'))
  File "/home/sven/emesene-dev/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/sven/emesene-dev/emesene/e3/papylib/papyon/papyon/service/OfflineIM/scenario/fetch_messages.py", line 46, in __get_message_callback
    run(self._callback, id, run_id, seq_num, message)
  File "/home/sven/emesene-dev/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/sven/emesene-dev/emesene/e3/papylib/papyon/papyon/service/OfflineIM/offline_messages_box.py", line 355, in __fetch_message_cb
    message = self._messages.search_by_id(id)[0]
IndexError: list index out of range
```

Probably unrelated, but still an error.

**Comment by Sbte** [comment] 2011-10-04 20:02
Other than that error, I can't reproduce this

**Comment by Stiveknx** [comment] 2011-10-21 21:07
The same thing happens here...
I open a window in my browser with ebuddy logged in.
I open a window in emesene, and I sent the message. the message didn't show up in ebuddy, and I asked for the guy if he did received the message and he says no. 
The same thing happen sometimes with receiving messages.
There's nothing in console error (in any tab), in the same time that I sent the message.

**Comment by c10ud** [comment] 2011-11-14 14:01
if this thing is 100% reproducible i can try to see what's going on...?

**Comment by the98** [comment] 2011-11-14 14:15
Not 100%, it's random. It hasn't happened to me in a while.

2011/11/14 Riccardo <
reply@reply.github.com

> if this thing is 100% reproducible i can try to see what's going on...?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/851#issuecomment-2730653

## 

Marco

**Comment by c10ud** [comment] 2011-12-29 10:24
assuming fixed in git master

**Closed as completed by c10ud** 2011-12-29 10:24 UTC
Labels: incomplete
